### ISSUE TITLE
List of things that need to be done

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#10]
@SergeyMosin :  I am the donor [of the bounty that you are claiming](https://www.bountysource.com/issues/67911177-appointment-slot-support). Thanks for bringing the calendar function a very good step forward - well done so far!!!

@SergeyMosin :  Nice improvement in version 1.10 ! I have boded "done" tasks to the according section.

There are some things that I am still missing and that I would ask you to please add before claiming the bounty:

- If I create appointments in an _existing_ calendar "by hand" (single calendar entries, not created by "create schedule" function), in my German version of nextcloud, the category "Appointment" is not showing in the dropdown. I have to manually search it, then I find it. This will be confusing for other first time users. 

DONE:
- make single days / multiple individual days clickable in "create schedule" dialogue, for example, march 2nd, march 5th, march 9th, all in none dialogue (related to [this issue](https://github.com/SergeyMosin/Appointments/issues/5))

- please send an .ics file with the appointment confirmation email, so that the recipient can import the appointment it in her/his calendar 

- make length of appointments in "create schedule" dialogue manually configurable (e.g. add 15 mins or 20 mins slots). If that is too hard to achieve, add "15 mins", "20 mins" as preconfigured options (related to [this issue](https://github.com/SergeyMosin/Appointments/issues/4))

Sorry for not sticking to the GitHub convention "one issue per post". As I am the donor of the bounty, I thought it makes sense to communicate my thoughts and requests in a bundle. Hope you don't mind in this case.

PS: Would you be interested to work [on this bounty of mine](https://www.bountysource.com/issues/63413126-share-calendar-to-users-or-groups-with-show-only-as-busy) as well? It is also calendar related. You will find [additional specs here](https://cloud.nextcloud.com/call/pjvxs42t).

**Comment by nolens** [comment]
@SergeyMosin 
The bounty has been withdrawn. 

If you still want to claim it, please contact me.

**Comment by SergeyMosin** [comment]
@nolens  It's up to you really, but as they say: 🍺 is the best fuel for open source projects :)
