### ISSUE TITLE
Appointments disapearing

### ISSUE THREAD

**Issue by a162624** [SergeyMosin/Appointments#101]
Somehow my appointments are disapearing in the webform after some hours. also the online status of the official page is changing to offline sometimes. but even when it's online, oppointments are not avaliable in the form anymore (still are in calendar)
i am syncing the the calendar to outlook via caldav synchronizer. does that somehow affect the whole thing? noting changed in the appointments (category is still there). thanks, daniel

**Comment by SergeyMosin** [comment]
Can you post (or email me ) the ics file of a disappearing/not available appointment.

> the online status of the official page is changing to offline sometimes

When the page is offline there is the ``data-state:  [numeric code]`` line in the browser's console. Also, page goes offline when the appointments calendar is changed.

**Comment by a162624** [comment]
Hi Sergey

Thanks for comming back so quickly and the hints regarding offline-page.

You’ll find the ics in the attachment.

Thanks again

Daniel

 

Von: Sergey Mosin <notifications@github.com> 
Gesendet: Sonntag, 28. Juni 2020 14:58
An: SergeyMosin/Appointments <Appointments@noreply.github.com>
Cc: a162624 <dk@chole.ch>; Author <author@noreply.github.com>
Betreff: Re: [SergeyMosin/Appointments] Appointments disapearing (#101)

 

Can you post (or email me ) the ics file of a disappearing/not available appointment.

the online status of the official page is changing to offline sometimes

When the page is offline there is the data-state: [numeric code] line in the browser's console. Also, page goes offline when the appointments calendar is changed.

**Comment by a162624** [comment]
example of undisplayed appointment

**Comment by SergeyMosin** [comment]
@a162624 thanks for info.
Looks like 'STATUS' property is missing and 'ORGANIZER' does not have 'SCHEDULE-AGENT' parameter.
Probably something to do with caldav synchronizer. This is probably similar to https://github.com/SergeyMosin/Appointments/issues/39#issuecomment-611539164

Externally created events will be supported in the future.

**Comment by SergeyMosin** [comment]
See https://github.com/SergeyMosin/Appointments/issues/100#issuecomment-653780651
