### ISSUE TITLE
Time Table does not show Sunday at all

### ISSUE THREAD

**Issue by mau2806** [SergeyMosin/Appointments#102]
I want to create appointments for sunday but the time table does not show a column for the weekday sunday at all. I checked that with chromium and firefox web browser.

**Comment by SergeyMosin** [comment]
Yes correct no Sunday at all. If you really want to have appointments on Sunday you can just move(drag and drop) them in the nextcloud calendar.

**Comment by dolohow** [comment]
What's the reason behind not being able to do that?
