### ISSUE TITLE
Different Appointment Algorithm

### ISSUE THREAD

**Issue by akidburn** [SergeyMosin/Appointments#103]
Hi,
would it be possible to not search for free spaces in calendars and fit appointments in,
but to search for existing calendar entries where the title matches a regex, and only show those entries where the  match is positive?

Because we have 5 practitioners taking appointments on varying weekdays and times, and are also taking appointments by phone, 
and we would like to keep a large portion of that going, we just want to add an online form for appointment booking to our website.

Would this be possible?

akidburn

**Comment by SergeyMosin** [comment]
This probably should be addressed in #87
