### ISSUE TITLE
Localized company name, service descriptions, and emails

### ISSUE THREAD

**Issue by yrammos** [SergeyMosin/Appointments#106]
This is a groundbreaking plugin — congratulations to the author.

Is there provision for localization of the service/company descriptions and emails?

Thanks.

**Comment by SergeyMosin** [comment]
Assuming you are referring to values set by a user (see screenshot) than it is not possible from my end. The "strings" must be hard-coded to be translated  by the Nextcloud community on Transifex https://www.transifex.com/nextcloud/ However, it is theoretically can be done with some adjustments to the code and a couple of custom files in the``/path/to/nextcloud/apps/appointments/l10n/`` directory. There is some useful information at the bottom of this page: https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html

![user-inputs](https://user-images.githubusercontent.com/10747559/87675766-c9c4a500-c745-11ea-8e8f-ad7222767c7f.jpg)

**Comment by yrammos** [comment]
@SergeyMosin what I'm looking for is a way to make specific appointment categories visible to visitors of specific locales/languages (and hide appointment categories in all other languages).

Therefore this might be a discussion resuming when/if the app supports multiple appointment categories (e.g. as in #21).

**Comment by SergeyMosin** [comment]
Since #21 is tagged I am going close this
