### ISSUE TITLE
Set appointments any time during a 24h day

### ISSUE THREAD

**Issue by Anonym69** [SergeyMosin/Appointments#107]
What should I do to enable appointments to be set during any time during a 24h day? Right now I only see that I can have them set between 8:00am and 9:45pm (8:00 - 21:45). This is important since an appointment might be set out of my own office hours.

Thank you

**Comment by SergeyMosin** [comment]
If you really want to have meetings/appointments at 3:00 in the middle of the night you can just create a couple of extra appointments and then just drag-and-drop them around to when-ever you want in the calendar or try the "External Mode" and use Nextcloud's calendar app to create appointments as per section 8 (Time slot mode) of the tutorial.

**Comment by Anonym69** [comment]
Oh yes thank you! I see that now.

**Comment by SergeyMosin** [comment]
Thanks
