### ISSUE TITLE
Support multiple calenders as destination.

### ISSUE THREAD

**Issue by 13hannes11** [SergeyMosin/Appointments#108]
Either support the creation of multiple appointment forms by one user or allow one form to have multiple destination calendars.

Basically I would like to use your system for reserving washing machines. This means as a requirement I either need to be able to use multiple forms for one user (with different destination calendars) or to allow the selection of multiple calendars for one form.

This could look like that you can in the form select which calendar you want.

**Comment by 13hannes11** [comment]
Just noticed it's a duplicate of #21

**Comment by SergeyMosin** [comment]
Also #81 is similar, closing as duplicate.
