### ISSUE TITLE
Admin to create a booking form with custom fields/controls

### ISSUE THREAD

**Issue by Anonym69** [SergeyMosin/Appointments#109]
I have not seen that this is possible. I would like to be able to create forms with additional fields like Company name of the one booking an appointment, radio buttons/check boxes etc, drop down menus etc and also mark them as either mandatory or optional when creating the booking form.

Maybe this is possible already and if not I would like to see this as a feature if possible. 
I realize that it depends on the calendar too, but if that is a limitation then the form fields could perhaps be what I suggested (and mark them as mandatory or optional to complete the booking) and then add them into the Description field in the calendar.

Awesome plugin! Good work and very useful.

**Comment by SergeyMosin** [comment]
Unfortunately it is not possible yet.
Since #24 is the placeholder for form customization ideas, I am closing this but the discussion can continue there.
