### ISSUE TITLE
Add ajax/zones.json to build

### ISSUE THREAD

**Issue by kesselb** [SergeyMosin/Appointments#112]
It seems that with the default nginx configuration (https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html) .json files from ajax/ folder are not served by the webserver. 

![image](https://user-images.githubusercontent.com/3902676/87976712-db9fa280-cacd-11ea-85ca-9d66bb1d667b.png)

I would suggest to include ajax/zones.json in the build process with script.js. A workaround could be to rename zones.json to zones.js.

**Comment by SergeyMosin** [comment]
In v1.6.6 the zones.json file is renamed to **zones.js** 

Thanks

**Comment by kesselb** [comment]
You are welcome
