### ISSUE TITLE
[feature] allow multiple calendars to provide "busy" timeslots

### ISSUE THREAD

**Issue by eleith** [SergeyMosin/Appointments#113]
i have multiple calendars to coordinate, but only one is used as the destination for appointments.

if i could specify additional calendars to check for "busy" time slots, then the public page would only show true appointments for which there are no conflicts.

the workaround for now is to remove appointments manually from the source calendar when conflicts are spotted from other calendars.

**Comment by nolens** [comment]
This should now be possible in version 1.7. 

@SergeyMosin 
Is this feature available for contributors only - with the new contributor key?

**Comment by nolens** [comment]
To re-iterate this **enhancement suggestion**: 

- introduce the option to **define different source calendars with one target calendar**

(use case: Do not offer a free time slot if either private or business calendar are busy)

@SergeyMosin 
Would this be possible? I think this would be useful.

**Comment by SergeyMosin** [comment]
v1.8.* in `weekly template` mode there is now `Check for conflicts in…` setting.

**Comment by nolens** [comment]
@SergeyMosin 
I am using external mode only...
Any chance to have this functionality in external mode, too ?

Best 
Thomas
