### ISSUE TITLE
[Feature] Larger (configurable) Slots

### ISSUE THREAD

**Issue by Stew-rt** [SergeyMosin/Appointments#114]
My appointments are allotted in Days (usually spanning around 8 hours), my minimum slot size is 1/2 a day.
Would it be possible to add the possibility for Appointments to account for this and have perhaps 3 options a client can book for, i.e:
I could pre-configure:
morning
afternoon
whole day

**Comment by SergeyMosin** [comment]
Currently it is not directly possible, but you can adjust appointment length in the calendar app and/or use the external mode. You can also add a title, like "Morning Session" for example as per https://github.com/SergeyMosin/Appointments/issues/97

**Comment by Stew-rt** [comment]
Thanks, I've figured it out.. might have more of a play with this later
