### ISSUE TITLE
When moving appointments, confirmation link is missing in push email

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#116]
Hello there,

- I am moving an appointment in my calendar. 
- notification email is sent to my client
- in this email, text sais "to confirm the new appointment, please click link below"
- but there is no link in the email! 

Can you check and fix this?

My setup: 
- using apple calendar app
- native mail app in MacOSX
(both latest versions)

Thanks and regards
Thomas

**Comment by SergeyMosin** [comment]
Fixed in v1.6.8
Appointments **_booked_ before v1.6.8** are still affected, use Nextcloud's calendar app if you need to move appointments **_booked_ before v1.6.8**

Also please up-vote https://github.com/nextcloud/server/issues/22197 issue for more robust solution.

**Comment by nolens** [comment]
@SergeyMosin 
I have upvoted the issue. 

Now, the attendee/participant is getting the message "Your scheduled details have changed....[changed details] and an updated .ics file. 

When I double click the .ics file, I cannot see wether a participant has confirmed the new date or not. 

Clicking the confirmation link in the "two step invitation process" always produced the "confirmed" tick in the macOS calendar app. 

Why not use the confirmation link? Does this have to do with the nextcloud/server issue you mentioned above?

**Comment by SergeyMosin** [comment]
Are you moving a ``confirmed`` or a ``pending (not yet confirmed by the attendee)`` appointment ?

**Comment by nolens** [comment]
In my setup, I am skipping the confirmation step, so it is a `confirmed` appointment.

**Comment by SergeyMosin** [comment]
OK, I see what's happening...
When moving a confirmed appointment in mac calendar it changes attendee's ``PARTSTAT`` (participation status) from ``ACCEPTED`` to ``NEEDS-ACTION`` automatically :( without asking.

Two possible solutions:
1. It can pe changed back to what it was before the move automatically
2. Ask the attendee to re-confirm

What do you think ?

**Comment by nolens** [comment]
Can we do both? 

This might seem a little "over the top", but here's why I think both would be great: 

- some systems do not recognize the .ics files automatically
- some users don't notice or "overlook" the reconfirmation link

So If the notification email about change of time/date would contain a reconfirmation link and an .ics file, this would be the most "failsafe" solution that I can think of.... 

Don't you think?

**Comment by nolens** [comment]
Implemented in version 1.7
