### ISSUE TITLE
Visual translation typo

### ISSUE THREAD

**Issue by Ozzie76** [SergeyMosin/Appointments#119]
Great work Sergey, thank you!!! My apologies for posting the typo here, but I was unsuccessful in branching and making an account on Transiflex didn't help either.

There is a pretty visual typo in 2 translation files.
1: filel10n/nl.js on line 44 
2: file l10n/nl.json on line 42
    "Book Your Appointment" : "Reserveer ja afspraak",
should be
    "Book Your Appointment" : "Reserveer je afspraak",

**Comment by SergeyMosin** [comment]
Should be fixed in v1.7.0.
You can also change it in the ``Customize Public Page > Form Title``

![translations](https://user-images.githubusercontent.com/10747559/92313168-72e58a00-ef96-11ea-9c93-4dda8ee39229.jpg)

**Comment by Ozzie76** [comment]
Fixed, thank you!!
Wouldn't changing the "Customize Public Page > Form Title" mess up the multi lingual capabilities of the form? I'm using it both in English and Dutch and am amazed you are supporting this right out of the box!
Awesome, thank you!!
