### ISSUE TITLE
Adding iframe-resizer

### ISSUE THREAD

**Issue by kominoshja** [SergeyMosin/Appointments#121]
The iframe feature is awesome, as it provides a smooth experience for users, however, sizing the frame is a bit complicated. 

I came across this and thought it might be a good idea to implement it so that iframe can then be the perfect size for all users: https://github.com/davidjbradshaw/iframe-resizer

**Comment by kominoshja** [comment]
The end goal is to only have the form framed into the site, and not the entire html content. If we are approaching this wrongly please let us know!

**Comment by SergeyMosin** [comment]
Look like the iframe-resizer is [used outside](https://github.com/davidjbradshaw/iframe-resizer#typical-setup) of the iframe.

> RE: The end goal is to only have the form framed into the site, and not the entire html content

Whatever is served from the "embedable" URL is as minimalistic as the smallest Nextcloud template allows. Though it is possible to make an end-point that would only serve the ``<form>...</form>`` HTML along with inline JS and CSS, but it is a completely different issue.

**Comment by kominoshja** [comment]
From the same link you posted:

> The second file (iframeResizer.contentWindow.min.js) needs placing in the page(s) contained within your iFrame. This file is designed to be a guest on someone else's system, so has no dependencies and won't do anything until it's activated by a message from the containing page.

Shouldn't this be done from the Appointments app?
