### ISSUE TITLE
[Bug] Public link for "second page" results in "file not found"

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#123]
I have created a second page. In the backend, I can see the preview, also slots shown in the preview (If I change them from "busy" to "free" as described in #122)

But the public URL does not render - Error is saying: "file not found"

**Comment by nolens** [comment]
@SergeyMosin 
Can you replicate this behavior?

**Comment by Dubidubiduu** [comment]
Same for me

**Comment by nolens** [comment]
@SergeyMosin 

Solved.
Cool. ;=)
