### ISSUE TITLE
Make additional email text form dependent

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#126]
I use two forms. In these, I use two different links to videoconferencing.

There is only one setting "Zusätzlicher E-Mail-Text zur BESTÄTIGUNG:" (additional text for mail approving). In this I would like to tell the link for the videoconference again, but this is not possible, as I use two different links.

Maybe working with %link%-var could do the job, or alternatively move that setting to the singular forms.

**Comment by SergeyMosin** [comment]
available since v2
