### ISSUE TITLE
Use Nextcloud Locale for slot selection calendar view and public form

### ISSUE THREAD

**Issue by basti1982** [SergeyMosin/Appointments#128]
It seems that the English locale (e.g. "Monday, Septermber 14, 2020, 10:00 AM") is always used, although another locale, in my case "German" is set in the Nextcloud admin.

Using the locale that is set in Nextcloud would make sense here.

![2020-09-11_10-51](https://user-images.githubusercontent.com/38282605/92897524-8f157b00-f41d-11ea-895d-935a87045cc7.png)
![2020-09-11_10-50](https://user-images.githubusercontent.com/38282605/92897530-8fae1180-f41d-11ea-92e9-bf7976bd3a81.png)

**Comment by SergeyMosin** [comment]
These are actually depend on visitor's browser locale. All modern browser should be supported. What browser are you using ???
However, I can also add an override option to force a locale.

![locale](https://user-images.githubusercontent.com/10747559/92921229-ad6d7d80-f401-11ea-81a3-52be9fd558be.jpg)

**Comment by basti1982** [comment]
Im using Chromium on Debian 10, the browser language is set to English and the Nextclouad language to German. I just wondered why everything else is translated, but not the time and date.

**Comment by SergeyMosin** [comment]
Time and date grids are generated by JS in a browser and therefore translated to the language/locale set by the browser, in your case it is English. However, I'll add an option to the settings to force the Time/Date translation into language set by Nextcloud.

**Comment by basti1982** [comment]
That would be great!

**Comment by SergeyMosin** [comment]
As of version 1.7.6 "front-end" locale is set to the language set by Nextcloud. This the default and NOT optional, because having two different languages is just too confusing.
