### ISSUE TITLE
Feature request: Requester can select meeting duration

### ISSUE THREAD

**Issue by alex9434** [SergeyMosin/Appointments#129]
Would it be possible to have the meeting requester select meeting duration? E.g. I provide a meeting slot from 10am to 4pm and the external meeting requester can then schedule a meeting starting at 11.30 for 45 min? 

Maybe have a drop-down or radio box with 15min, 30min, 45min, 1h and 1.5h. This way different requester can allocate different amount of time. It would be similar to hubspot (see screenshot). Also it would be good if the visitor can see and change the timezone for the appointments.

![image](https://user-images.githubusercontent.com/8560446/93208719-99be7000-f78f-11ea-9846-ed83c19ad411.png)

They have also a very convenient way to select the date:
![image](https://user-images.githubusercontent.com/8560446/93210786-cde76000-f792-11ea-8257-553c51d08303.png)

**Comment by SergeyMosin** [comment]
This should be available when #87 (weekly template mode) is implemented.
@alex9434 how does the "select the date" (second screen-shot)  look on mobile devices?

**Comment by alex9434** [comment]
I really like the idea with the weekly template. For me it is important that the requester can determine the length within much larger blocks of available time.

Here is the first screen. I have deleted the top part of that screen that contains: Company logo, Picture and name of the person below (gives a nice and personal touch) and then the date picker:
![image](https://user-images.githubusercontent.com/8560446/93658063-d7aae500-fa6a-11ea-910e-4763b6b981a3.png)

If you click on any date, you get to the second screen:
![image](https://user-images.githubusercontent.com/8560446/93658072-f27d5980-fa6a-11ea-8a8e-0d6d5b5fb20a.png)
I really like that you can select meeting duration and time zone to spare yourself complicated calculations.

**Comment by jpbraun** [comment]
Very nice idea.

**Comment by alderson59** [comment]
Any updates on this? Much needed feature! Calendly replacement 👍 

Thanks for such an amazing plugin @SergeyMosin :)

**Comment by SergeyMosin** [comment]
Starting from v1.8.* in `weekly template` mode it is possibly to preset multiple appointment durations and a visitor will be able to select one of them.
