### ISSUE TITLE
[feature] Re-using canceled time slot

### ISSUE THREAD

**Issue by philjak** [SergeyMosin/Appointments#131]
Hello everyone,

not sure if this already works, but when I tried it did not.

Let's say I have 3 timeslots for one day. If a user books this slot and cancels this booking later on, it'd be great to give his/her slot back to the pool of available slots, so that someone else can book that time slot.

What do you think?

Thanks,
philjak

**Comment by SergeyMosin** [comment]
``Settings > Advanced Settings > When Attendee Cancels: ...``

**Comment by philjak** [comment]
You're awesome! Thanks for your quick reply!
