### ISSUE TITLE
html for Additional Email Text

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#132]
html tags would be conditionally very helpful for the mail text:
- CRLF (<br>)
- Link (<a href=.....)
- Bold (<strong>)

**Comment by mhoeppner-le** [comment]
YES, that would be great.

Matthias from rad3
already funding the project (calendar name in mail text ==> would be better in subject text)

**Comment by Vince2956** [comment]
Yes, it would be nice to be able to customize the signature.

**Comment by SergeyMosin** [comment]
Fixed in v1.12.6
