### ISSUE TITLE
[Minor Feature Request] Show Time Zone for Booking User

### ISSUE THREAD

**Issue by alderson59** [SergeyMosin/Appointments#133]
It would be really good to show the time zone of the booking user. When they see a list of times, it isn't immediately obvious to them what the time zone of the time slots are. I've had several back and forths from users about the exact timing.

I've made a mockup of what it could look like.
![Untitled-1](https://user-images.githubusercontent.com/69715968/94349375-68d71880-0076-11eb-93c1-325295b0cf58.jpg)

It could just be a way to pull the user's time zone using their browser session.

**Comment by SergeyMosin** [comment]
There is ``Settings > Public Page Settings > Advanced Settings > Show timezone`` it just show tz abbreviations. There are plans for redesign, something similar to #129 , see the second screenshot for timezones https://github.com/SergeyMosin/Appointments/issues/129#issuecomment-695157513
