### ISSUE TITLE
HowTo edit "Customize email text:" for Talk integration?

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#134]
How I can edit "Customize email text:"?
By click only the faq will be open.

**Comment by SergeyMosin** [comment]
It is a contributor only feature, did you get your contributor key ?

**Comment by RoundAboutWEB** [comment]
Where can I pay and how much?

**Comment by SergeyMosin** [comment]
Info https://github.com/SergeyMosin/Appointments/issues/79#issuecomment-687659269 and general funding discussion is here #79

Thanks
