### ISSUE TITLE
Make lead time freely configurable

### ISSUE THREAD

**Issue by seichter** [SergeyMosin/Appointments#135]
Currently the maximum lead time seems 2h. In my case even 2h is way too much. I would prefer something like 24h to avoid students (in my case) to bomb my calendar. I think other users of appointments have even more diverging requirements. So a simple textfield to put in a time would be a great help.

**Comment by PhilippWoelfel** [comment]
Same here - need a lead time of at least 1 day. A text field may not be easy to implement, but having additional longer lead time options (e.g., 8h, 12h, 24h, 48h) would be very helpful.

**Comment by Jaxom99** [comment]
As a first step, you could update the #155 PR with more time-slots :wink:

**Comment by Dracorubio** [comment]
This would be a great addition!!

**Comment by SergeyMosin** [comment]
There are additional options are available in 1.8.*

![image](https://user-images.githubusercontent.com/10747559/109002094-bed6d900-7673-11eb-87a0-8d141eefa6f9.png)
