### ISSUE TITLE
Location for booked appointments incorrect 

### ISSUE THREAD

**Issue by pagaille** [SergeyMosin/Appointments#136]
Hi,

I use two calendars for availability slots with "At the office" or "At your premises" defined in the location field. That works, but in the booked appointment calendar all location fields are set to "At your premises".

Let me know if I can help further.

**Comment by SergeyMosin** [comment]
Confirmed. Thanx.

**Comment by SergeyMosin** [comment]
fixed in v1.7.7

**Comment by nolens** [comment]
@pagaille 
If the new version has solved your problem, please close this issue. 
Otherwise, please specify. 
Thanks.

**Comment by pagaille** [comment]
Yep I’ll check this week. Txs already !

Matthieu G.  (en mode mobile)

**Comment by pagaille** [comment]
Fix working, issue can be closed. Thanks for the quickfix !

**Comment by pagaille** [comment]
Just a note : I wish the location could be written to the confirmation email. But it might be a very personal case.

**Comment by SergeyMosin** [comment]
@pagaille Goog idea, btw the location is written to the .ics if you ``Email Settings > Attach .ics file to confirm/cancel emails``

**Comment by pagaille** [comment]
Sure. My user case is particular : since I have to use Outlook I must create each booked event by hand in my calendar. That's why I want to receive the location as well. Maybe attaching the ICS in the organisator's confirmation email might be a good solution.
