### ISSUE TITLE
Allow people to book appointments which are MORE than 5 weeks in future

### ISSUE THREAD

**Issue by philjak** [SergeyMosin/Appointments#137]
Hello,

is there a way to allow people booking apointments which are in more than 5 weeks from now on? Let's say I have just one slot per week, it'd be a pity if only 5 people could do their bookings.

![image](https://user-images.githubusercontent.com/5772650/94908427-ee592f00-04a1-11eb-9691-79870bf772f3.png)

Thanks,
philjak

**Comment by jpbraun** [comment]
I agree. I would prefer an integer field for days or weeks.

**Comment by practical-solutions** [comment]
This App ist great but indeed also it would help a lot, if it was possible to book appointment for more than 5 Weeks...

**Comment by nolens** [comment]
Yes, also on my side, would be really very helpful to be able to chose the amount of weeks to "book ahead" freely!

**Comment by nolens** [comment]
@philjak 
Booking appointments **up to 12 weeks** in the future is now possible via **dropdown-menu** since [version 1.7.11](https://github.com/SergeyMosin/Appointments/releases/tag/v1.7.11)

**Comment by philjak** [comment]
@nolens Awesome, thanks for this info!
