### ISSUE TITLE
Nextcloud 20 & Appointments 1.7.7

### ISSUE THREAD

**Issue by jpbraun** [SergeyMosin/Appointments#139]
"Warning - Can't find Talk app. Is it installed and enabled?"

This is a new bug since Nextcloud 20.

![2020-10-09_160320](https://user-images.githubusercontent.com/31374152/95592489-ffc5ac80-0a48-11eb-900e-39380e93d42e.jpg)

**Comment by SergeyMosin** [comment]
Fixed in v1.7.8 _(But the NC app store is down now - Oct. 10, 8:00EDT)_
