### ISSUE TITLE
enable schedule generator to create appointments after 5pm

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#14]
After 5pm, it seems impossible to create appointments with schedule generator. Please implement the possibility to add appointments to all hours - some of us work until late... ;=)

Thanks!

**Comment by nolens** [comment]
Done in version 1.10

**Comment by ingoha** [comment]
Where is version 1.10? I would like to try this out before the release ;-)

**Comment by nolens** [comment]
Just download / or update (to) the latest version of the app.

**Comment by ingoha** [comment]
Hm, I have the most recent version installed (1.1.16). And I can't create time slots after 7pm. Am I missing something?

**Comment by SergeyMosin** [comment]
7pm is the cut off. How late do you work?

**Comment by ingoha** [comment]
10pm Could this be configurable?

**Comment by ingoha** [comment]
btw: Should the public link work without authentication? It does not for me :-/

**Comment by SergeyMosin** [comment]
Yes no authentication required.
Can you open a new issue and provide the link.
Thanks
