### ISSUE TITLE
Get HTTP ERROR 500 when trying to make a reservation

### ISSUE THREAD

**Issue by linkstat** [SergeyMosin/Appointments#141]
I get HTTP ERROR 500 when trying to make a reservation. Sometimes when retrying (refresh), it succeeds, but most of the time the refreshed page indicates that it is necessary to try again.
This is the error from the log:
[PHP] Error: Declaration of OCA\Appointments\Email\EMailTemplateNC::addBodyListItem(string $text, string $metaInfo = '', string $icon = '', $plainText = '', $plainMetaInfo = '') must be compatible with OCP\Mail\IEMailTemplate::addBodyListItem(string $text, string $metaInfo = '', string $icon = '', $plainText = '', $plainMetaInfo = '', $plainIndent = 0) at /var/www/nextcloud/apps/appointments/lib/Email/EMailTemplateNC.php#49

POST /index.php/apps/appointments/pub/nz3wCaFEpV14/form
from 10.252.252.3 by admin at 2020-10-09T20:25:13+00:00

**Comment by linkstat** [comment]
I'm using Appointments 1.7.7 on Nextcloud 20.0.0 running on Debian Buster (installed yesterday). Other software versions: PHP 7.3.19  PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1).
I have the installation with an optimal configuration (cache values, PHP, etc. except for the HSTS configuration, which I will not enable until I have the site in production). I can also send test emails from the Nextcloud administrator account (which is the one I am using to do the tests).

This is another error that I see in the log:
[no app in context] Error: Select different time

POST /index.php/apps/appointments/pub/dIi3TX_EKMdMxs801/form
from 10.252.252.3 at 2020-10-09T20:24:24+00:00

**Comment by SergeyMosin** [comment]
Oh, see... The app has not been tested with NC20 yet. Is NC20 in stable release channel already?
I'll take a look at it this weekend.

Thanks.

**Comment by linkstat** [comment]
Yes. At the moment, Nextcloud 20 is the last stable version. It was published last October 3

**Comment by SergeyMosin** [comment]
Fixed in v1.7.8 _(But the NC app store is down now - Oct. 10, 8:00EDT)_

**Comment by nolens** [comment]
@linkstat 
The problem is solved. Please close this issue now.

**Comment by linkstat** [comment]
Thanks you @SergeyMosin !!!
