### ISSUE TITLE
No translation to Spanish. Sent mails are in english language

### ISSUE THREAD

**Issue by linkstat** [SergeyMosin/Appointments#142]
Hello.
My NExtcloud instance is allin Spanish language. But, Appointments is fully in english, except for the text of buttons in the email confirmation (Confirmar / Cancelar).
I see that the project have a l10n folder with many variatns of spanish, and a file translationtool.phar (withno spanish at all inside).  So...

What can I contribute with translation for spanish language?

Regards!

**Comment by jpbraun** [comment]
Same problem with German Language (Nextcloud 20 & Appointments 1.7.9). With Nextcloud 19 & Appointments 1.7.7 the Mails were in German.

**Comment by SergeyMosin** [comment]
I can not reproduce, but I'll do an other release with the latest files from [transifex](https://www.transifex.com/nextcloud/nextcloud/) just in-case.

NC20:

![email-translations](https://user-images.githubusercontent.com/10747559/95860800-8cfd4f80-0d2e-11eb-83a6-9e8d4a174769.jpg)

**Comment by SergeyMosin** [comment]
v1.7.10 is int store, see if it helps

**Comment by jpbraun** [comment]
v1.7.10 resolved the issue.

**Comment by nolens** [comment]
@linkstat 
The issue is resolved. Please close this thread now.

**Comment by linkstat** [comment]
Thanks you so much @SergeyMosin !!!
