### ISSUE TITLE
Enable requester to request n appointments in a row

### ISSUE THREAD

**Issue by Kogoro** [SergeyMosin/Appointments#147]
I have the use case, where my university sailing club is teaching student how to sail.
As a requirement they need to work for 4 weeks at the workshop so that the boats are maintained.
So at each week, we teach 4 students in an overlapping order, so that at each week we have a new student who can learn from his/her predecessors.

As I can see in #130 , I could create appointments for each of the students in a different calendar, which would be no problem, but there is currently no way to generate 4 meetings in the next 4 weeks.
Is there any way to achieve it, so that only one person can book a recurring appointment?

**Comment by SergeyMosin** [comment]
I think I get the idea. tagging #87 (weekly template) , maybe there is going to be a way to have **multiple overlapping templates**
