### ISSUE TITLE
canceled appointment should be bookable again

### ISSUE THREAD

**Issue by jpbraun** [SergeyMosin/Appointments#149]
A canceled appointment gets deleted. It would be much better if the appointment slot could get selected and booked again.

**Comment by SergeyMosin** [comment]
Have you tried ``Settings > Advanced Settings > When Attendee Cancels: ...``
Are you using ``simple`` or ``external`` mode ?

**Comment by jpbraun** [comment]
Hi Sergey,

Screenshot 1
[cid:image003.png@01D6AD39.8805C930]


Screenshot 2 (canceld)
[cid:image004.png@01D6AD39.8805C930]

Screenshot 3
[cid:image002.png@01D6AD39.BE15A900]


Screenshot 4

[cid:image006.png@01D6AD3A.54E795A0]

Best regards,

Jan

-------------------------------------------------------------------------------
Dr. Jan-Peter Braun
  Schulleiter
    braun@igs-lengede.de<mailto:braun@igs-lengede.de>

    Integrierte Gesamtschule Lengede
      Bodenstedter Weg 35
      38268 Lengede
      Tel.: 05344 262920-10
      Fax: 05344 262920-11
      Homepage: http://www.igs-lengede.de<http://www.igs-lengede.de/>

       Schulleitung: Dr. Jan-Peter Braun, Hans Knobel, Kathrin Böke, Kerstin Jasper, Oliver Virkus
       Schulnummer: 80330 (Niedersachsen) - Schulträger: Landkreis Peine

[Logo_Smart School_RGB]

Ausgezeichnet 2020 vom Branchenverband bitkom
mit dem Bildungspreis als digitale Vorreiterschule..

Von: Sergey Mosin <notifications@github.com>
Gesendet: Mittwoch, 28. Oktober 2020 14:45
An: SergeyMosin/Appointments <Appointments@noreply.github.com>
Cc: Jan-Peter Braun <braun@igs-lengede.de>; Author <author@noreply.github.com>
Betreff: Re: [SergeyMosin/Appointments] canceled appointment should be bookable again (#149)


Have you tried Settings > Advanced Settings > When Attendee Cancels: ...
Are you using simple or external mode ?



**Comment by SergeyMosin** [comment]
Jan, unfortunately I can not see the screenshots. Must be email --> github thing...

**Comment by jpbraun** [comment]
Hi Sergey,

I send the mail to sergey@srgdev.com<mailto:sergey@srgdev.com>.

Best regards,

Jan



-------------------------------------------------------------------------------
Dr. Jan-Peter Braun
  Schulleiter
    braun@igs-lengede.de<mailto:braun@igs-lengede.de>

    Integrierte Gesamtschule Lengede
      Bodenstedter Weg 35
      38268 Lengede
      Tel.: 05344 262920-10
      Fax: 05344 262920-11
      Homepage: http://www.igs-lengede.de<http://www.igs-lengede.de/>

       Schulleitung: Dr. Jan-Peter Braun, Hans Knobel, Kathrin Böke, Kerstin Jasper, Oliver Virkus
       Schulnummer: 80330 (Niedersachsen) - Schulträger: Landkreis Peine

[Logo_Smart School_RGB]

Ausgezeichnet 2020 vom Branchenverband bitkom
mit dem Bildungspreis als digitale Vorreiterschule..

Von: Sergey Mosin <notifications@github.com>
Gesendet: Mittwoch, 28. Oktober 2020 15:00
An: SergeyMosin/Appointments <Appointments@noreply.github.com>
Cc: Jan-Peter Braun <braun@igs-lengede.de>; Author <author@noreply.github.com>
Betreff: Re: [SergeyMosin/Appointments] canceled appointment should be bookable again (#149)


Jan, unfortunately I can not see the screenshots. Must be email --> github thing...



**Comment by SergeyMosin** [comment]
I am trying to reproduce but no luck sofar in NC18. You are use NC20 right ? I'll try on my other machine(NC20) later...

**Comment by jpbraun** [comment]
Hi Sergey,

We are using Nextcloud 20. Do you need access?

Best regards,

Jan



-------------------------------------------------------------------------------
Dr. Jan-Peter Braun
  Schulleiter
    braun@igs-lengede.de<mailto:braun@igs-lengede.de>

    Integrierte Gesamtschule Lengede
      Bodenstedter Weg 35
      38268 Lengede
      Tel.: 05344 262920-10
      Fax: 05344 262920-11
      Homepage: http://www.igs-lengede.de<http://www.igs-lengede.de/>

       Schulleitung: Dr. Jan-Peter Braun, Hans Knobel, Kathrin Böke, Kerstin Jasper, Oliver Virkus
      Schulnummer: 80330 (Niedersachsen) - Schulträger: Landkreis Peine

[Logo_Smart School_RGB]

Ausgezeichnet 2020 vom Branchenverband bitkom
mit dem Bildungspreis als digitale Vorreiterschule..

Von: Sergey Mosin <notifications@github.com>
Gesendet: Mittwoch, 28. Oktober 2020 17:06
An: SergeyMosin/Appointments <Appointments@noreply.github.com>
Cc: Jan-Peter Braun <braun@igs-lengede.de>; Author <author@noreply.github.com>
Betreff: Re: [SergeyMosin/Appointments] canceled appointment should be bookable again (#149)


I am trying to reproduce but no luck sofar in NC18. You are use NC20 right ? I'll try on my other machine(NC20) later...



**Comment by SergeyMosin** [comment]
@jpbraun I'll try to reproduce on my NC20 machine first.

**Comment by SergeyMosin** [comment]
I can not reproduce this even in NC20

I have tried the following with both single and dual calendars:

1. book > cancel (without confirming)
2. book > confirm > cancel
3. book in-person meeting > change meeting type > cancel
4. book virtual meeting > change meeting type > cancel
5. book virtual meeting > delete talk room > cancel

There was a minor (fixed in v1.7.12) non critical error, which might have affected your particular setup. An other unlikely, way this might possibly happen is if appointments were created in an older version (pre 1.7.x) of the app.

Are there any errors in your logs ?

**Comment by jpbraun** [comment]
Thank you very much.

I tried it again. It works now. It is quite strange. Wie tried it a few times with three different users. We tried it with NC 20. A few days ago we updates to NC 20.0.1. Maybe this is the reason.
