### ISSUE TITLE
no transifex commits if no changes apply

### ISSUE THREAD

**Issue by mokkin** [SergeyMosin/Appointments#150]
If there are no changes in translations, for a better overview about code changes no commit should be done like here:
https://github.com/SergeyMosin/Appointments/commit/897c06cfcd6b6f93be36590d55f0406d1e8d08a1

**Comment by SergeyMosin** [comment]
I am not sure what you mean, the https://github.com/SergeyMosin/Appointments/commit/897c06cfcd6b6f93be36590d55f0406d1e8d08a1 commit is by the @nextcloud-bot , should I forward this that team ?

**Comment by mokkin** [comment]
For example. If you cannot influence that by yourself, just tell them.
I find it way clearer to see only real changes.

**Comment by SergeyMosin** [comment]
I really have no control over this
