### ISSUE TITLE
5 Minute Slots

### ISSUE THREAD

**Issue by KnudH** [SergeyMosin/Appointments#151]
It would be awesome if it would be possible to add time slots with a duration of 5 minutes.

**Comment by SergeyMosin** [comment]
Have you tried "external" mode. It is also possible to adjust an appointment's duration in the calendar app. This probably will be implemented in #87 (weekly template mode)

**Comment by SteBoun** [comment]
When i used "external" mode, My appointment does an infinity loop and crash.
I find a little solution for this, I limited my calendar to 2 months.
Do you have a solution for expend this calendar ?

**Comment by SergeyMosin** [comment]
> My appointment does an infinity loop and crash

Is there anything useful in NC logs after the crash by any chance ?
