### ISSUE TITLE
Allow requester to book several (adjacent slots) in a row

### ISSUE THREAD

**Issue by guitchok** [SergeyMosin/Appointments#156]
Thanks for this app which is super needed !

I wish I could run this "simple" use case though : I would like the requester to be able to book several slots in a row OR choose the duration of his/her appointment (although the latter choice does not seem possible since I need to declare available slots with specific duration in advance).

Would it be possible ?

I had a look at #147 but it seems a slightly different use case... not implemented yet :)

**Comment by SergeyMosin** [comment]
Duplicate #129 , more info here: https://github.com/SergeyMosin/Appointments/issues/129#issuecomment-694930361
