### ISSUE TITLE
Parallel TimeSlots

### ISSUE THREAD

**Issue by joesch2** [SergeyMosin/Appointments#159]
A great project. Thanks a lot for this!

Would it be possible to also allow parallel slots when creating time slots? For some purposes it is helpful to be able to offer two (or more) appointments in parallel. Currently, this only works by creating several booking calendars.
![Unbenannt](https://user-images.githubusercontent.com/18378305/100082556-aa066180-2e48-11eb-90ed-70aa2f22b74b.PNG)

Many thanks!

**Comment by ei8fdb** [comment]
"For some purposes it is helpful to be able to offer two (or more) appointments in parallel"

I'm curious - what purposes would that be useful for? I don't understand why you'd want to do that.

If it's the same day, then would unique session times be what was required? If it was a different day then it's not parallel. 🤔

**Comment by joesch2** [comment]
In my specific use-case, I would like to let athletes book training times in one and the same room so as not to exceed the maximum number of users.

**Comment by radoeka** [comment]
How to implement the following, a barbershop with 2 hairdressers.  Select either one of hair dressers, to make an appointment.  Besides include the treatment.  (Never realized that this is a not too easy to do, until now).  See following screenshot and url where this particular selection can be done: https://www.barbershophilversum.nl/online-afspraak-maken/

![image](https://user-images.githubusercontent.com/2937666/105628652-675c0800-5e3e-11eb-9074-89104b7a8eb5.png)

Might work as a source of inspiration.

**Comment by SergeyMosin** [comment]
Parallel time slots will be available in the next version. 

@radoeka I would use directory page https://github.com/SergeyMosin/Appointments/issues/21#issuecomment-696738211 for barbers and then an extra field for the haircut type https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-721103321

**Comment by evertvanvliet** [comment]
@SergeyMosin, this is not an option for instance if you run a tanning bed shop, where you reserve the bed while part of the time (mainly at the start) an employee will guide the person to the right bed. In that case the employee can start helping a new guest while the first one is enjoying the tanning bed. Should you use then "lead time"?
 So, 10 min for the employee while you set the lead time at 30 min.

**Comment by evertvanvliet** [comment]
@SergeyMosin and what to do if the type of haircut is defining the time required to be reserved? Here it would be usefull to add some more interaction via the json add-on (eg abillity to do som if then statements to interact with the customer). So if the beard is selected the customer should reserve a timeslot of 15 minutes while for a regular haircut 2x15 minutes is required.
