### ISSUE TITLE
On Public page, only appointments within the next 10 days are showing

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#16]
If I create appointments 4 weeks (or more) in advance, only appointments within the next 10 days are showing in the dropdown.

**Comment by SergeyMosin** [comment]
v 1.1.1 fix minor fix is out, it should be available over OTA in the next 30min

**Comment by nolens** [comment]
Looks like 14 days are showing in advance now - why not show **all** available slots that are available, e.g. also 6 weeks in advance?

@SergeyMosin 
Very good improvements since version 1.09 !!!

**Comment by SergeyMosin** [comment]
5 weeks in v1.1.3

**Comment by nolens** [comment]
Cool!
