### ISSUE TITLE
Available Slots Not Showing Up

### ISSUE THREAD

**Issue by LittleDuke** [SergeyMosin/Appointments#160]
For some reason the system is not showing my available slots for external calendar mode -- no changes on our side other than taking in last version !?

**Comment by SergeyMosin** [comment]
Can you check timezone for the event and/or send me the .ICS file at sergey [at] srgdev.com

**Comment by LittleDuke** [comment]
It was the "floating" timezone issue.  Thanks for the fast follow-up!  Fixing it now...
