### ISSUE TITLE
future request: upload files

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#161]
It would be helpful if the form could also be used to upload files for an event (PDF, jpg, ...)

**Comment by LittleDuke** [comment]
Not sure that I agree this is the right place to put something like that -- it would likely get abused by bots and malware eventually requiring a CAPTCHA plugin.   NextCloud already has an easy way to share a folder with someone for file upload.

Can you walk through a user story you have in mind?

**Comment by RoundAboutWEB** [comment]
Example:
A customer wants to talk about a specific screenshot during a telephone appointment. It would be helpful if the customer can already submit the screenshot (file) via the form.

Of course, the customer can also send the data by other means, but it is easier for the customer to do everything important at a central location.

**Comment by LittleDuke** [comment]
IMHO that just sounds like a vector for malware to me -- honestly the right place to share images DURING a call is using something like Zoom or any one of the other tele-meeting services.  Your other option would be a ticketing system like RedMine or zendesk etc.
