### ISSUE TITLE
[BUG] Wrong calendar entries when "booking more than 5 weeks ahead" is switched on

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#162]
Hello @SergeyMosin,

**My settings:**
- I am using "make slots available 12 weeks ahead" option
- I have 4 different calendars

**My observation**
When using "make slots available 12 weeks ahead" option, two strange things happen: 
1. Open Slots from calendar 3 are showing in the public URL of calendar 1
2. Open slots that I have already deleted in calendar 1 are still showing in calendar 1 

**Interim solution**
1. I am switching back to "make slots available 2 weeks ahead" option and save. All time slots in the calendars / public calendar URLs are showing fine. 
2. When switching to "show open slots xx weeks ahead" to a number bigger than 5, the error re-appears very consistently. 

So I cannot make appointments available for more than 5 weeks ahead of time without the errors appearing - which is very very unpractical for me. 

Can you please fix this Bug? 

I am using latest stable release of NC 19 and latest version of appointments.

Thanks and best
Thomas

**Comment by SergeyMosin** [comment]
This is very strange.

_RE: Open Slots from calendar 3 are showing in the public URL of calendar 1_
Just for the sake of debugging, if you were to book the "alien slot (from cal 3)" on cal 1 page, which calendar would the appointment end-up in 1 or 3 ?

_RE: Open slots that I have already deleted in calendar 1 are still showing in calendar 1_
Is it external calendar and/or do you delete them in NC or by some other external means. Could this be related to synchronization procedures?

Can you also take a look at the logs ``settings > administration > logging``

**Comment by SergeyMosin** [comment]
One more questions...
Do the ""alien time slots (from cal 3)" show up at random places, or just after/before some date?

**Comment by nolens** [comment]
Here are some more hints / Observations: 

- Yes, I am using external synching, Mac calendar app. I am copying / pasting available slots from day to day / week to week.

- In order to root out the possibility of sync errors, I deleted *all* open slots from the source calendar, then re-created some of them, 12 weeks ahead. 

After deleting all open slots in all source calendars and re-creating them carefully (not copying / pasting too many at a time), the problem is gone - for now.


If anything alike occurs, I will re-open this thread.

Many thanks for giving me the „sync problem“ hint, Sergey!, and sorry for bothering you with this.
