### ISSUE TITLE
24h / 48h delay

### ISSUE THREAD

**Issue by zebbez** [SergeyMosin/Appointments#163]
Hello Sergey,
Thanks for your useful application.
I'd like to add an appointment delay. 
Example : 
Between now and 24 hours or 48 hours => no possibility to make an appointment.
Thus, if the last appointment is ended at 13Hours, I'm sure to be free during the afternoon.

Regards

**Comment by SergeyMosin** [comment]
Some kind of "cool down" time-out after an appointment if I understand correctly ?

**Comment by Nadeige** [comment]
Hi Sergey,

I am interested in that functionality too. I would like people to make an appointment at least 24 (or 48) hours in advance. Otherwise people tend to book a slot that is in only 2 hours. To avoid that I have to spend time deleting non-booked slots everyday.

Thank you!

**Comment by Jaxom99** [comment]
I think it's what "lead time" is used for, maybe we should explain that in a clearer way? Otherwise this PR #242 would enhance the available settings.

**Comment by SergeyMosin** [comment]
Booked/pending appointment buffers are added in v1.12.2 (`Manage Appointment Slots` menu)

It is possible to block-off a period of time before and after a booked(and pending) appointment. This could be useful when some preparation/travel time is required before or cleanup/cool-off time needs to be blocked-off after an appointment.

Buffer blocking logic:
![appointment-buffers](https://user-images.githubusercontent.com/10747559/157701805-d7e9f1e6-47b9-40ca-afab-06bb02eb0fe6.jpg)
