### ISSUE TITLE
Cant't copy to sundy

### ISSUE THREAD

**Issue by joesch2** [SergeyMosin/Appointments#164]
I have installed the current version of the app. When entering the slots, I cannot copy the ones from Saturday to Sunday. Have I configured something wrong?
![copy](https://user-images.githubusercontent.com/18378305/102508307-861fef80-4085-11eb-8d05-eeeece31ed0d.PNG)

**Comment by SergeyMosin** [comment]
Duplicate #102 or try "external mode"
