### ISSUE TITLE
Control "Workday" Range

### ISSUE THREAD

**Issue by CodeMouse92** [SergeyMosin/Appointments#165]
I'm an early bird, and work a lot with folks in Europe, so I need to offer time slots at 6am and 7am, sometimes even 5am. The Appointments form only allows 8am as the earliest time, and automatically blocks out Sundays.

Can you allow users to freely edit the range of days and times shown?

**Comment by smugbit** [comment]
The possibility of appointments on Sunday would be very good.

**Comment by CodeMouse92** [comment]
I looked at docs, couldn't find. Link?
