### ISSUE TITLE
Modals cannot be read on very wide screens

### ISSUE THREAD

**Issue by laurentS** [SergeyMosin/Appointments#166]
I use a 4K screen (3840px wide) on which the modals/popup boxes are unreadable. See screenshot below (resized to make it usable here)
![image](https://user-images.githubusercontent.com/1745184/103575188-3cc70100-4ec9-11eb-9380-b16a8d089e4c.png)

I think it just needs some CSS fix, but I'm too bad at CSS to try it myself.

**Comment by SergeyMosin** [comment]
Thanks for the report. It will be fixed in the next release.

**Comment by SergeyMosin** [comment]
Fixed in 1.8.0
