### ISSUE TITLE
[BUG] Repeat / reoccurring appointments in source calendar don't block slots target calendar / external mode

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#168]
Hello @SergeyMosin 

I am using calendar in external mode (mac calendar app). 

- Reoccuring / ("repeat") appointments in my source calendar do not block slots in the target calendar. 
- Blocking slots in target calendar works flawlessly with ordinary "non-repeat appointments". 

Can you look into this and maybe fix this, please? 

Best regards
Thomas

**Comment by nolens** [comment]
PS: Just made my second **contribution** for Sergeys phantastic work via 
https://www.srgdev.com/gh-support/nextcloudapps 

I recommend everybody using the app **to do the same**!

**Comment by SergeyMosin** [comment]
@nolens Thanks.

The next version includes a bunch of new features (including the Weekly Template mode,  flexible appointment duration. etc...) and bug fixes. I was hopping to release it this weekend, but unfortunately the time just got away, and it will have to be the Jan 30/31.

**Comment by nolens** [comment]
@SergeyMosin 
With latest version 1.8, this issue still persists...

**Comment by nolens** [comment]
Fixed in Version 1.83
thanks @SergeyMosin
