### ISSUE TITLE
[feature] Add NC workflow to move finalized appointments between calendars

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#17]
Initial issue was:
When adding appointment slots manually, they are not showing on public page

**Steps to reprocude:**

1. Add time slot manually in existing calendar

1. Set time to floating, category to "Appointment", status to "Tentative", the appointment is not showing on public page.

**Comment by SergeyMosin** [comment]
It should still work, but at this point it is discouraged. I have updated the "Help/Tutorial" section. The "Schedule Generator" has been updated and it is possible now to add a single appointments to virtually any time slot, or you can just move appointments around in the calendar interface.
However  when there is progress on https://github.com/nextcloud/calendar/issues/812 I was thinking of adding "Convert to Appointment" option to this calendar menu:
![image](https://user-images.githubusercontent.com/10747559/76246255-b8a5dd80-6213-11ea-9021-20d369962472.png)

**Comment by nolens** [comment]
Sounds like a good idea.

**Comment by nolens** [comment]
Or better even: Provide the possibility to add a "nextcloud workflow" so that once an appointment is finalized, it will be moved or copied automatically from "Appointment slot calendar A" to "Calendar B" (can be defined freely via workflow).

How does that sound?

**Comment by nolens** [comment]
Similar option added in version 1.5

Great and thank you, @SergeyMosin !
