### ISSUE TITLE
[bug] Cancel event does not work

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#170]
The link in the mail to the participant to cancel an appointment does not work.

Nextcloud: 20.0.6.1
APP: 1.7.15

**Comment by SergeyMosin** [comment]
I can not reproduce. Is there anything in the logs? What mode are you using "Simple" or "External" ?

**Comment by RoundAboutWEB** [comment]
Do you mean the "time slot modus"? This will be "simple".
Witch logs you mean?

**Comment by SergeyMosin** [comment]
RE: Witch logs you mean?
``NC > Settings > Logging``

**Comment by SergeyMosin** [comment]
RE: The link in the mail to the participant to cancel an appointment does not work.
What happens when the link is clicked ?

**Comment by RoundAboutWEB** [comment]
There will be no link, so nothing happens when I click it.
Nothing in logs.
I also test it with "External" - the same problem.

**Comment by SergeyMosin** [comment]
Are BOTH Cancel Links missing or just ONE ?
![appt_cancel](https://user-images.githubusercontent.com/10747559/105874955-3230f080-5fcb-11eb-9b2b-798f3ea58998.jpg)

**Comment by RoundAboutWEB** [comment]
The left one I didn't see so the problem will be the right one.
You can test it here: https://nextcloud.roundaboutweb.info/index.php/apps/appointments/embed/AyBT0l7dmWduwQ%3D%3D/form

**Comment by SergeyMosin** [comment]
I think your embedding config missing ``https://`` in front of ``www.wolfa...``

**Comment by SergeyMosin** [comment]
I'll update the docs. It should be

----

php occ config:app:set appointments "emb_cncf_YourUserName" --value "**https**://your.domain.com/page_url?some_param_name="

----

**Comment by RoundAboutWEB** [comment]
Now I am completely confused.
Which "embedding config"?

**Comment by SergeyMosin** [comment]
It looks like the "**iFrame/Embedding**" is configured (or actually MIS-configured) for this form. As per **Chapter 10** of the tutorial https://htmlpreview.github.io/?https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php

**Comment by RoundAboutWEB** [comment]
I do not understand which parameter must be entered. When I enter "https://nextcloud.roundaboutweb.info/page_url?some_param_name=" the login of Nextcloud is called. Which link/parameter must be entered here?

**Comment by SergeyMosin** [comment]
Are you trying to embed the form into an ``<iframe>`` or are you using it as is ???

**Comment by RoundAboutWEB** [comment]
I embeded here: https://www.roundaboutweb.net/impressum/kontakt/
and as Popup by click "Termin vereinbaren" on Mainpage here: https://www.roundaboutweb.net/

**Comment by SergeyMosin** [comment]
Did you figure this out or you still need help with this ?

**Comment by SergeyMosin** [comment]
no response, closing, if you still need help with this contact me
