### ISSUE TITLE
[feature] act like a poll

### ISSUE THREAD

**Issue by stefanoco** [SergeyMosin/Appointments#171]
I'm considering the idea of using this (otherwise perfect) app instead of polls for the use case of:

"Converging on the best date/time for a meeting between parties"

Of course, the basic idea is that only one party (the proposer) has control over Appointmens, and his calendar(s) is taken into account. The other parties would receive a link for voting and eventually the proposer would check for the most voted date/time and confirm that one.

Would this be considered useful? Somehow related also to #25 #23 #54

**Comment by nolens** [comment]
I would consider this useful, but only of pre-selected dates out of an existing source calendar are up for voting..

**Comment by stefanoco** [comment]
Yes my requirements are coming exactly from noticing that today two different plugin are doing a great job independently, and superimposing or connecting them would yeld an even mode useful result.

- poll: provides a list of slots for an unlimited number of persons to vote, and the proposer then selects the most appropriate among them for a meeting (the most voted or whatever)
- appointments: provides a list of slots for one person at a time to select any of them for an appointment, with automated event creation on the proposer's calendar

I'm not sure if a link between the two solutions would work. Ideally, one should be able to create a new poll while working being in the *poll* app, based on one of the *appointments* app configurations, and the list of options should pop up populated accordingly. After voting etc., confirming the selected option should be equivalent to selecting one option out of the *polls* dates.
