### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by andrzej-r** [SergeyMosin/Appointments#173]
Error when trying to update the Appointments app:
 
    Updating <appointments> ...
    Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE UNIQUE INDEX user_index ON oc_appointments_pref (user_id)':
    
    SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "user_index" already exists
    Update failed

**Comment by SergeyMosin** [comment]
I think I know what the problem is. Are you using POSTGRESQL ?

**Comment by andrzej-r** [comment]
Yes, sorry, forgot to mention that. Nextcloud 20, fpm docker image.

**Comment by Neikius** [comment]
Same here. Had to disable the app and now can't enable it since the same happens upon enabling.

**Comment by SergeyMosin** [comment]
Have you tried v1.8.1 ?

**Comment by Neikius** [comment]
I think it's fine now. App was disabled and I was able to update via UI & it automatically enabled.

Quick action, nice!
