### ISSUE TITLE
I don't see the screens that your docs show

### ISSUE THREAD

**Issue by compumatter** [SergeyMosin/Appointments#174]
Using Nextcloud 20 and have your latest version from Github.  My home screen is very different from what you show on the docs.  There is no "Booking Page" or "Generate Schedule" 

At the top it says public "disabled"

I am confused.  Perhaps you have a clearer documentation or video available showing how to set this software up.  

Can you direct me on what I am missing here.

**Comment by SergeyMosin** [comment]
Duplicate #167
