### ISSUE TITLE
Can't update app

### ISSUE THREAD

**Issue by acsfer** [SergeyMosin/Appointments#175]
Exception: App with id appointments has invalid signature

**Comment by SergeyMosin** [comment]
Are you updating to v1.8.1 ?

**Comment by acsfer** [comment]
My NC says 1.8.0

**Comment by SergeyMosin** [comment]
I think 1.8.0 must be un-installed first and then you should be able to install 1.8.1 (which is the latest https://apps.nextcloud.com/apps/appointments)

**Comment by acsfer** [comment]
Well, on my NC, it says 1.8.0, even after uninstall and trying to install it again...

![image](https://user-images.githubusercontent.com/12234510/106646440-0d6de780-658e-11eb-944f-330e373ec103.png)

**Comment by acsfer** [comment]
Same from CLI:

```
$ php occ app:enable appointments
App with id appointments has invalid signature
```

**Comment by SergeyMosin** [comment]
Yes, there is a problem with 1.8.0 signature but 1.8.1 was supposed to fix it.

**Comment by SergeyMosin** [comment]
There is nothing I can really do from my side. v 1.8.2 is being released tomorrow. I don't understand why your NC is not seeing that v1.8.1 is available in the store. You could try manual install.
