### ISSUE TITLE
Show end time

### ISSUE THREAD

**Issue by axelos** [SergeyMosin/Appointments#176]
Hello,

"Appointments" does not display slot end times.

It shows the start time in one column by default, in two columns if the "Show time in two columns" option is enabled, but not the end time if the "Show end time" option is enabled. Instead it shows a single column without an end time.

This has happened recently, probably as a result of an update of the module, we have noticed it in use.

Thanks !

Appointments : 1.8.2
Nextcloud : 18.0.14
Php : 7.2.31
Mysql : 5.6.50

**Comment by SergeyMosin** [comment]
Which mode are you using `Simple`, `Weekly Template` or `External` ?

**Comment by axelos** [comment]
We used the simple mode.

**Comment by SergeyMosin** [comment]
I can not reproduce this.
Can you send me(sergey [at] srgdev.com) the text from the settings dump `Settings > Advanced Settings > Debugging > Settings Dump`

**Comment by SergeyMosin** [comment]
This should be fixed in v1.9.2

**Comment by axelos** [comment]
Thanks Sergey Mosin,

I update Nextcloud for version 21 in september...

Axel.

**Comment by axelos** [comment]
Hello,

In August, I migrated the instance in use to a more capable server, and then updated Nextcloud (18 → 21).
The Appointments 1.10.1 version fixes the problem well :)

Thanks!
