### ISSUE TITLE
After update to Talk 10.1.2

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#179]
After updating to Talk 10.1.2   users can not confirm bookings when integrated with talk.

Dont know if the bug should be added here or talk.

Nextcloud 20.0.7.1 with talk 10.1.2 and Appointments 1.8.3

I did mask some stuff from the log 

{"reqId":"VJ50axKN7xbzZAezJCNi","level":3,"time":"2021-02-22T14:37:48+00:00","remoteAddr":"**************************","user":"--","app":"index","method":"GET","url":"*******************************************","message":{"Exception":"Exception","Message":"Call to undefined method OCA\\Talk\\Room::addUsers()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Appointments\\Controller\\PageController"},"cncf"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Appointments\\Controller\\PageController","cncf",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"token":"Nxhpx1ZGJjlkaA2","_route":"appointments.page.cncf"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["***********************************************"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"Error","Message":"Call to undefined method OCA\\Talk\\Room::addUsers()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/appointments/lib/Backend/BackendUtils.php","line":401,"function":"createRoomForEvent","class":"OCA\\Appointments\\Backend\\TalkIntegration","type":"->","args":["James Pink",{"delimiter":",","name":"DTSTART","group":null,"parameters":{"TZID":{"name":"TZID","noName":false,"parent":null,"__class__":"Sabre\\VObject\\Parameter"}},"parent":{"name":"VEVENT","parent":{"name":"VCALENDAR","parent":null,"__class__":"Sabre\\VObject\\Component\\VCalendar"},"__class__":"Sabre\\VObject\\Component\\VEvent"},"__class__":"Sabre\\VObject\\Property\\ICalendar\\DateTime"},"jobe"]},{"file":"/var/www/nextcloud/apps/appointments/lib/Backend/BackendUtils.php","line":375,"function":"addEvtTalkInfo","class":"OCA\\Appointments\\Backend\\BackendUtils","type":"->","args":["jobe",["jobe","","p1","0","_","_"],{"name":"VEVENT","parent":{"name":"VCALENDAR","parent":null,"__class__":"Sabre\\VObject\\Component\\VCalendar"},"__class__":"Sabre\\VObject\\Component\\VEvent"},{"delimiter":null,"name":"ATTENDEE","group":null,"parameters":{"SCHEDULE-AGENT":{"name":"SCHEDULE-AGENT","noName":false,"parent":null,"__class__":"Sabre\\VObject\\Parameter"},"CN":{"name":"CN","noName":false,"parent":null,"__class__":"Sabre\\VObject\\Parameter"},"PARTSTAT":{"name":"PARTSTAT","noName":false,"parent":null,"__class__":"Sabre\\VObject\\Parameter"}},"parent":{"name":"VEVENT","parent":{"name":"VCALENDAR","parent":null,"__class__":"Sabre\\VObject\\Component\\VCalendar"},"__class__":"Sabre\\VObject\\Component\\VEvent"},"__class__":"Sabre\\VObject\\Property\\ICalendar\\CalAddress"}]},{"file":"/var/www/nextcloud/apps/appointments/lib/Backend/BCSabreImpl.php","line":1183,"function":"dataConfirmAttendee","class":"OCA\\Appointments\\Backend\\BackendUtils","type":"->","args":**************,{"file":"/var/www/nextcloud/apps/appointments/lib/Backend/BCSabreImpl.php","line":1152,"function":"confirmCancel","class":"OCA\\Appointments\\Backend\\BCSabreImpl","type":"->","args":["jobe","20","**********************************************",true]},{"file":"/var/www/nextcloud/apps/appointments/lib/Controller/PageController.php","line":257,"function":"confirmAttendee","class":"OCA\\Appointments\\Backend\\BCSabreImpl","type":"->","args":["jobe","20","**************************************************"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"cncf","class":"OCA\\Appointments\\Controller\\PageController","type":"->","args":[false]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Appointments\\Controller\\PageController"},"cncf"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Appointments\\Controller\\PageController"},"cncf"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Appointments\\Controller\\PageController","cncf",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"token":"*******************","_route":"appointments.page.cncf"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["***************************************************,{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/appointments/lib/Backend/TalkIntegration.php","Line":69},"CustomMessage":"--"},"userAgent":"**************************************************************************************

**Comment by small1** [comment]
So going from 10.0.5 to 10.1.2 has some changes within.

This line  was removed 
- $room->addUsers(['userId' => $userId]);   			

This was added:
+$this->participantService->addUsers($room, [[
+					'actorType' => Attendee::ACTOR_USERS,
+					'actorId' => $userId,
+				]]);

No clue more than that yet

**Comment by SergeyMosin** [comment]
I'll take a look at it later today, thanks for reporting

**Comment by small1** [comment]
Ok so this is valid for talk 10.1.*. Might be for talk 11 in Nextcloud 21 
as well

/Johan

**Comment by nickvergessen** [comment]
Please don't use PHP internal API of Talk in your app.
It's far from being settled and will change in the dev cycle of Nextcloud 22 again.

**Comment by SergeyMosin** [comment]
@nickvergessen But there is no other way to create talk rooms from the backend. Is there? Do you think a sub-request to https://nextcloud-talk.readthedocs.io/en/latest/ endpoints would be better? Wouldn't it lock on single core installations ?

**Comment by nickvergessen** [comment]
Well as said, we don't have a public PHP API yet. I heavily recommend to stick to the Rest API until the php one is settled and has a documented public api. Otherwise it will break almost every release or could have side effects

**Comment by nickvergessen** [comment]
Let me sent you an invite to our talk development chat so we can clarify what you need, so we can look into that first.

Is https://github.com/SergeyMosin/Appointments/blob/master/appinfo/info.xml#L10 the correct email?

**Comment by SergeyMosin** [comment]
@nickvergessen Yes, email is correct, thank you.

**Comment by SergeyMosin** [comment]
Fixed in v1.8.4
