### ISSUE TITLE
When adding new slots to a calender show busy slots from the other calendars as well

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#180]
Right now when you add new slots you only see whats busy from the main calendar. It would be nice to be able to see whats busy from the other calendars the user has as well.

I have three different ones that i add times to depending on what they are about. So when adding new slots i have to check in the calendar app before i mark out the new slots.

**Comment by RileySeaburg** [comment]
Upvote this 1000 percent. 

If this app is meant for a business owner to replace calendly, one must be able to not double book appointments.

They only way this is possible is to add the ability to reference multiple calendar for a scheduling conflict.
