### ISSUE TITLE
[Bug] Appointments become available, while timeslot is already booked.

### ISSUE THREAD

**Issue by DmitryPetukhov88** [SergeyMosin/Appointments#183]
I think i am having a bug here...

**My settings:**
Appointment can be booked at least 30 minutes prior to the available timeslot.
Slots are scheduled in weekly mode with 45 or 105 minutes duration f.e. as such:
![image](https://user-images.githubusercontent.com/79863556/109531745-92c6b800-7ab8-11eb-9bfc-556e4c017477.png)

**Expectation:**
Someone books 10:00 appointment with 105 Minutes duration -> both slots starting 10am and 11am become unavailable.

**Reality:**
Both appointments become unavailable at first. BUT: Once its past 10am and not yet 10:30am the 11am appointment becomes available again. Which might end up in double booking on very short notice.

Would gladly invest in a solution. Thanks for the great work and app!

nextcloud v20.0.5 @ docker
Appointments v1.8.4

**Comment by SergeyMosin** [comment]
This is fixed inv1.8.5 and daylight savings as-well

**Comment by DmitryPetukhov88** [comment]
Awesome work, thank you!
