### ISSUE TITLE
Just upgraded and now public preview doesn't render -- just spins

### ISSUE THREAD

**Issue by LittleDuke** [SergeyMosin/Appointments#184]
No one is able to get our Appointments on screen it just spins

![Screen Shot 2021-03-01 at 17 18 31](https://user-images.githubusercontent.com/1402517/109572061-3365a980-7ab2-11eb-8677-a0607869eb5f.png)

**Comment by LittleDuke** [comment]
If I stop sharing it shows up in grey but if i re-enable it just starts spinning again

**Comment by SergeyMosin** [comment]
What version ?

**Comment by LittleDuke** [comment]
1.8.5

**Comment by SergeyMosin** [comment]
And NC version ?

**Comment by LittleDuke** [comment]
19.0.4

**Comment by LittleDuke** [comment]
I just checked the system panel and it is complaining about missing imagick -- though the php module is definitely there

**Comment by SergeyMosin** [comment]
One more question do you have `talk integration` enabled and if so, what is your `talk` version ?

**Comment by LittleDuke** [comment]
no we don't use talk and it's not enabled in your settings

**Comment by LittleDuke** [comment]
Just updated everything on OS and php7.4 no errors and updated NC to 19.0.9 -- no change it just spins when we try to publish -- renders when disabled
![Screen Shot 2021-03-01 at 21 37 31](https://user-images.githubusercontent.com/1402517/109593350-6326a880-7ad6-11eb-83e0-cae9c1a1f1cd.png)

**Comment by SergeyMosin** [comment]
Are there any errors in the browser console (F12) ?

**Comment by LittleDuke** [comment]
Nothing.

**Comment by SergeyMosin** [comment]
I am trying to reproduce this, but no luck so far, what `mode` are you using ?

**Comment by LittleDuke** [comment]
External, calendar is managed by NC

**Comment by SergeyMosin** [comment]
OK, it is a bug, will have fix soon.

**Comment by SergeyMosin** [comment]
v1.8.6 is in the store, it should propagate to the updater in an hour or so.

**Comment by nolens** [comment]
For me, the problem seems to be solved for now.

**Comment by LittleDuke** [comment]
Now at least it's show an internal error

Here is what is in the access.log

`x.x.x.x - - [02/Mar/2021:07:17:33 -0600] "GET /apps/appointments/form?p=p0&v=1614691052970 HTTP/1.1" 500 5802 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"`

And what is in the nextcloud.log

`{"reqId":"vHVuz8AbEMoN3Ln4V6kC","level":3,"time":"2021-03-02T13:22:48+00:00","remoteAddr":"63.232.64.253","user":"david.duccini","app":"index","method":"GET","url":"/apps/appointments/form?p=p0&v=1614691366969","message":{"Exception":"Sabre\\VObject\\Recur\\MaxInstancesExceededException","Message":"Recurring events are only allowed to generate 3500","Code":0,"Trace":[{"file":"/www/nextcloud/apps/appointments/lib/Backend/BCSabreImpl.php","line":378,"function":"valid","class":"Sabre\\VObject\\Recur\\EventIterator","type":"->"},{"file":"/www/nextcloud/apps/appointments/lib/Backend/BCSabreImpl.php","line":673,"function":"queryRangeTR","class":"OCA\\Appointments\\Backend\\BCSabreImpl","type":"->"},{"file":"/www/nextcloud/apps/appointments/lib/Controller/PageController.php","line":873,"function":"queryRange","class":"OCA\\Appointments\\Backend\\BCSabreImpl","type":"->"},{"file":"/www/nextcloud/apps/appointments/lib/Controller/PageController.php","line":447,"function":"showForm","class":"OCA\\Appointments\\Controller\\PageController","type":"->"},{"file":"/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"formBase","class":"OCA\\Appointments\\Controller\\PageController","type":"->"},{"file":"/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/www/nextcloud/lib/base.php","line":1010,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/EventIterator.php","Line":299,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36","version":"19.0.9.1"}`


<img width="874" alt="Screen Shot 2021-03-02 at 07 13 39" src="https://user-images.githubusercontent.com/1402517/109654500-dd334d80-7b27-11eb-8bf6-cde873c7698f.png">

**Comment by SergeyMosin** [comment]
v1.8.7 is in the store with fix, NC updater should see it in 1/2 hour or so.

**Comment by LittleDuke** [comment]
Thanks @SergeyMosin  -- was able to manually install it and can confirm we're back online!   Tipping now...

Thanks -- let's leave it open for a day to make sure its solid ?

<img width="804" alt="Screen Shot 2021-03-02 at 09 14 30" src="https://user-images.githubusercontent.com/1402517/109669464-baa93080-7b37-11eb-826d-28bfc63c1c8b.png">
