### ISSUE TITLE
[feature] Add option to add phone number to .ics file

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#19]
Make an option available to add the phone number from the "settings" page to the .ics file that is sent in the confirmation email. Otherwise, the attendee does not know where to call if the appointment is for a phone call.

**Comment by SergeyMosin** [comment]
There is no standard defined way to add phone numbers, but it could go into the "description" area, together with the organization name, I guess.

**Comment by nolens** [comment]
Yes, that's what I imagined would be useful. 

Something like: 

"Appointment between
[applicants name from form entry field] 
[applicants phone no from form entry field] _remark: (both of these are already sent, if I remember this correctly - and then below:)_

[calendar owner name from the setup field] 
[calendar owner phone no from setup field]"

**Comment by SergeyMosin** [comment]
Solved in v1.1.4
