### ISSUE TITLE
Bug: Timezone data is empty

### ISSUE THREAD

**Issue by digitalrevisor** [SergeyMosin/Appointments#194]
Error:
"Cant load timezones"
when click submit button.
Specially for new users.
This means that appointment cant be used at all.

Somebody who knows solution?
https://demo.digitalrevisor.eu/index.php/s/oQyz7qeoryjL7aE

**Comment by SergeyMosin** [comment]
Are there any errors in the browser console (F12 to check) ?

**Comment by SergeyMosin** [comment]
What version of NC are you using ?

**Comment by SergeyMosin** [comment]
Can not replicate, no response, closing...
