### ISSUE TITLE
Timezone mix

### ISSUE THREAD

**Issue by Stef8955** [SergeyMosin/Appointments#195]
I really like the Appointments App, but I have an issue with it.

My timezone is Europe/Berlin = MESZ (UTC+2)

I created a week based hourly Appointment Slot.
The automatic detected time zone within the Appointments App is: Europe/Berlin

When someone book an appointment it shows for example available --> 8:00 MESZ , so book it.
Within the confirmation e-mail its written 10:00 MESZ  !

After confimation, the calender app shows it at 10:00 o´clock
Within the details from calendar app as 8:00 UTC
 

My enviroment:
Nextcloud 20.0.8
Nextcloud user zone: Germany
Ubuntu 20.04.02 LTS (0 updates to patch)
Linux timezone Europe/Berlin
PHP 7.4

BR

Stefan

**Comment by SergeyMosin** [comment]
Confirmed (weekly template mode). When calendar timezone does not match default(automatic) timezone - time shift occurs.
TODO: figure out which timezone should take precedence and when.
Temporary solution: use automatic timezone or a different mode.

@Stef8955 Thanks for reporting

**Comment by SergeyMosin** [comment]
Fixed in v1.9.0

**Comment by Stef8955** [comment]
Just updated and testet.
It´s perfect now :-)
