### ISSUE TITLE
Where is SUNDAY?

### ISSUE THREAD

**Issue by Dr-Sommer** [SergeyMosin/Appointments#196]
Hi, we would like to use Appointments in a Hospital. 
As we work 24/7, we also need SUNDAYS for Termination. How can I activate Sundays in your Software?
Thank You in advance... 
(using NC Version 20.0.8)

**Comment by forestmountain** [comment]
+1

**Comment by LindenerGenie** [comment]
+1

**Comment by Bartiiee** [comment]
Also looking for sunday.
I'm setting up a Nextcloud instance to use with a bunch of volonteers this summer of our vacation goes trough. I would like them to be able to make an appointment with certain people but we also need sunday.
I would be verry willing to donate if sunday works as an option (if not I cannot use the module ofc).

**Comment by TheGreyDiamond** [comment]
Yeah, I'm also looking for sundays? Where are they?

**Comment by Dr-Sommer** [comment]
Would be nice, if somebody could explain, why Sundays are not given, Thanks...

**Comment by UkeFan** [comment]
Sunday comes if one spends 10€ or more - the instructions are to be found in his help at the very buttom. "Contribution key".
I realized it by chance. There is quite some more documentation needed.

**Comment by Bartiiee** [comment]
It states nowhere that you get sunday if you fund. Can you please comform it is there?
I don't mind giving some money, but only if I get the features needed when I do so.

**Comment by SergeyMosin** [comment]
There is no Sunday support even with a key. There are two workarounds:
1. In simple mode: Create an appointment and then move it to Sunday using calendar app
2. Use external mode: You can create anything you want, including Sundays, Recurrence, etc..

P.S. Sunday support is planned but it is not high priority at the moment.

**Comment by MaxHillebrand** [comment]
bump for feature request for Sunday bookings.

> 1. In simple mode: Create an appointment and then move it to Sunday using calendar app

This is not a useful workaround, as the booking-user won't know that sunday spots are available.

**Comment by smoebody** [comment]
> > 1. In simple mode: Create an appointment and then move it to Sunday using calendar app
> 
> This is not a useful workaround, as the booking-user won't know that sunday spots are available.
What he means is to add timeslots via external calendar in calendar-app and use this calendar as Source Calendar. (But - as mentioned - this works only in Simple- and External Mode)

**Comment by remylenerd** [comment]
> etc..
You would think this would've been deployed with the app from the beginning, seeing as how it's a day of the week that everyone uses, and it's a calendar scheduling app. I'm using external calendars to set my availability and it's not working. I just contributed $10. I do hope this gets addressed. I'm happy to continue contributing but this a tool I'm using for business, business=income, and income means I have money to continue saying thanks for an excellent app that makes my work easier. 🙏🏼😁

**Comment by SergeyMosin** [comment]
@remylenerd an email with a key just bounced back. Does your email look like `enta*l_ca*h*ps0m@...` ? If so please send me your email address to sergey [at] srgdev.com so I can send your contributor key.

**Comment by remylenerd** [comment]
Yes it is that email

**Comment by SergeyMosin** [comment]
Sunday is available in v1.12.0 Additional discussion is tracked in #250 , closing
