### ISSUE TITLE
Add the option Admin confirmation

### ISSUE THREAD

**Issue by portalx** [SergeyMosin/Appointments#20]
Hello,
Also add the option to admin/group for final confirmation on an appointment !?

Thanks

**Comment by SergeyMosin** [comment]
No sure I follow. Do you want to make the final confirmation optional ?

**Comment by portalx** [comment]
Hello Sargey,

Yes it will be a good idea to give us this option with the possibility when the status changed, automatically inform the client by email with the new status update of the appo (PS. confirmed, scheduled, cancelled etc..)

Thank you

**Comment by SergeyMosin** [comment]
Sound reasonable, I am thinking that this should triggered on:
1. Time/Date change
2. Status change (confirmed/cancelled)
3. Location change

Am I missing something else ?

**Comment by portalx** [comment]
Hello Sergey,

Yes! sounds good !! It's what we need.

Thank you

**Comment by SergeyMosin** [comment]
Available in version 1.4.0 ``Email Settings > Email Attendee when the appointment is: ...``
