### ISSUE TITLE
Show local timezone indicator

### ISSUE THREAD

**Issue by MaxHillebrand** [SergeyMosin/Appointments#201]
The appointments app shows the time in the local timezone of the user. 
However, it is not obvious what time zone is in fact displayed. 

I have received many times now from independent users the question of `What timezone is this?`.

This confusion would be cleared up if the app would show explicitly what time zone is displayed. 

Notice this would also improve the case where the user accesses the app through tor browser, which has by default UTC, which can be confusing as well.

**Comment by SergeyMosin** [comment]
v1.9.0...
![image](https://user-images.githubusercontent.com/10747559/115177874-1b67da80-a09e-11eb-876c-4f3835b6b1db.png)

**Comment by MaxHillebrand** [comment]
Amazing, thank you so much for shipping a fix!! :black_heart: :rocket:

**Comment by MaxHillebrand** [comment]
Deployed v1.9.0, it works, thank you!
![screenshot_20210419_094723](https://user-images.githubusercontent.com/30683012/115200213-41b86500-a0f4-11eb-85f7-35a7d8347209.png)
