### ISSUE TITLE
display of the reservation slot is bugged

### ISSUE THREAD

**Issue by user67x** [SergeyMosin/Appointments#203]
Hi.

With the last update of Appointment, the display of the reservation slot is bugged and confusing. Here are two screenshots that say more.

Regards
![2021-04-20_11-21-49](https://user-images.githubusercontent.com/13274746/115372491-3edc7380-a1cb-11eb-8137-c64f0218ab42.png)
![2021-04-20_11-22-17](https://user-images.githubusercontent.com/13274746/115372493-400da080-a1cb-11eb-9f4f-c41b322b0303.png)

**Comment by user67x** [comment]
I workaround is to inject this css rule:
```
.srgdev-ncfp-chb-cont {
    position: inherit;
}
```
Inherit instead of relative…

**Comment by SergeyMosin** [comment]
Fixed in 1.9.1, I have just uploaded to the app store so it should be available in the updater in about 30 min.
Thanks for reporting
