### ISSUE TITLE
Making an appointment is possible when the agenda is not available

### ISSUE THREAD

**Issue by user67x** [SergeyMosin/Appointments#205]
Hello,

With the last version of appointment : I have found that it is possible to make an appointment even though a time slot is already taken, and not free in one of the agendas. In my example, we could make an appointment at 3:30 pm when I am already busy between 3 and 4 pm. In short, there is a bug.

Regards

![2021-04-24_16-48-13](https://user-images.githubusercontent.com/13274746/115963007-2f885d80-a51e-11eb-9269-265240deb1f7.png)
![2021-04-24_16-49-56](https://user-images.githubusercontent.com/13274746/115963008-3020f400-a51e-11eb-88ef-3342b11e964b.png)
![2021-04-24_16-49-03](https://user-images.githubusercontent.com/13274746/115963009-3020f400-a51e-11eb-831b-6925efd682d3.png)

**Comment by user67x** [comment]
This is a weekly occurrence. I have test with a oneshot slot and appointment works in this case.

**Comment by SergeyMosin** [comment]
Is the event in the first screenshot marked as `Appointment` ?

![appointments_block](https://user-images.githubusercontent.com/10747559/116168691-078d2b80-a6d1-11eb-9bb1-0879cabed4bf.jpg)

**Comment by user67x** [comment]
Yes Sergey, it an appointment with the right category. I have try to reproduice the issu, but it works with a event that repeat all weeks. The event named 'kiné' had enter on Korganizer (in KDE neon). I will delete it and recreate it again with Thunderbird, and I say you more details.

**Comment by user67x** [comment]
Ok, there is a problem too if I try to block some hours in a agenda in Thunderbird (PC).

**Comment by SergeyMosin** [comment]
If this is still happening please send me you Settings Dump:
`Settings > Advanced Settings > Debugging > Settings Dump`
and email text to sergey [at] srgdev.com

**Comment by user67x** [comment]
Hi Sergey!

I just add a rendez-vous in Thunderbird, and now the appointment doesn't display these hours as available. 
I also created a recurring appointment, but we'll have to wait until next week to see if the calendar is actually taken by that date. I can't find the possibility to book an appointment more than a week away.

**Comment by SergeyMosin** [comment]
Please #137 for more weeks.

**Comment by user67x** [comment]
Perfect Sergey. The problem has been fixed with one of the updates, everything seems to work fine now.

I close the issue.
