### ISSUE TITLE
[Feature] include custom text in .ics file (like a meeting link)

### ISSUE THREAD

**Issue by okworx** [SergeyMosin/Appointments#207]
It would be nice to be able to have a custom text to be included in the description of the .ics file that is sent with the appointment confirmation. That could for example be a meeting link for a personal room with some other web meeting service (than NextCloud's Talk), instructions to connect etc. 

It should be possible that this text contains line breaks. 

Currently, it seems to only be possible to include such information in the confirmation email itself, but it would be super practical if the person who booked the appointment had it in their calendar app via the .ics file.

**Comment by UkeFan** [comment]
Why can't the appointment app just "foreward" the existing calendar event as it is as ics-file to the booking people? Then we could write all the slot-specific information into that event and the person that book had specific links, attachments, description texts, place etc.
Again @SergeyMosin : Could you tell whether this is something you see within your app or wheter thi should become another app.
Thank you very much!

**Comment by SergeyMosin** [comment]
@UkeFan There is already an option to add more email text to confirmation emails, I guest it is not that hard to also add to the .ics file. I look into it for the next release.

**Comment by SergeyMosin** [comment]
Available since v1.11.12 `Settings > Email Settings > Additional ICS file description`

![image](https://user-images.githubusercontent.com/10747559/155025880-930756f9-fbe5-42a7-a7a3-1a7f2257bb46.png)
