### ISSUE TITLE
Group Appointments

### ISSUE THREAD

**Issue by MaxHillebrand** [SergeyMosin/Appointments#208]
The appointments app is super useful for booking an event for a single person's calendar. However, it would be even more powerful if it were possible to do so for a group of users!

1. Multiple users setup the appointments app with their available / blocked time.
2. User selects which users are included in a desired appointment.
3. Show only those times that are available for ALL selected users.
4. When one slot is selected, ALL participants get the calendar invite / talk room invitation.

**Comment by MaxHillebrand** [comment]
This is a high priority feature request for me, I would use it the day it is shipped. 

I'm happy to offer a 0.01 bitcoin bounty, split up to those persons who are involved in getting this feature implemented, reviewed and shipped.

**Comment by UkeFan** [comment]
We also need urgently need something like this. If we could receive an proper invoice we could contribute thoughout usual money..

**Comment by SergeyMosin** [comment]
This is an interesting idea, but there is no easy way to make it work with current code, maybe in the future it could be possible using shared calendar. However, this could also be it's own app, called "Meeting Time" or something :) ,  there is freelancers forum https://help.nextcloud.com/c/nextcloud-freelancing you could try your luck there.

**Comment by MaxHillebrand** [comment]
Thank you @SergeyMosin for the referral, I will propose a feature request to this forum.

If this feature is out of scope for this application, feel free to close the issue.
