### ISSUE TITLE
[BUG] "An Error occurred - please try again with a different date" in booking process

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#209]
Hello Sergej,

customers report frequently that some slots cannot be booked. "An Error occurred - please try again with a different date" is the message, right after hitting the "booking" button. ![Check this screenshot, please](https://user-images.githubusercontent.com/21305551/117348099-19798600-aeaa-11eb-9b48-46e0218836dc.png)

I am using this setup: 
- external mode
- validation step
- using 4 different calendars to provide different lengths of slots

I have tried the following steps with no avail:
- delete the booking, re-try again at the same time
- delete the empty slot, create a new on one from scratch at the same date and time - no avail, either.

So it looks to me like the database does not recognize the time slot to be "free", even if I create a new open time slot from scratch.

This is happening with some time slots at random, but fairly regularly, so these error reports from my customers come in frequently. 

How can I help you to further identify the underlying issue? 

Best
Tom

**Comment by SergeyMosin** [comment]
> using 4 different calendars to provide different lengths of slots

How is this this set-up ???

Can you also email me the  `Settings Dumb` . `Settings > Additional Settings > Debugging > Settings Dump`

**Comment by nolens** [comment]
> > using 4 different calendars to provide different lengths of slots
> How is this this set-up ???

1. I have setup 4 different calendars in nextcloud (4 different source calendars)
2. defining different lengths of appointments to each of the 4 calendars (½h, 1h, 3h, 8h)
3. all 4 source calendars are showing in apple calendar app. From here, I define and provide the free slots to nextcloud calendar with "external mode"
4. the 4 different time slots (calendars) are overlapping (3h slot may contain 6 x ½ hour slots. Example: If ½ hour slot is booked, target calendar is filled with ½ hour appointmeht and this would then block the whole 3h slot - similar scenario with 1h and 8h slots)
5. One singe target calendar is filled with the appointments 

> Can you also email me the `Settings Dumb` . `Settings > Additional Settings > Debugging > Settings Dump`

Can you provide an obfuscated link where to find this? 
I have a German translation and the path is less than obvious.

Thanks!

**Comment by SergeyMosin** [comment]
I can not reproduce this but In v1.9.2 i have added additional logging which might help in tracking this down. If/when this happens again please check NC logs in Nexcloud `Settings > Logging` and look for warnings starting with any of the following:
- Timeslot is blocked ...
- Lock uid already exists ...
- BusySpot/error detected ...

Thanks

**Comment by LittleDuke** [comment]
Getting a ton of errors trying to update from 1.8.7 to 1.8.10

<img width="911" alt="Screen Shot 2021-06-14 at 07 29 10" src="https://user-images.githubusercontent.com/1402517/121892374-478c8a00-cce2-11eb-89c5-00ffc744f296.png">

**Comment by LittleDuke** [comment]
19.0.12

That is not intentional -- certainly nothing we configured or changed

**Comment by SergeyMosin** [comment]
can you check the output of
```
ls /www/nextcloud/apps/appointments
```
but maybe `appointments` reinstall would be a better option

**Comment by LittleDuke** [comment]
```
# ls /www/nextcloud/apps/appointments
ajax          composer.json  img   Makefile                 phpunit.xml  src               translationtool.phar
appinfo       composer.lock  js    package.json             README.md    templates         webpack.common.js
build         COPYING        l10n  package-lock.json        screenshots  tests             webpack.dev.js
CHANGELOG.md  css            lib   phpunit.integration.xml  scss         translationfiles  webpack.prod.js

```

**Comment by nolens** [comment]
> I can not reproduce this but In v1.9.2 i have added additional logging which might help in tracking this down. If/when this happens again please check NC logs in Nexcloud `Settings > Logging` and look for warnings starting with any of the following:
> 
> * Timeslot is blocked ...
> * Lock uid already exists ...
> * BusySpot/error detected ...

@SergeyMosin 
Yes, the error has occured again.

Here are the errors from the log: 

[appointments] Warning: BusySpot/error detected in setAttendee func, mode: 1, trc_code: 1

POST /index.php/apps/appointments/pub/P5ISxEvW1G4dFIW16A%3D%3D/form
from 2a00:20:100c:f9b2:8d24:a1c9:2fd1:7cd9 by xxxxxxxxx at 2021-06-18T12:55:24+00:00

[appointments] Warning: Timeslot is blocked, calId: 4, blocker_start: 1624626000, blocker_end: 1624629600, timeslot_start: 1624629600, timeslot_end: 1624631400

POST /index.php/apps/appointments/pub/P5ISxEvW1G4dFIW16A%3D%3D/form
from 2a00:20:100c:f9b2:8d24:a1c9:2fd1:7cd9 by xxxxxxx  at 2021-06-18T12:55:24+00:00

Best
Tom

**Comment by SergeyMosin** [comment]
@nolens Thanks I see now what's causing this:
```
   blocker_end: 1624629600
timeslot_start: 1624629600
```
There start/end intersections comparison problem I'll fix it asap probably tomorrow morning

**Comment by nolens** [comment]
@SergeyMosin 
This would be awesome, thanks - because many customers have problems booking appointments here right now... 

Best
Tom

**Comment by SergeyMosin** [comment]
This issue is fixed in v1.9.3

@LittleDuke Do you still use NC19 ? if so can try to back port the fix to Appointments version 1.8.7

**Comment by nolens** [comment]
Great and thanks, Sergey!

**Comment by LittleDuke** [comment]
Yes we do currently upgrade planned for this summer will try patch and report back
