### ISSUE TITLE
Multiple calendars with different categories possible?

### ISSUE THREAD

**Issue by Cermit** [SergeyMosin/Appointments#21]
Is it possible to use several calendars for appointments and then select them with a drop down menu in the public form.

In this context, the calendars could be assigned to different categories, so that first the category and then the calendar is selected in the form.

My use case would be for example the booking of rooms and portable devices in a school.

**Comment by SergeyMosin** [comment]
Maybe in the future releases.

**Comment by SergeyMosin** [comment]
Multi-page support is available as of version 1.7.x 

![appt-multipage-4](https://user-images.githubusercontent.com/10747559/93891721-b68c0380-fcb9-11ea-811e-019114eb28ae.jpg)

**Comment by nolens** [comment]
@Cermit 
Please close this issue. The feature has been implemented.
