### ISSUE TITLE
How to adapt mail texts?

### ISSUE THREAD

**Issue by nephilim75** [SergeyMosin/Appointments#211]
Hello

how can I adapt the mail texts which were sent to user during the booking process? The mails doesn't sound "good" to native speakers. If this is not possible for my own, I am interested in assisting you with this.

Kind regards
//neph

**Comment by UkeFan** [comment]
In settings/E-Mail-Settings there is per form one field for EXTRA text. But I guess you mean the translation of the above standard texts. Yeah, I would also be interested in knowing how to alter that!

**Comment by SergeyMosin** [comment]
RE: The mails doesn't sound "good" to native speakers.
English or an other language ? Feel free to contribute translations here: https://www.transifex.com/nextcloud/public/ and I'll include them into the next release. Plus all nextcloud/transifex contributors can get a free key.

**Comment by nephilim75** [comment]
There are 6 projects under this link. Which one includes the mail messages?

**Comment by nephilim75** [comment]
Added my suggestions in transfex. Thank you.
