### ISSUE TITLE
Let several people book one slot

### ISSUE THREAD

**Issue by UkeFan** [SergeyMosin/Appointments#213]
Currently a slot can only be booked by ONE person. After it is booked, it disappears from the list. We are a NGO that brings people in movement. We wan't to let 15-30 people book bicycle tours throughout this summer. Due to Covid sometimes it's 15 sometimes 30 people who are allowed to ride together.
So it would be perfect if we could set a maximum of bookers per date. 
Is that something @SergeyMosin that you could eventually make possible or is it again another app and we should ask the freelance world to realice it?!
In our case it would also be nice if we could have one page per day - using the same two source and destination calendars.

**Comment by SergeyMosin** [comment]
This is different from #208 and is duplicate #54 , I is technically possible for but it is not high priority at the moment.
I'll close this, discussion can continue in #54

**Comment by UkeFan** [comment]
ah sorry, I hadn't seen #54!
