### ISSUE TITLE
Error during scheduling

### ISSUE THREAD

**Issue by LittleDuke** [SergeyMosin/Appointments#217]
Something broke -- this was working fine this morning and we have made zero changes

<img width="811" alt="Screen Shot 2021-06-11 at 20 46 27" src="https://user-images.githubusercontent.com/1402517/121761624-8958dd00-caf6-11eb-824e-45764635c4c2.png">

**Comment by SergeyMosin** [comment]
This is double booking protection, but if you think it is an error and you are using `external` mode please read this: https://github.com/SergeyMosin/Appointments/issues/209#issuecomment-860096742

If you are NOT using `external` mode please send me your Settings Dump and I'll try to reproduce it...
`Settings > Advanced Settings > Debugging > Settings Dump`
and email the text to sergey [at] srgdev.com

Thanks

**Comment by LittleDuke** [comment]
We ARE using external mode and NO there was not a double book -- the slot was absolutely available.   Had two reports of it yesterday -- Will upgrade and enable debug.

**Comment by LittleDuke** [comment]
Patch appears to have worked.  Closing issue.
