### ISSUE TITLE
External mode is broken

### ISSUE THREAD

**Issue by pH142857** [SergeyMosin/Appointments#218]
- time slot mode set to "External" with a source agenda and a target agenda (Nextcloud agendas)
- "_Require "Appointment" category_" unticked
- The events in the source agenda aren't accounted in the app, even with the Free/Busy field set to Free.
--> External mode seems to be broken.

[Settings dump](https://github.com/SergeyMosin/Appointments/files/6661919/appointmentssettingsdump.txt)

**Comment by SergeyMosin** [comment]
Can you please send me (sergey [at] srgdev.com) the `.ics` file for one of the events/appointments that are not being displayed in the appointments app.

**Comment by pH142857** [comment]
Can't reproduce: I am now using "in production" the Appointments main public page I was using for tests, so I created a new page to reproduce the issue, and it seems to work fine. I'll try again when I have no more appointments pending.
