### ISSUE TITLE
[simple mode] Control slots from the Nextcloud agenda

### ISSUE THREAD

**Issue by pH142857** [SergeyMosin/Appointments#219]
Slot events must have the Appointment category to be accounted by the Appointment app. You can't add the Appointment category in the Nextcloud interface. Hence:
- Create an event in the source NC agenda with the free/busy field set to "_free_": it does not appear in the app.
- Create a slot in the app, then from the NC Agenda, remove the Appointment category from the generated event: it does not appear anymore in the app.
--> Is it possible to make the Appointment category optional just like when, in external mode, the option _"Require "Appointment" category"_ is unticked?

**Comment by SergeyMosin** [comment]
> You can't add the Appointment category in the Nextcloud interface

Can you check here:

![image](https://user-images.githubusercontent.com/10747559/122271799-d13c8300-cead-11eb-9296-f50c851dd4e3.png)

**Comment by pH142857** [comment]
Yes I'm positive it does not appear. And for events created by the app, 
it appears but disappears as soon as I untick it.

Le 16/06/2021 à 20:21, Sergey Mosin a écrit :

**Comment by nolens** [comment]
> PS: I would use external mode instead if it didn't [seem to be broken](#218).

The issue you are linking to is closed. Also in my experience, external mode works fine !

**Comment by pH142857** [comment]
Hi @SergeyMosin would you care to explain why you closed this as `wontfix` ? It appears to me it's an obvious bug, maybe related to language.
