### ISSUE TITLE
[simple mode] How to delete time slots?

### ISSUE THREAD

**Issue by pH142857** [SergeyMosin/Appointments#220]
In time slot mode "Simple".
I found no way to delete a time slot within the app. I see a "_delete everything_" button in each day "..." menu of the "_add to agenda_" page, but it's greyed out. How is it supposed to work?

PS : I could delete the event from the Nextcloud agenda, but [I can't drive the whole slots process from there](https://github.com/SergeyMosin/Appointments/issues/219).

**Comment by SergeyMosin** [comment]
>  I see a "delete everything" button in each day "..." menu of the "add to agenda" page, but it's greyed out. How is it supposed to work?

This is to delete events **while you are creating them** before they are saved.

**Comment by pH142857** [comment]
Okay, so is there no way to delete timeslots you created in the app? Can it be a feature request then? Sounds mandatory to me.

**Comment by small1** [comment]
Just delete the timeslot in the calendar and it doesnt show in appointments anymore.

**Comment by pH142857** [comment]
> Just delete the timeslot in the calendar and it doesnt show in appointments anymore.

Thanks, that's what I said in my PS in the OP, but it's a workaround, this app should have this feature by itself to have the [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) basics.

**Comment by SergeyMosin** [comment]
There is an option to "clean-up" old appointments here:
![image](https://user-images.githubusercontent.com/10747559/128640367-9eb02b4d-201a-494f-b8f4-cda45e82e80e.png)

I have no plans for adding an option to delete (or move) current/future events as they should be managed from one place: **"the calendar app"**
@pH142857 However, I do agree that some kind of "bulk delete" option is needed in the calendar app, so if you want to pursue this further please open a feature request with the calendar app

**Comment by pH142857** [comment]
> I have no plans for adding an option to delete (or move) current/future events as they should be managed from one place: **"the calendar app"**
Hello @SergeyMosin, thanks for your answer. As I said in the OP, on the contrary, events cannot be managed from the calendar app only. I understand your reluctance to add a feature that's not in your roadmap, and I don't know how the governance system of this app but what if someone reading this was willing to develop such feature? I wish Nextcloud to become a credible workspace with the power of the opensource community and such drawbacks are making it less user-friendly. I hope you understand.

**Comment by SergeyMosin** [comment]
@pH142857 and anyone willing to contribute code, pull request are always welcome.
Thanks in advance
