### ISSUE TITLE
[simple mode] Some slots don't appear

### ISSUE THREAD

**Issue by pH142857** [SergeyMosin/Appointments#221]
I created slots for a whole week:
![appointments1](https://user-images.githubusercontent.com/11050141/122444920-518fe080-cfa1-11eb-9490-969b074ccd7f.png)

But only the first three days of the week have slots:
![appointments2](https://user-images.githubusercontent.com/11050141/122444976-60769300-cfa1-11eb-9093-54997fce7121.png)
There are also slots for the next week, and the Next button seems active, but it actually does nothing, the UI remains on the current week.

[Here is the generated ICS](https://github.com/SergeyMosin/Appointments/files/6672096/appointments.simple.mode.txt)
Creating new slots above the already existing ones on thursday and friday changes nothing.

**Comment by SergeyMosin** [comment]
How many weeks do you have enabled ?

![image](https://user-images.githubusercontent.com/10747559/122467905-0e297800-cf89-11eb-95e6-2df98b31807e.png)

**Comment by pH142857** [comment]
Okay, that was it. I didn't know about this parameter, and if I may, it's very confusing to be able to create slots and they don't show. My suggestions:
- Don't default it to 1 week, it's way too short;
- Add a warning on the slot creation page to remind of this setting.
Thanks anyway.

**Comment by JimKillock** [comment]
Thanks for pointing this out @SergeyMosin — where is this setting? I can't see it in the documentation and haven't seen it in the interface.

**Comment by xeruf** [comment]
yes, the default should be at least 2 weeks
