### ISSUE TITLE
[BUG] Blocking whole day in source calendar does not block slots in appointment app

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#226]
Hello @SergeyMosin ,

I am using external mode with apple calendar app. 

If I am blocking one whole day (or several whole days) in apple calendar app, the slots in appointment app are still showing as "available". The "free slots" should obviously marked as "taken" in the database. 

I send screenshots for clarification. 

Best
Tom
<img width="322" alt="Bildschirmfoto 2021-07-10 um 16 23 18" src="https://user-images.githubusercontent.com/21305551/125166366-a76c3880-e19b-11eb-84ac-78464385a9ef.png">
<img width="581" alt="Bildschirmfoto 2021-07-10 um 16 22 57" src="https://user-images.githubusercontent.com/21305551/125166370-ab985600-e19b-11eb-9ed0-4315fb332ec7.png">

**Comment by nolens** [comment]
Same issue as this one https://github.com/SergeyMosin/Appointments/issues/231

**Comment by SergeyMosin** [comment]
New option is available in v1.10.2: `Settings > Advanced Settings > All day events can block`

**Comment by nolens** [comment]
Hmmm, not working here yet... 

- I have added a new "whole day" event in apple calendar app. 
- activated the new option in "advanced settings" 

Free slots are still showing in appointments app (used in external mode). 

Best 
Tom

**Comment by SergeyMosin** [comment]
@nolens Can you please send me the `.ics` for the "whole day" event (sergey [@] srgdev.com )
Thanks

**Comment by nolens** [comment]
Done.

**Comment by SergeyMosin** [comment]
@nolens The whole day event in the `.ics` is marked as FREE aka `TRANSP:TRANSPARENT` and free events can not block other events (only BUSY events can block).
The free/busy settings in apple (shared) calendars might be related to this well know issue: https://discussions.apple.com/thread/250675325

**Comment by nolens** [comment]
**Summary:** 

I have created a "whole day" event in nextcloud calendar, and with the new option in "advanced settings" switched on, whole day events now indeed block open appointments in source calendar. 

You cannot use this feature from macos calendar App in "external mode" as of yet, because there is yet an implementation problem with the "FREE" markup in .ics data in apple calendar app. This will have to be solved by Apple, it seems. 


Thanks @SergeyMosin
