### ISSUE TITLE
Maximum appointment duration

### ISSUE THREAD

**Issue by thomarse-ef** [SergeyMosin/Appointments#230]
Would it be possible to extend the appointment length beyond 150 minutes?

**Comment by SergeyMosin** [comment]
What would a reasonable maximum duration be then ?

**Comment by thomarse-ef** [comment]
8 hours? I.e. the whole day

**Comment by jacotec** [comment]
I copy this request. There is no ability right now to block a whole work day (i.e. let the 08:00 slot allow 8 hours).

Also I can't add more than 3 options for a duration, what's the reason for that limit?

**Comment by SergeyMosin** [comment]
I guest for the next release the `weekly template` mode can be adjusted to:
- Max appointment length 8 hours
- 8 duration options max

**Comment by jacotec** [comment]
@SergeyMosin Sounds good for me! 👍🏻

**Comment by SergeyMosin** [comment]
8 hour duration is available since v1.11.2, closing.
