### ISSUE TITLE
Do not schedule appointments when calendar has an all-day event marked as busy

### ISSUE THREAD

**Issue by dbolton** [SergeyMosin/Appointments#231]
If you have an all-day event in your calendar and that event is marked as "show as busy" (instead of "show as free"), the Appointments app should not let people schedule an appointment on that day.

**Comment by nolens** [comment]
Same issue as this one 
https://github.com/SergeyMosin/Appointments/issues/226

**Comment by SergeyMosin** [comment]
Closing as a duplicate of #226

**Comment by nolens** [comment]
@SergeyMosin 

You have closed both issues now - was this intentional? Is the described behaviour intentional? 

Best
Tom

**Comment by SergeyMosin** [comment]
@nolens #226 is open
