### ISSUE TITLE
[request] remove/twist booking logic

### ISSUE THREAD

**Issue by Solar-Simon** [SergeyMosin/Appointments#233]
Hi there, great app, I use it often for appointment determination.

But often it does not fit into our style of appointment determination. 
The App works great if you have the same appointment procedure every time, like your appointments always run for the same time. In our application, every appointment is individual. Therefor i suggest to twist the logic a bit.

Current solution: I choose extern mode, cus we dont have recurring weekly procedures. On a free day I set appointments each 1h, for example 4 time slots.
Problem: both sides must fit into this grid

**Complex Solution:** We (the host) declare only one timeslot, lasting 4h, instead of 4 time slots each 1h. The client can choose any start time and duration. Maximum duration can be set by host. Very much like Weekly Template, but depending on an extern calender.
**Simple Solution**: We (the host) only want to make our whole available time visible. Appointments setting are diverse, so remove the booking option. The App only provides an Overview so the client can send individual suggestions via existing communication channels.

So for us it would be already great, to be able to remove the booking feature (Button and Text fields). So the client can only make himself a impression of availability.

Is my need clear? What are your thoughts?
Simon

**Comment by SergeyMosin** [comment]
I think you are looking for free/busy calendar feature like this https://raw.githubusercontent.com/nextcloud/calendar/master/screenshots/sidebar.png which is a part of calendar app already. I am not sure if it can be made public though. In any case, this is not something I'll be implementing in appointments app.
