### ISSUE TITLE
l10n: Meaning of text string

### ISSUE THREAD

**Issue by Valdnet** [SergeyMosin/Appointments#237]
A request to clarify the meaning of the text string for: `All day events can block`.

Could this mean "All day events can be blocked"?

_Reported by a translator from Transifex._

**Comment by SergeyMosin** [comment]
@Valdnet Before this feature ( #226  ) `all day events` were skipped when checking for blocked / conflicting time slots, now when this option is enabled, `all day event` will be considered for conflict checking.

All day event in Nextcloud:
![image](https://user-images.githubusercontent.com/10747559/133170511-b43e0b9d-b44d-4b41-814f-56e755bf2b42.png)

If the name is confusing I am open to other ideas. Thanks.

**Comment by Valdnet** [comment]
If this is an option to be set in the application, then maybe this version of the text string would be better: `All day events are to be blocked`.

**Comment by CafeTango** [comment]
Or perhaps simply "Include all day event in conflict check" ? ^_^

**Comment by Valdnet** [comment]
If it fits the task of the function, then it is behind the change.

**Comment by SergeyMosin** [comment]
I think "Include all day events in conflict check" is very clear, it will be used instead of "All day events can block" as of next release.
