### ISSUE TITLE
Leaving ".../index.php/..." away in the customer links

### ISSUE THREAD

**Issue by jacotec** [SergeyMosin/Appointments#238]
Hi,

testing around with this pretty app I found that the links to the created talk rooms are not very pretty.

A created room i.e. gives me this link when I copy it from the NC talk in the web interface: https://cloud.mydomain.de/call/b97e4e9i

The link which the customer gets in the email from the appointments app is: https://cloud.mydomain.de/index.php/call/b97e4e9i

Although it's more cosmetic the app should respect the " 'htaccess.RewriteBase' => '/' "  setting in Nextcloud

**Comment by SergeyMosin** [comment]
duplicate #185

**Comment by gitwittidbit** [comment]
um, so this is closed?

Because for me it still shows the index.php part (NC 27) although I have NC rewrite the base URL (as per above)...
