### ISSUE TITLE
One booked appointment blocks slots in same time range

### ISSUE THREAD

**Issue by steiditi** [SergeyMosin/Appointments#239]
I am using the appointments app, to manage how many people can come to a specific time range. A few weeks ago, this worked just fine in weekly mode. I entered 10 slots for 6:00 to 7:00 pm and ten people were able to book a slot. Some update ago this stopped working. Only one person is able to get a slot and then all slots at the same time are blocked. In simple mode, where I have to enter every slot every week again, this still works. But not in external and weekly mode. Could you please allow this feature again?

**Comment by SergeyMosin** [comment]
This is the default behavior for `external` and `weekly template` modes. The only way to have multiple appointments in the same time is to use the `simple` mode. 

> A few weeks ago, this worked just fine in weekly mode. 
I am really not sure why/how it worked in the `weekly` mode for you unless it was some kind of bug, but the is noting in the code that would support this kind of behavior.

Additionally "Multiple attendees for one appointment" feature is tracked in this thread #54
