### ISSUE TITLE
No timezone Detection

### ISSUE THREAD

**Issue by Ethaseo** [SergeyMosin/Appointments#240]
I installed the latest nextcloud version with php 8 and the appointments app cant be used because it cant detect a timezone from either the default calander nor the one created by nextcloud.

**Comment by SergeyMosin** [comment]
Are there any error in the logs ?
Was this working with PHP7 ?
What is the time zone in nextcloud calendar ?
![image](https://user-images.githubusercontent.com/10747559/133172002-e1913b95-56d7-4ca4-a96e-ca1ca9ae8206.png)

Thanks.

**Comment by Ethaseo** [comment]
Timezone is automatic (Europe/Berlin)

I havent tried it with PHP7, i used 8 to install nc with the first time

I couldnt find any specific errors in the logfiles that relate to this issue but if you let me know what other logfiles to check then the apache log ( i use it for nc too ) i can sure do that or email you the logs privately

**Comment by SergeyMosin** [comment]
@Ethaseo Can you please send me the `settings dump` to sergey [at] srgdev.com so I can try to replicate the issue.
`Settings > Advanced Settings > Debugging > Settings Dump`

**Comment by SergeyMosin** [comment]
please see this comment https://github.com/SergeyMosin/Appointments/issues/243#issuecomment-970230463
Closing this and discussion can continue in #243
