### ISSUE TITLE
24h time

### ISSUE THREAD

**Issue by artelse** [SergeyMosin/Appointments#244]
I have set my NextCloud calendar to a 24h clock by means of setting the right language in my settings. The calendar correctly shows time in 24h format, but Appointments stays at AM/PM format. How can I change this?

**Comment by SergeyMosin** [comment]
As of now the time/date format depends on the language setting , for example "German" and most European languages will have 24 hour format and "English (US)" will have the AM/PM format.

I'll look into making this work with NC "Locale" settings, which actually does make more sense.

Thanks for the report.

**Comment by xeruf** [comment]
Hey, I would also very much like to see this implemented :)

**Comment by SergeyMosin** [comment]
Fixed in v1.12.6
