### ISSUE TITLE
Weekly slots not repeating

### ISSUE THREAD

**Issue by JimKillock** [SergeyMosin/Appointments#247]
In the user manual it says:

> **Weekly Template** - in this mode you can set a weekly template and it will be repeated automatically.

However in our install the weekly template is by default applying for one week only without repetition. Does anyone have any ideas what might be causing this, and whether that is a bug, error in documentation, or a setup problem?

**Comment by SergeyMosin** [comment]
@JimKillock https://github.com/SergeyMosin/Appointments/issues/221#issuecomment-863543374

**Comment by JimKillock** [comment]
Resolved, as per #221 — I didn't find the setting that controls this.
