### ISSUE TITLE
Create editable Wiki documentation pages

### ISSUE THREAD

**Issue by JimKillock** [SergeyMosin/Appointments#248]
I'd like to improve the documentation a bit, and also track down a couple of user problems I haven't resolved yet. I've come across perhaps 3-4 set up problems which took me a few hours to resolve, which could be cleared up by documentation. I've noted those against bug reports, but it would be better for these to be on a Wiki page and ultimately the user guide. (Is the user guide editable? i wasn't able to see how to do this?)

**Comment by SergeyMosin** [comment]
There is no wiki page yet, but if you post some info here I'll add it to the help/tutorial section.

**Comment by SergeyMosin** [comment]
I have tried github wiki but it looks like it does not support pull requests and I am not familiar with other wiki hosting providers.

Documentation related  issues / questions will be tracked in #167 

Thanks
