### ISSUE TITLE
Disable confirmation email to the person appointment is booked 

### ISSUE THREAD

**Issue by elhananjair** [SergeyMosin/Appointments#249]
Hello there is it possible to disable confirmation email to the person appointment is booked? For the person who wanted to book an appointment, it is good to send an email when the appointment is confirmed but for the person who confirmed the appointment I want to disable the confirmation email. Thanks

**Comment by SergeyMosin** [comment]
Email related options are in: `Settings > Email Settings` 

I think you want to un-check the "_Email Me when an appointment is:_ `confirmed`" option

![image](https://user-images.githubusercontent.com/10747559/141487411-a332d18b-3bdc-43f4-8c9d-dc61202a3b7d.png)

**Comment by elhananjair** [comment]
Hello @SergeyMosin I tried that before and it still sends "Confirmation mail" after I confirm an appointment. 
![image](https://user-images.githubusercontent.com/69236638/141730060-977adc0f-7f9d-4095-9912-a3abfccd268d.png)
and here is my setting 
![image](https://user-images.githubusercontent.com/69236638/141730140-1cbd6af0-db98-4e80-a570-92484d60ad8c.png)

In reverse even though I have checked options under Email Attendee, the email is not delivered to that person.

**Comment by elhananjair** [comment]
![image](https://user-images.githubusercontent.com/69236638/141742935-ab0bf73d-537a-4771-8ec7-33e33d42859d.png)
Does this setting override any setting in appointment?

**Comment by SergeyMosin** [comment]
@elhananjair Can you send me the event/appointment data:

![image](https://user-images.githubusercontent.com/10747559/141784570-33d2e9ae-081d-456b-9a6f-90b8b7931f94.png)

Also, where is the "Calendar Server" menu shown in your screenshot?

**Comment by elhananjair** [comment]
![image](https://user-images.githubusercontent.com/69236638/141787095-44f384d1-b199-4a04-8d2e-4d82071a55ab.png)

In admin setting you can find it in Groupware option

**Comment by elhananjair** [comment]
@SergeyMosin Any ideas?

**Comment by SergeyMosin** [comment]
Sorry I can not reproduce this

**Comment by elhananjair** [comment]
@SergeyMosin I think I messed up with the concept of Appointment and I don't think am not doing it the right way can you please help me. 🥶🥶
This is my scenario:
![image](https://user-images.githubusercontent.com/69236638/144982986-9dcb0466-92ef-43e8-808d-e39a0fa66e2b.png)

This is what I want:
     - Customers give an info to Secretary and the secretary fills that info and book an appointment on behalf of the customers 
     - The manager then confirms if he/she got a time and can meet the customer 
     - And then the Customer got an appointment have been confirmed from a manager 
    
Can you please tell me the way I achieve this with settings I should tweak. Thank you

**Comment by SergeyMosin** [comment]
@elhananjair This app is designed to be customer facing, and unfortunately does not work in the scenario you described. Maybe the secretary can create an event directly in Calendar App with `Tentative` status and then manager can switch the status to `Canceled` or `Confirmed` but I am not sure which emails are going to be sent out by NC during this process.

**Comment by elhananjair** [comment]
> @elhananjair This app is designed to be customer facing, and unfortunately does not work in the scenario you described. Maybe the secretary can create an event directly in Calendar App with `Tentative` status and then manager can switch the status to `Canceled` or `Confirmed` but I am not sure which emails are going to be sent out by NC during this process.

@SergeyMosin What if the secretary acts as customer? So that the customer got every notifications as the appointment got modified. btw we are using it like that for now, the secretary fills the user info and books the appointment and then the manager will confirm it since the secretary used the customers email address the customers will get notified when an appointment got modified. So in our case its working as we wanted in our scenario, we just wanted to disable the confirmation email sent to our manager when he confirms an appointment. Thanks again.
