### ISSUE TITLE
Lead time does not work

### ISSUE THREAD

**Issue by PekkaJalonen** [SergeyMosin/Appointments#254]
Hello,

I have Weekly template in use, meeting slots are simply 1 hour slots with 30 and 60 min options. I have set Lead time to 15minutes, and appointments still show available slots back to back. User was able to book meeting at 10:00 AM even thought the lead time was set 15min and previous meeting was ending at 10:00 AM. Also another user booked a meeting right after the other.

Am I missing something, I thought that there should not be slot available between 10:00-10:30 AM if there is a meeting  which ends at 10:00 AM.

Is this lead time configuration only for certain type of calendar or how should I configure it. Debug also lists the 'prepTime' => '15'. I can provide more dump details if needed.

**Comment by SergeyMosin** [comment]
In this case "Lead Time" of 15 minutes means that if you have two appointments for example one at 10:00 and on other one at 11:00 and someone visits the page at 9:50 for example the 10:00 o'clock appointments is not going to be shown.

However there are plans to add a "Cool Off Time" option that would work in the way you described.
