### ISSUE TITLE
[feature] connect sms providers for confirmation/reminder

### ISSUE THREAD

**Issue by mokkin** [SergeyMosin/Appointments#26]
To confirm and/or remind the attendee of appointments there should be an option to connect to an sms provider.

**Comment by SergeyMosin** [comment]
All standard event are dispatched as usual here [CalDavBackend.php](https://github.com/nextcloud/server/blob/24d0fb9fcd8b190b6c16c4608c95785036b1eb31/apps/dav/lib/CalDAV/CalDavBackend.php#L1136) for example. I guess it up to an sms provider to listen and take appropriate action.
Is there an SMS provider for nextcloud ?

**Comment by francoisPE** [comment]
Hello,
I am back to this topic.
There is no app able to send sms with nextcloud. There is only one to backup sms : phone sync app
Everything is ready in your app to send mails.
Would it be possible to document a little classes, etc... to help connect to an API such as octopush ?

example : https://octopush.com/en/sms-gateway-api-documentation/send-sms/
with a shell script to be adapted...
curl -X POST \ 
 'https://api.octopush.com/v1/public/sms-campaign/send' \ 
 -H 'Content-Type: application/json' \ 
 -H 'api-login: @email.org' \ 
 -H 'api-key: *************' \ 
 -H 'cache-control: no-cache' \ 
 -d '{
   "recipients": [
     {
       "phone_number": "+336000123",
       "first_name": "Axelle",
       "last_name": "Durand",
       "param3": "Mme"
     }
   ],
   "text": "Here is an SMS. STOP at 30101",
   "type": "sms_premium",
   "purpose": "wholesale",
   "sender": "Entreprise"
 }'

**Comment by francoisPE** [comment]
That would be really nice !
There are several way to connect to API's for sms depending provider. It is always quite well documented !

Thanks a lot for your proactivity !

**Comment by Fr3dDr3sk3n** [comment]
Is there a solution to the chrome based browsers issue not showing the agenda in a website embedded config? 
FireFox has zero issue. 
Check URL: https://fred-internet.nl/helpdesk/afspraak-inplannen-monteurs-agenda 

Thanks!
