### ISSUE TITLE
Help with appointment form

### ISSUE THREAD

**Issue by ChotaFallen** [SergeyMosin/Appointments#260]
Good morning,

because I don´t know where to post this question for help, I do it here.
I have not much knowledge of linux uns nextcloud atm, starting for 2 weeks I like the appointment app.

But I have some questions:
Where is the the file stored which produce the appointment page? 
The pic in the link show my questions.

_Where can I change (1.) the color of the header which is blue now and change the name?[
]([url](url))
_ Can I use the space (2.) around the form, because I need some descriptions for it. 
 I can´t embed it in another page like an iframe I have to use the original one.
Would be great if you had some textareas we can fill in like extra field allready exist.

Last one, after cofirmation, how do one go back to the appointment page or other? Theres is no link no nothing?

[https://ibb.co/BK5vZJs](url)

Tabbi

**Comment by SergeyMosin** [comment]
`Settings > Customize Public Page > Advanced Settings > Style Override` (Basic CSS knowledge is required )
