### ISSUE TITLE
[Feature request] Captcha

### ISSUE THREAD

**Issue by francoisPE** [SergeyMosin/Appointments#261]
Hello,
Your app is amazing.
I would be interested in a captcha : a picture to choose, an add to do, a picture with letters... ( NOT google Recaptcha )

Is it something you can plan ?
It seems there is already an event on submit ! it would help :-)
Many thanks

**Comment by SergeyMosin** [comment]
hCaptcha is available in v2.2.0 , this is still a third-party service but their privacy policy ( https://docs.hcaptcha.com/faq/#should-i-update-my-privacy-policy-when-enabling-hcaptcha )  seems to be a bit better than Google's reCaptcha
