### ISSUE TITLE
Booking appointment with two different email address 

### ISSUE THREAD

**Issue by elhananjair** [SergeyMosin/Appointments#263]
Hello, there I tried to book an appointment with two different email addresses in user/organization settings. Unfortunately, if I book that appointment at once, which means, if I book the second appointment with a different email address before the first appointment get confirmed, Only the second email address will get "confirmed" email **twice** (The first booked appointment's confirmed email also sent to the second booked email). In other words, the first email address won't get "Confirmed" mail as it goes to the second booked email address. 

I don't know if I described it well, in my case I am using appointments to book for multiple different persons on behalf of them and there is one person who confirms all appointments I book. The problem is if I send multiple booked appointments at once, only the last email address I used in the user/organization setting will be used to get "confirmed" mail including for other booked appointments.   
Thanks

**Comment by elhananjair** [comment]
Hello @SergeyMosin 
This issue hasn't gotten attention yet I guess, can you please check it I still face this problem on NC 25 with the latest Appointment app.

**Comment by SergeyMosin** [comment]
RE: _using appointments to book for multiple different persons on behalf of them and there is one person who confirms all appointments I book_

This type of system does not work with this app. There is a similar feature request here #222 , but currently it is on the backlog.
