### ISSUE TITLE
Appointment slots disappear occasionally when appointment is cancelled

### ISSUE THREAD

**Issue by Bromptonaut** [SergeyMosin/Appointments#264]
Occasionally appointment slots disappear after they have been cancelled. This is not always the case and so far I wasn't able to provoke it myself. If I do cancel an appointment, the slot occurs again. I have no idea how to gather more information to find cause for this behavior. Does anybody observe the same? Is there anything I could do to learn more about the reason for that phenomenon?

**Comment by SergeyMosin** [comment]
@Bromptonaut can you please send me the settings dump so I can try to reproduce this. `Settings > Advanced Settings > Debugging > Settings Dump` ( sergey [at] srgdev.com )

**Comment by Bromptonaut** [comment]
Nextcloud Version: 22.2.3
Appointments Version: 1.11.2
Timezone: Europe/Berlin
Key: No

org_info: array (
  'organization' => 'Praxis Drewermann',
  'email' => 'praxis-drewermann@gmx.de',
  'address' => 'Dr. med. Eva Drewermann
Viktoriastraße 67
44787 Bochum',
  'phone' => '0234 9647835',
)

email_options: array (
  'icsFile' => true,
  'skipEVS' => false,
  'attMod' => true,
  'attDel' => true,
  'meReq' => false,
  'meConfirm' => true,
  'meCancel' => true,
  'vldNote' => 'Bitte bestätigen Sie Ihre verbindliche  Terminreservierung.',
  'cnfNote' => 'Bitte erscheinen Sie zum Termin im T-Shirt und bringen Folgendes mit:
- Krankenkassenkarte
- Impfausweis
- die ausgefüllt und unterschriebene Einverständniserklärung https://praxis-drewermann.de/wp-content/uploads/2021/05/Einverstaendniserklaerung_Covid_Impfung_202105.pdf

Bitte beachten Sie auch die Hinweise auf unserer Internetseite: https://praxis-drewermann.de/corona-impfung/',
)

calendar_settings: array (
  'mainCalId' => '22',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'nrPushRec' => true,
  'nrRequireCat' => false,
  'nrAutoFix' => false,
  'tmmDstCalId' => '20',
  'tmmMoreCals' => 
  array (
  ),
  'prepTime' => '0',
  'whenCanceled' => 'reset',
  'tsMode' => '0',
  'allDayBlock' => false,
)

page_options: array (
  'formTitle' => 'Corona-Impfung mit Impfstoff Moderna',
  'nbrWeeks' => '8',
  'showEmpty' => false,
  'startFNED' => false,
  'showWeekends' => true,
  'time2Cols' => false,
  'endTime' => false,
  'hidePhone' => false,
  'showTZ' => false,
  'gdpr' => 'Ich bin Patient*in der Praxis Drewermann und  akzeptiere die Datenschutzerklärung.  Wir weisen darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. ',
  'pageTitle' => 'Praxis Drewermann',
  'pageSubTitle' => 'Viktoriastraße 67, 44787 Bochum',
  'metaNoIndex' => false,
  'pageStyle' => '',
)

more_pages: array (
  'mainCalId' => '-1',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'tmmDstCalId' => '-1',
  'tmmMoreCals' => 
  array (
  ),
  'tsMode' => '2',
  'organization' => '',
  'email' => '',
  'address' => '',
  'phone' => '',
  'formTitle' => '',
  'p1' => 
  array (
    'mainCalId' => '23',
    'destCalId' => '-1',
    'nrSrcCalId' => '-1',
    'nrDstCalId' => '-1',
    'tmmDstCalId' => '19',
    'tmmMoreCals' => 
    array (
    ),
    'tsMode' => '0',
    'organization' => '',
    'email' => 'praxis-drewermann@gmx.de',
    'address' => '',
    'phone' => '',
    'formTitle' => 'Corona-Impfung mit Impfstoff BioNTech',
  ),
)

pages: array (
  'p0' => 
  array (
    'enabled' => 1,
    'label' => 'Corona-Impfung Moderna',
  ),
  'p1' => 
  array (
    'enabled' => 1,
    'label' => 'Corona-Impfung  Biontech',
  ),
)

dir_info: array (
  0 => 
  array (
    'title' => 'Corona-Impfung',
    'subTitle' => 'Impfstoff Johnson & Johnson ',
    'text' => '1-mal-Impfstoff',
    'url' => 'https://drbocloud.spdns.de/index.php/apps/appointments/pub/68F1VnGoc3OA2Kr2aFL%2BTBlGIgSX/form',
  ),
  1 => 
  array (
    'title' => 'Corona-Impfung',
    'subTitle' => 'Impfstoff Biontech',
    'text' => '',
    'url' => 'https://drbocloud.spdns.de/index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/form',
  ),
)

reminders: array (
  'data' => 
  array (
    0 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    1 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    2 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
  ),
  'friday' => false,
  'moreText' => '',
)

appt_talk: array (
  'enabled' => false,
  'delete' => false,
  'emailText' => '',
  'lobby' => false,
  'password' => false,
  'nameFormat' => 0,
  'formFieldEnable' => false,
  'formLabel' => '',
  'formPlaceholder' => '',
  'formTxtReal' => '',
  'formTxtVirtual' => '',
  'formTxtTypeChange' => '',
  'formDefLabel' => 'Besprechungstyp',
  'formDefPlaceholder' => 'Besprechungstyp auswählen',
  'formDefReal' => 'Persönliche Besprechung',
  'formDefVirtual' => 'Online (Audio/Video)',
)

fi_json: array (
)

fi_html: array (
  0 => '',
)

useDefaultEmail: NULL

emailFixOpt: NULL

template_info: array (
  'tzName' => 'Europe/Berlin',
  'tzData' => 'BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE',
)

template_data: array (
)

**Comment by SergeyMosin** [comment]
Looks like you have the `When Attendee Cancels` option set to `Reset`, which will delete the canceled time slot and make it available for an other person to book. The other option is to `Mark` the slot as canceled, but then the slot will not be available for booking by an other person.
There are plans to add `Cancel and Reset` option.
 
![image](https://user-images.githubusercontent.com/10747559/143313746-402fbdc1-fd1c-4f9d-8d16-719e5143e61c.png)

**Comment by Bromptonaut** [comment]
The reset-option is chosen intentionally. The problem is that in sometimes, but not always, the cancelled time slot is not made available again. In those cases the time slot disappears from the calendar.  I apologize for not having been clear about that,

**Comment by netdox** [comment]
Hello,
I've the same issue on my nextcloud, I set up on _Calendars and Schedule >  Advanced Settings  > Reset (make time slots available)_ but after cancellation  by user or client the time slot come not available again. (**always**)
Here my settings, maybe my mistake in my configuration?
Thanks for help.

> `Nextcloud` Version: 21.0.7
Appointments Version: 1.11.3
Time zone: Europe/Berlin (calendar: Europe/Berlin, core: Asia/Jakarta)
Key: No
org_info: array (
  'organization' => 'Test',
  'email' => '******',
  'address' => 'Ihr Arbeitsplatz',
  'phone' => '',
)
email_options: array (
  'icsFile' => true,
  'skipEVS' => true,
  'attMod' => true,
  'attDel' => true,
  'meReq' => false,
  'meConfirm' => false,
  'meCancel' => false,
  'vldNote' => '',
  'cnfNote' => '',
)
calendar_settings: array (
  'mainCalId' => '11',
  'destCalId' => '-1',
  'nrSrcCalId' => '10',
  'nrDstCalId' => '10',
  'nrPushRec' => true,
  'nrRequireCat' => false,
  'nrAutoFix' => false,
  'tmmDstCalId' => '-1',
  'tmmMoreCals' => 
  array (
    0 => '10',
 ),
  'prepTime' => '0',
  'whenCanceled' => 'reset',
  'allDayBlock' => false,
  'tsMode' => '0',
)
page_options: array (
  'formTitle' => 'Test',
  'nbrWeeks' => '3',
  'showEmpty' => true,
  'startFNED' => false,
  'showWeekends' => false,
  'time2Cols' => false,
  'endTime' => false,
  'hidePhone' => false,
  'showTZ' => false,
  'gdpr' => '',
  'pageTitle' => 'Office365',
  'pageSubTitle' => 'Buchen Sie Ihren Termin für die Umstellung',
  'metaNoIndex' => false,
  'pageStyle' => '',
)
more_pages: NULL
pages: array (
  'p0' => 
  array (
    'enabled' => 1,
    'label' => '',
  ),
)
dir_info: array (
)
reminders: array (
  'data' => 
  array (
    0 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    1 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    2 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
  ),
  'friday' => false,
  'moreText' => '',
)
appt_talk: array (
  'enabled' => false,
  'delete' => false,
  'emailText' => '',
  'lobby' => false,
  'password' => false,
  'nameFormat' => 0,
  'formFieldEnable' => false,
  'formLabel' => '',
  'formPlaceholder' => '',
  'formTxtReal' => '',
  'formTxtVirtual' => '',
  'formTxtTypeChange' => '',
  'formDefLabel' => 'Meeting Type',
  'formDefPlaceholder' => 'Select meeting type',
  'formDefReal' => 'In-person meeting',
  'formDefVirtual' => 'Online (audio/video)',
)
fi_json: array (
)
fi_html: array (
  0 => '',
)
useDefaultEmail: NULL
emailFixOpt: NULL
template_info: array (
  'tzName' => 'Asia/Jakarta',
  'tzData' => 'BEGIN:VTIMEZONE
TZID:Asia/Jakarta
BEGIN:STANDARD
TZOFFSETFROM:+0700
TZOFFSETTO:+0700
TZNAME:WIB
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE',
)
template_data: array (
)`

**Comment by Bromptonaut** [comment]
This is what I find in the log:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RAW
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
{"reqId":"LqqmXycJhFEVvO2X6Zg6","level":2,"time":"2021-11-29T10:50:54+00:00","remoteAddr":"34.218.224.190","user":"--","app":"appointments","method":"GET","url":"/index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=0tgcZ1iRO8GifqxAL5OcbeyqGBD8aTxbue1RWXuAlcBxvAgt%2BubF%2Fh%2BcmaDRvgp58DFhzHBJ%2BC5k%3D","message":"can not re-create appointment, no dt_info","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","version":"22.2.3.0","id":"61a52b4e6b55d"}

{"reqId":"18Pv94FqPwQ0ui4UTcvu","level":3,"time":"2021-11-29T10:50:51+00:00","remoteAddr":"52.37.222.243","user":"--","app":"appointments","method":"GET","url":"/index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=05qGwZLSeoQ9qgnkV4pNjsQjoDMIzIYCLhfVv2cWTeDWEnRtrovk3EJQQBMLSblWECgAXiT3l4BY%3D","message":"addAppointments() failed 1:Bad user Id.","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","version":"22.2.3.0","id":"61a52b4e6b577"}

{"reqId":"2f4nq6zJz2HkiQAQJz3z","level":2,"time":"2021-11-29T10:50:50+00:00","remoteAddr":"54.204.248.166","user":"--","app":"appointments","method":"GET","url":"/index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=05qGwZLSeoQ9qgnkV4pNjsQjoDMIzIYCLhfVv2cWTeDWEnRtrovk3EJQQBMLSblWECgAXiT3l4BY%3D","message":"can not re-create appointment, no dt_info","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","version":"22.2.3.0","id":"61a52b4e6b593"}

{"reqId":"JAreBHqjLSfLxTq996DC","level":3,"time":"2021-11-29T07:44:53+00:00","remoteAddr":"89.247.225.228","user":"--","app":"appointments","method":"GET","url":"/index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=0LHNlSgSsnVuUwekB4kb2BQqDBEdivibZRq5tUa9KPTlgqika43E%2B1CzKmVkL4zclsx%2B9xmfv2fM%3D","message":"addAppointments() failed 1:Bad user Id.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.3.0","id":"61a52b4e6b5aa"}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FORMATTED 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[appointments] Warning: can not re-create appointment, no dt_info

GET /index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=0tgcZ1iRO8GifqxAL5OcbeyqGBD8aTxbue1RWXuAlcBxvAgt%2BubF%2Fh%2BcmaDRvgp58DFhzHBJ%2BC5k%3D
from 34.218.224.190 at 2021-11-29T10:50:54+00:00
[appointments] Error: addAppointments() failed 1:Bad user Id.

GET /index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=05qGwZLSeoQ9qgnkV4pNjsQjoDMIzIYCLhfVv2cWTeDWEnRtrovk3EJQQBMLSblWECgAXiT3l4BY%3D
from 52.37.222.243 at 2021-11-29T10:50:51+00:00

[appointments] Warning: can not re-create appointment, no dt_info

GET /index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=05qGwZLSeoQ9qgnkV4pNjsQjoDMIzIYCLhfVv2cWTeDWEnRtrovk3EJQQBMLSblWECgAXiT3l4BY%3D
from 54.204.248.166 at 2021-11-29T10:50:50+00:00

[appointments] Error: addAppointments() failed 1:Bad user Id.

GET /index.php/apps/appointments/pub/jKoabKOMGbBtBEk1ecoRSQCx8pcjgk801/cncf?d=0LHNlSgSsnVuUwekB4kb2BQqDBEdivibZRq5tUa9KPTlgqika43E%2B1CzKmVkL4zclsx%2B9xmfv2fM%3D
from 89.247.225.228 at 2021-11-29T07:44:53+00:00

**Comment by SergeyMosin** [comment]
@Bromptonaut Thank you for the logs. The problem has been identified and the fix will be available in v1.11.5 ( probably the next day or two )

**Comment by SergeyMosin** [comment]
Should be fixed in v1.11.6

**Comment by Bromptonaut** [comment]
Didn't observe the issue since update to v1.11.6 which was 4 days ago, so I think this is solved. Sergey, I appreciate your efforts. Thank you for providing the appointments-app.
