### ISSUE TITLE
The directory page and forms do not work if another user is logged in.

### ISSUE THREAD

**Issue by alSeveR** [SergeyMosin/Appointments#265]
I have created several forms from the nextcloud admin user and they work perfectly if this account is open or if no account is open. However, if another account is open, the link to the directory page or those of the forms are redirected to the nextcloud home page.

**Comment by SergeyMosin** [comment]
I can not reproduce, what does your "Directory" page URL looks like. It should look something like this:
```
https://[YOUR_DOMAIN]/index.php/apps/appointments/pub/D_G7Qa_Sow5QHbc%3D/dir
```
I just need the part after `index.php`

![image](https://user-images.githubusercontent.com/10747559/143305552-1443da2a-d5a1-40ae-b95c-afd450f8b78e.png)

**Comment by alSeveR** [comment]
https://[DOMAIN]/index.php/apps/appointments/pub/kSoughGoHySYrX6958GT%2Bg%3D%3D/dir

**Comment by alSeveR** [comment]
I had forgotten to say that the app is only enabled for the administration account. I have already checked that if the user is in a group that can use the app, it works fine. However, for our intended use it is not useful for users to be able to create their own forms. Therefore, could we implement that even if the app is not enabled for that user, it can redirect properly to the forms?

**Comment by SergeyMosin** [comment]
Ah I see, this is a know issue the workaround is here https://github.com/SergeyMosin/Appointments/issues/154#issue-741374732 . I hope it works for you as well.

PS: I'll add info about `limitToGroups` setting to docs

**Comment by alSeveR** [comment]
This solution works for me. I imagine the only way to customize the message is to modify the template, and that will also be overwritten with updates.

**Comment by SergeyMosin** [comment]
@alSeveR Yes.
