### ISSUE TITLE
External mode, "No slot found" : Is Appointments really scraping my calendar to find available slots ?

### ISSUE THREAD

**Issue by Kalytis** [SergeyMosin/Appointments#266]
Hi, I'm using the app for a few weeks now (v1.11.3 atm), and I'm looking for a way to just set a time range as available, and let people select their own appointment hours, instead of adding slots myself.

I've set my working hours on Nextcloud Agenda ("Personal availability settings"), and then set the Appointments app on External mode, but even though my days are free, Appointments show no available time slots for meetings.

Did I do something wrong ?

Thanks a lot

**Comment by Jawn78** [comment]
When using external mode you are telling the appointment apps which dates/times you are available.  If you go to the Settings>Advanced Settings >External Mode Settings: You will see require "Appointment" category. That is most likely why they are not being picked up. Also make sure they are marked as Free. I do 30 minute meetings and use CalDav Synchronizer to sync nextcloud with my Outlook calendar.  Also, check the Manage Appointment Slots to make sure you are choosing the correct source and destination calendar.

**Comment by SergeyMosin** [comment]
@Kalytis Please see the "Quick Start Guide" in Help/Tutorial section
