### ISSUE TITLE
Embedding forms only works with secret configuration :-)

### ISSUE THREAD

**Issue by spaetz** [SergeyMosin/Appointments#268]
Embedding forms with https://XXXX/index.php/apps/appointments/embed/XXX/form leads to

`content-security-policy [...] frame-ancestors 'self' [...]`

So, embedding the forms in other sites as iframes is forbidden, at least by recent Firefoxes. 
Looking at [this](https://github.com/SergeyMosin/Appointments/blob/905712a5ff16e98ec46b6b55b89e4dafa05a9151/lib/Controller/PageController.php#L164) code shows the secret app configuration key `emb_afad_USERID`. And indeed after doing:

`sudo -u www-data php ./occ config:app:set appointments  emb_afad_MYUSERNAMEHERE --value="https//*.EMBEDDINGDOMAINHERE.de"`

This is being returned on the embedded form page:

`content-security-policy [...] frame-ancestors 'self' https://*.EMBEDDINGDOMAINHERE.de [...]`

And indeed, that made the difference between a "Firefox is not allowed to load this page" and a working embedded form!
Is it possible to expose, or at least document this useful setting? To make embedding actually work?

Thanks for Appointments!

**Comment by SergeyMosin** [comment]
@spaetz Embedding forms is somewhat tricky but there is some info in the Help/Tutorial already and also on how to "forward" email `Confirm`/`Cancel` buttons(links). I'll add a link your post to the `iFrame/Embedding` section of the help page, Thanks.
