### ISSUE TITLE
Multiple appointments with multiple calendars 

### ISSUE THREAD

**Issue by Tompion2k** [SergeyMosin/Appointments#271]
I love this app! Great idea, working perfectly! 👍
I do have one request:
It is no problem with one kind of appointment, working with a source and one destination calendar.
When you need more than one kind of appointment (e. g. book appointments with Mr x and book appointments mit Madam y) you will need a source calendar for Mr x and Madam y each).
What I found is, that you can use one source calendar only.... And booked appointments will spread to several destination calendars when you use more than one kind of appointment.

... So it would be great, if you can use a pair of calendars (1 source and 1 destination) for each kind of different appointments.

Thanks a lot!

**Comment by SergeyMosin** [comment]
Sorry, out of scope.
