### ISSUE TITLE
Can not set timezone template

### ISSUE THREAD

**Issue by the-moog** [SergeyMosin/Appointments#272]
After installation I get lots of these "Can not set timezone template" in the logs.
No further info (even a line number) so I can't debug further.

NC: 22.2.3
Appointments: 1.11.6

**Comment by SergeyMosin** [comment]
Can you send me the settings dump `Settings > Advanced Settings > Debugging > Settings Dump` to ( sergey [at] srgdev.com )

**Comment by SergeyMosin** [comment]
Can not replicate as of v1.11.10, closing.
