### ISSUE TITLE
Unable to activate the app 

### ISSUE THREAD

**Issue by davrot** [SergeyMosin/Appointments#273]
Hi,

the installation of the app (version 1.11.7) worked without any problems (directly using NextCloud via Web). 
Then I tried to activate it... And it didn't liked me at all...

[index] Error: openssl_random_pseudo_bytes(): Argument #1 ($length) must be greater than 0
POST /~nc/index.php/settings/apps/enable

[PHP] Error: openssl_cipher_iv_length(): Unknown cipher algorithm at /home/webserver/www/htdocs/users/nc/apps/appointments/lib/Migration/InstallHook.php#47
POST /~nc/index.php/settings/apps/enable

Nextcloud 22.2.3
PHP 8.0.7
OpenBSD 6.9 amd64

I have no problems to activate other apps. (I just tested it again with the Announcement center.)

best wishes
David

**Comment by SergeyMosin** [comment]
Appointments App requires `openssl` with `AES-128-CFB` cipher 
If you have access to command line can you run this:
```
php -r "var_dump(openssl_get_cipher_methods());"
```
it should output something similar to the list below and if you do not see `AES-128-CFB` then unfortunately appointments app will not run on your system as is and will require additional `PHP` config. Just FYI NC23 has native support for appointments in Calendar App https://player.vimeo.com/video/650621426?h=5896b9b0bd&badge=0&autopause=0&player_id=0&app_id=58479 
```
array(142) {
  [0]=>
  string(11) "aes-128-cbc"
  [1]=>
  string(21) "aes-128-cbc-hmac-sha1"
  [2]=>
  string(23) "aes-128-cbc-hmac-sha256"
  [3]=>
  string(11) "aes-128-ccm"
  [4]=>
  string(11) "aes-128-cfb"
  [5]=>
  string(12) "aes-128-cfb1"
  [6]=>
  string(12) "aes-128-cfb8"
  [7]=>
  string(11) "aes-128-ctr"
  [8]=>
  string(11) "aes-128-ecb"
  [9]=>
  string(11) "aes-128-gcm"
  [10]=>
  string(11) "aes-128-ocb"
  [11]=>
  string(11) "aes-128-ofb"
  [12]=>
  string(11) "aes-128-xts"
  [13]=>
  string(11) "aes-192-cbc"
  [14]=>
  string(11) "aes-192-ccm"
  [15]=>
  string(11) "aes-192-cfb"
  [16]=>
  string(12) "aes-192-cfb1"
  [17]=>
  string(12) "aes-192-cfb8"
  [18]=>
  string(11) "aes-192-ctr"
  [19]=>
  string(11) "aes-192-ecb"
  [20]=>
  string(11) "aes-192-gcm"
  [21]=>
  string(11) "aes-192-ocb"
  [22]=>
  string(11) "aes-192-ofb"
  [23]=>
  string(11) "aes-256-cbc"
  [24]=>
  string(21) "aes-256-cbc-hmac-sha1"
  [25]=>
  string(23) "aes-256-cbc-hmac-sha256"
  [26]=>
  string(11) "aes-256-ccm"
  [27]=>
  string(11) "aes-256-cfb"
  [28]=>
  string(12) "aes-256-cfb1"
  [29]=>
  string(12) "aes-256-cfb8"
  [30]=>
  string(11) "aes-256-ctr"
  [31]=>
  string(11) "aes-256-ecb"
  [32]=>
  string(11) "aes-256-gcm"
  [33]=>
  string(11) "aes-256-ocb"
  [34]=>
  string(11) "aes-256-ofb"
  [35]=>
  string(11) "aes-256-xts"
  [36]=>
  string(12) "aria-128-cbc"
  [37]=>
  string(12) "aria-128-ccm"
  [38]=>
  string(12) "aria-128-cfb"
  [39]=>
  string(13) "aria-128-cfb1"
  [40]=>
  string(13) "aria-128-cfb8"
  [41]=>
  string(12) "aria-128-ctr"
  [42]=>
  string(12) "aria-128-ecb"
  [43]=>
  string(12) "aria-128-gcm"
  [44]=>
  string(12) "aria-128-ofb"
  [45]=>
  string(12) "aria-192-cbc"
  [46]=>
  string(12) "aria-192-ccm"
  [47]=>
  string(12) "aria-192-cfb"
  [48]=>
  string(13) "aria-192-cfb1"
  [49]=>
  string(13) "aria-192-cfb8"
  [50]=>
  string(12) "aria-192-ctr"
  [51]=>
  string(12) "aria-192-ecb"
  [52]=>
  string(12) "aria-192-gcm"
  [53]=>
  string(12) "aria-192-ofb"
  [54]=>
  string(12) "aria-256-cbc"
  [55]=>
  string(12) "aria-256-ccm"
  [56]=>
  string(12) "aria-256-cfb"
  [57]=>
  string(13) "aria-256-cfb1"
  [58]=>
  string(13) "aria-256-cfb8"
  [59]=>
  string(12) "aria-256-ctr"
  [60]=>
  string(12) "aria-256-ecb"
  [61]=>
  string(12) "aria-256-gcm"
  [62]=>
  string(12) "aria-256-ofb"
  [63]=>
  string(6) "bf-cbc"
  [64]=>
  string(6) "bf-cfb"
  [65]=>
  string(6) "bf-ecb"
  [66]=>
  string(6) "bf-ofb"
  [67]=>
  string(16) "camellia-128-cbc"
  [68]=>
  string(16) "camellia-128-cfb"
  [69]=>
  string(17) "camellia-128-cfb1"
  [70]=>
  string(17) "camellia-128-cfb8"
  [71]=>
  string(16) "camellia-128-ctr"
  [72]=>
  string(16) "camellia-128-ecb"
  [73]=>
  string(16) "camellia-128-ofb"
  [74]=>
  string(16) "camellia-192-cbc"
  [75]=>
  string(16) "camellia-192-cfb"
  [76]=>
  string(17) "camellia-192-cfb1"
  [77]=>
  string(17) "camellia-192-cfb8"
  [78]=>
  string(16) "camellia-192-ctr"
  [79]=>
  string(16) "camellia-192-ecb"
  [80]=>
  string(16) "camellia-192-ofb"
  [81]=>
  string(16) "camellia-256-cbc"
  [82]=>
  string(16) "camellia-256-cfb"
  [83]=>
  string(17) "camellia-256-cfb1"
  [84]=>
  string(17) "camellia-256-cfb8"
  [85]=>
  string(16) "camellia-256-ctr"
  [86]=>
  string(16) "camellia-256-ecb"
  [87]=>
  string(16) "camellia-256-ofb"
  [88]=>
  string(9) "cast5-cbc"
  [89]=>
  string(9) "cast5-cfb"
  [90]=>
  string(9) "cast5-ecb"
  [91]=>
  string(9) "cast5-ofb"
  [92]=>
  string(8) "chacha20"
  [93]=>
  string(17) "chacha20-poly1305"
  [94]=>
  string(7) "des-cbc"
  [95]=>
  string(7) "des-cfb"
  [96]=>
  string(8) "des-cfb1"
  [97]=>
  string(8) "des-cfb8"
  [98]=>
  string(7) "des-ecb"
  [99]=>
  string(7) "des-ede"
  [100]=>
  string(11) "des-ede-cbc"
  [101]=>
  string(11) "des-ede-cfb"
  [102]=>
  string(11) "des-ede-ofb"
  [103]=>
  string(8) "des-ede3"
  [104]=>
  string(12) "des-ede3-cbc"
  [105]=>
  string(12) "des-ede3-cfb"
  [106]=>
  string(13) "des-ede3-cfb1"
  [107]=>
  string(13) "des-ede3-cfb8"
  [108]=>
  string(12) "des-ede3-ofb"
  [109]=>
  string(7) "des-ofb"
  [110]=>
  string(8) "desx-cbc"
  [111]=>
  string(13) "id-aes128-CCM"
  [112]=>
  string(13) "id-aes128-GCM"
  [113]=>
  string(14) "id-aes128-wrap"
  [114]=>
  string(18) "id-aes128-wrap-pad"
  [115]=>
  string(13) "id-aes192-CCM"
  [116]=>
  string(13) "id-aes192-GCM"
  [117]=>
  string(14) "id-aes192-wrap"
  [118]=>
  string(18) "id-aes192-wrap-pad"
  [119]=>
  string(13) "id-aes256-CCM"
  [120]=>
  string(13) "id-aes256-GCM"
  [121]=>
  string(14) "id-aes256-wrap"
  [122]=>
  string(18) "id-aes256-wrap-pad"
  [123]=>
  string(24) "id-smime-alg-CMS3DESwrap"
  [124]=>
  string(10) "rc2-40-cbc"
  [125]=>
  string(10) "rc2-64-cbc"
  [126]=>
  string(7) "rc2-cbc"
  [127]=>
  string(7) "rc2-cfb"
  [128]=>
  string(7) "rc2-ecb"
  [129]=>
  string(7) "rc2-ofb"
  [130]=>
  string(3) "rc4"
  [131]=>
  string(6) "rc4-40"
  [132]=>
  string(12) "rc4-hmac-md5"
  [133]=>
  string(8) "seed-cbc"
  [134]=>
  string(8) "seed-cfb"
  [135]=>
  string(8) "seed-ecb"
  [136]=>
  string(8) "seed-ofb"
  [137]=>
  string(7) "sm4-cbc"
  [138]=>
  string(7) "sm4-cfb"
  [139]=>
  string(7) "sm4-ctr"
  [140]=>
  string(7) "sm4-ecb"
  [141]=>
  string(7) "sm4-ofb"
}
```

**Comment by davrot** [comment]
Thank you for the fast reply. Well, AES-128-CFB is there at [2] and aes-128-cfb at [91]. Sorry! It would have been so easy if not. :-)

cogniumweb# /usr/local/bin/php -r "var_dump(openssl_get_cipher_methods());"
array(193) {
  [0]=>
  string(11) "AES-128-CBC"
  [1]=>
  string(21) "AES-128-CBC-HMAC-SHA1"
  [2]=>
  string(11) "AES-128-CFB"
  [3]=>
  string(12) "AES-128-CFB1"
  [4]=>
  string(12) "AES-128-CFB8"
  [5]=>
  string(11) "AES-128-CTR"
  [6]=>
  string(11) "AES-128-ECB"
  [7]=>
  string(11) "AES-128-OFB"
  [8]=>
  string(11) "AES-128-XTS"
  [9]=>
  string(11) "AES-192-CBC"
  [10]=>
  string(11) "AES-192-CFB"
  [11]=>
  string(12) "AES-192-CFB1"
  [12]=>
  string(12) "AES-192-CFB8"
  [13]=>
  string(11) "AES-192-CTR"
  [14]=>
  string(11) "AES-192-ECB"
  [15]=>
  string(11) "AES-192-OFB"
  [16]=>
  string(11) "AES-256-CBC"
  [17]=>
  string(21) "AES-256-CBC-HMAC-SHA1"
  [18]=>
  string(11) "AES-256-CFB"
  [19]=>
  string(12) "AES-256-CFB1"
  [20]=>
  string(12) "AES-256-CFB8"
  [21]=>
  string(11) "AES-256-CTR"
  [22]=>
  string(11) "AES-256-ECB"
  [23]=>
  string(11) "AES-256-OFB"
  [24]=>
  string(11) "AES-256-XTS"
  [25]=>
  string(6) "BF-CBC"
  [26]=>
  string(6) "BF-CFB"
  [27]=>
  string(6) "BF-ECB"
  [28]=>
  string(6) "BF-OFB"
  [29]=>
  string(16) "CAMELLIA-128-CBC"
  [30]=>
  string(16) "CAMELLIA-128-CFB"
  [31]=>
  string(17) "CAMELLIA-128-CFB1"
  [32]=>
  string(17) "CAMELLIA-128-CFB8"
  [33]=>
  string(16) "CAMELLIA-128-ECB"
  [34]=>
  string(16) "CAMELLIA-128-OFB"
  [35]=>
  string(16) "CAMELLIA-192-CBC"
  [36]=>
  string(16) "CAMELLIA-192-CFB"
  [37]=>
  string(17) "CAMELLIA-192-CFB1"
  [38]=>
  string(17) "CAMELLIA-192-CFB8"
  [39]=>
  string(16) "CAMELLIA-192-ECB"
  [40]=>
  string(16) "CAMELLIA-192-OFB"
  [41]=>
  string(16) "CAMELLIA-256-CBC"
  [42]=>
  string(16) "CAMELLIA-256-CFB"
  [43]=>
  string(17) "CAMELLIA-256-CFB1"
  [44]=>
  string(17) "CAMELLIA-256-CFB8"
  [45]=>
  string(16) "CAMELLIA-256-ECB"
  [46]=>
  string(16) "CAMELLIA-256-OFB"
  [47]=>
  string(9) "CAST5-CBC"
  [48]=>
  string(9) "CAST5-CFB"
  [49]=>
  string(9) "CAST5-ECB"
  [50]=>
  string(9) "CAST5-OFB"
  [51]=>
  string(6) "ChaCha"
  [52]=>
  string(7) "DES-CBC"
  [53]=>
  string(7) "DES-CFB"
  [54]=>
  string(8) "DES-CFB1"
  [55]=>
  string(8) "DES-CFB8"
  [56]=>
  string(7) "DES-ECB"
  [57]=>
  string(7) "DES-EDE"
  [58]=>
  string(11) "DES-EDE-CBC"
  [59]=>
  string(11) "DES-EDE-CFB"
  [60]=>
  string(11) "DES-EDE-OFB"
  [61]=>
  string(8) "DES-EDE3"
  [62]=>
  string(12) "DES-EDE3-CBC"
  [63]=>
  string(12) "DES-EDE3-CFB"
  [64]=>
  string(13) "DES-EDE3-CFB1"
  [65]=>
  string(13) "DES-EDE3-CFB8"
  [66]=>
  string(12) "DES-EDE3-OFB"
  [67]=>
  string(7) "DES-OFB"
  [68]=>
  string(8) "DESX-CBC"
  [69]=>
  string(13) "GOST 28147-89"
  [70]=>
  string(8) "IDEA-CBC"
  [71]=>
  string(8) "IDEA-CFB"
  [72]=>
  string(8) "IDEA-ECB"
  [73]=>
  string(8) "IDEA-OFB"
  [74]=>
  string(10) "RC2-40-CBC"
  [75]=>
  string(10) "RC2-64-CBC"
  [76]=>
  string(7) "RC2-CBC"
  [77]=>
  string(7) "RC2-CFB"
  [78]=>
  string(7) "RC2-ECB"
  [79]=>
  string(7) "RC2-OFB"
  [80]=>
  string(3) "RC4"
  [81]=>
  string(6) "RC4-40"
  [82]=>
  string(12) "RC4-HMAC-MD5"
  [83]=>
  string(7) "SM4-CBC"
  [84]=>
  string(7) "SM4-CFB"
  [85]=>
  string(7) "SM4-CTR"
  [86]=>
  string(7) "SM4-ECB"
  [87]=>
  string(7) "SM4-OFB"
  [88]=>
  string(11) "aes-128-cbc"
  [89]=>
  string(21) "aes-128-cbc-hmac-sha1"
  [90]=>
  string(11) "aes-128-ccm"
  [91]=>
  string(11) "aes-128-cfb"
  [92]=>
  string(12) "aes-128-cfb1"
  [93]=>
  string(12) "aes-128-cfb8"
  [94]=>
  string(11) "aes-128-ctr"
  [95]=>
  string(11) "aes-128-ecb"
  [96]=>
  string(11) "aes-128-gcm"
  [97]=>
  string(11) "aes-128-ofb"
  [98]=>
  string(11) "aes-128-xts"
  [99]=>
  string(11) "aes-192-cbc"
  [100]=>
  string(11) "aes-192-ccm"
  [101]=>
  string(11) "aes-192-cfb"
  [102]=>
  string(12) "aes-192-cfb1"
  [103]=>
  string(12) "aes-192-cfb8"
  [104]=>
  string(11) "aes-192-ctr"
  [105]=>
  string(11) "aes-192-ecb"
  [106]=>
  string(11) "aes-192-gcm"
  [107]=>
  string(11) "aes-192-ofb"
  [108]=>
  string(11) "aes-256-cbc"
  [109]=>
  string(21) "aes-256-cbc-hmac-sha1"
  [110]=>
  string(11) "aes-256-ccm"
  [111]=>
  string(11) "aes-256-cfb"
  [112]=>
  string(12) "aes-256-cfb1"
  [113]=>
  string(12) "aes-256-cfb8"
  [114]=>
  string(11) "aes-256-ctr"
  [115]=>
  string(11) "aes-256-ecb"
  [116]=>
  string(11) "aes-256-gcm"
  [117]=>
  string(11) "aes-256-ofb"
  [118]=>
  string(11) "aes-256-xts"
  [119]=>
  string(6) "bf-cbc"
  [120]=>
  string(6) "bf-cfb"
  [121]=>
  string(6) "bf-ecb"
  [122]=>
  string(6) "bf-ofb"
  [123]=>
  string(16) "camellia-128-cbc"
  [124]=>
  string(16) "camellia-128-cfb"
  [125]=>
  string(17) "camellia-128-cfb1"
  [126]=>
  string(17) "camellia-128-cfb8"
  [127]=>
  string(16) "camellia-128-ecb"
  [128]=>
  string(16) "camellia-128-ofb"
  [129]=>
  string(16) "camellia-192-cbc"
  [130]=>
  string(16) "camellia-192-cfb"
  [131]=>
  string(17) "camellia-192-cfb1"
  [132]=>
  string(17) "camellia-192-cfb8"
  [133]=>
  string(16) "camellia-192-ecb"
  [134]=>
  string(16) "camellia-192-ofb"
  [135]=>
  string(16) "camellia-256-cbc"
  [136]=>
  string(16) "camellia-256-cfb"
  [137]=>
  string(17) "camellia-256-cfb1"
  [138]=>
  string(17) "camellia-256-cfb8"
  [139]=>
  string(16) "camellia-256-ecb"
  [140]=>
  string(16) "camellia-256-ofb"
  [141]=>
  string(9) "cast5-cbc"
  [142]=>
  string(9) "cast5-cfb"
  [143]=>
  string(9) "cast5-ecb"
  [144]=>
  string(9) "cast5-ofb"
  [145]=>
  string(6) "chacha"
  [146]=>
  string(7) "des-cbc"
  [147]=>
  string(7) "des-cfb"
  [148]=>
  string(8) "des-cfb1"
  [149]=>
  string(8) "des-cfb8"
  [150]=>
  string(7) "des-ecb"
  [151]=>
  string(7) "des-ede"
  [152]=>
  string(11) "des-ede-cbc"
  [153]=>
  string(11) "des-ede-cfb"
  [154]=>
  string(11) "des-ede-ofb"
  [155]=>
  string(8) "des-ede3"
  [156]=>
  string(12) "des-ede3-cbc"
  [157]=>
  string(12) "des-ede3-cfb"
  [158]=>
  string(13) "des-ede3-cfb1"
  [159]=>
  string(13) "des-ede3-cfb8"
  [160]=>
  string(12) "des-ede3-ofb"
  [161]=>
  string(7) "des-ofb"
  [162]=>
  string(8) "desx-cbc"
  [163]=>
  string(6) "gost89"
  [164]=>
  string(10) "gost89-cnt"
  [165]=>
  string(10) "gost89-ecb"
  [166]=>
  string(13) "id-aes128-CCM"
  [167]=>
  string(13) "id-aes128-GCM"
  [168]=>
  string(14) "id-aes128-wrap"
  [169]=>
  string(13) "id-aes192-CCM"
  [170]=>
  string(13) "id-aes192-GCM"
  [171]=>
  string(14) "id-aes192-wrap"
  [172]=>
  string(13) "id-aes256-CCM"
  [173]=>
  string(13) "id-aes256-GCM"
  [174]=>
  string(14) "id-aes256-wrap"
  [175]=>
  string(8) "idea-cbc"
  [176]=>
  string(8) "idea-cfb"
  [177]=>
  string(8) "idea-ecb"
  [178]=>
  string(8) "idea-ofb"
  [179]=>
  string(10) "rc2-40-cbc"
  [180]=>
  string(10) "rc2-64-cbc"
  [181]=>
  string(7) "rc2-cbc"
  [182]=>
  string(7) "rc2-cfb"
  [183]=>
  string(7) "rc2-ecb"
  [184]=>
  string(7) "rc2-ofb"
  [185]=>
  string(3) "rc4"
  [186]=>
  string(6) "rc4-40"
  [187]=>
  string(12) "rc4-hmac-md5"
  [188]=>
  string(7) "sm4-cbc"
  [189]=>
  string(7) "sm4-cfb"
  [190]=>
  string(7) "sm4-ctr"
  [191]=>
  string(7) "sm4-ecb"
  [192]=>
  string(7) "sm4-ofb"
}

**Comment by SergeyMosin** [comment]
This is strange indeed, but sometime PHP **CLI** config might be different form PHP **Server** config. I have added more logging to activation flow here https://github.com/SergeyMosin/Appointments/blob/master/lib/Migration/InstallHook.php#L53-L56 If you try again can you post error the logs. Thanks.
