### ISSUE TITLE
External (Google) calendar not checked for conflicts

### ISSUE THREAD

**Issue by marvicz** [SergeyMosin/Appointments#275]
I have linked Google calendar to the Nextcloud calendar app and I can see the events. In the Appointments app, I checked this Google calendar in the "Check for conflicts" tab. Also tried to set the Subscription Sync interval to "Every hour". Neither the "Nextcloud Only Sync" nor "Every hour" option helped. Time slots are offered over this Google calendar events.

**Comment by SergeyMosin** [comment]
@marvicz Can you please send me your settings dump, `Settings > Advanced Settings > Debugging > Settings Dump` to ( sergey [at] srgdev.com ) so I can try to reproduce this.

**Comment by SergeyMosin** [comment]
@marvicz Thanks for the "settings dump", but I can not reproduce this. However v1.11.9 has a new `Get raw calendar data` option in debugging section, which outputs info similar to the sample below. When you get a chance can you send me debug info for your remote (google) calendar.

Sample debug info:
```
array (
  'name' => 'ncalendar.google.com',
  'id' => '7186d3f2',
  'isReadOnly' => '1',
  'isSubscription' => '1',
)

array (
  'cal' => 
  array (
    'id' => '1',
    'type' => 1,
  ),
  'range' => 
  array (
    'start' => '20211230T134315Z',
    'end' => '20220121T134315Z',
  ),
  'urls' => 
  array (
    0 => 'ad4b1589-0118-4344-b8d2-0d0928f8595a.ics',
  ),
  'events' => 
  array (
    0 => 'BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.3.5//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTART:20220105T160000Z
DTEND:20220105T170000Z
DTSTAMP:20211231T134205Z
UID:4sgbqcgeiisos0pi8v8aqa97j5@google.com
CREATED:20211230T141257Z
DESCRIPTION:
LAST-MODIFIED:20211230T141257Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:ttttttt
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
',
  ),
)

```

![image](https://user-images.githubusercontent.com/10747559/147826582-f0980bbb-27ec-44b7-ab24-8e69bc1fc9d4.png)

**Comment by SergeyMosin** [comment]
@marvicz Thanks for raw data, but there is nothing unusual there, except maybe for a possible 1 hour time shift because of time zone mismatch. 
Also v1.11.10 has a new `Log remote blockers` option in Debugging Settings. When it is enabled Appointments App should log something similar to the screenshot bellow and it might help with further debugging...  

![image](https://user-images.githubusercontent.com/10747559/147891133-657cec7c-a772-4be1-9b8c-04adc0bd731d.png)

**Comment by SergeyMosin** [comment]
A `Sync Remote Calendar Now` option is also available in the `Debugging` section and if that does not help I am really out of ideas why this might be happening.
