### ISSUE TITLE
Available Slots Not Showing Up

### ISSUE THREAD

**Issue by Tealk** [SergeyMosin/Appointments#277]
Hello,

when I create an appointment in the calendar and select a specific calendar, I don't get any open slots displayed.

**Comment by SergeyMosin** [comment]
Is there a `data-state: x` line in browser console (F12). Can you please send me your settings dump `Settings > Advanced Settings > Debugging > Settings Dump` to sergey [at] srgdev.com so I can try to replicate this on my machine

**Comment by Tealk** [comment]
> Is there a `data-state: x` line in browser console (F12). 

On which page should I look in the console? At the calendar or at the preview for the appointment selection?

> Can you please send me your settings dump `Settings > Advanced Settings > Debugging > Settings Dump` to sergey [at] srgdev.com so I can try to replicate this on my machine

done

**Comment by SergeyMosin** [comment]
@Tealk Sorry this is NC Appointments **App** which is different from the **NC Calendar App Appointments Feature** shown in your screenshot. Some more info about Appointments App vs Calendar App Appointments Feature is here: https://github.com/SergeyMosin/Appointments/issues/270 Your question would need to go here: https://github.com/nextcloud/calendar/issues
