### ISSUE TITLE
bug: email typo while booking makes the time slot unusable (event can't get deleted or changed to available)

### ISSUE THREAD

**Issue by herrselent** [SergeyMosin/Appointments#279]
Hi there Sergey, I encountered a problem using your appointments app in Nextcloud. We're running Nextcloud as a school. We're realizing ressource booking with your app by using a weekly template for our staff for them to be able to reserve any of our hardware tools that they can borrow for their lessons.

Now we wanted to add a feature so that parents of future students of our school can book an appointment to bring in their registration documents (due to Covid restrictions) during one particular week (that's why we went for "simple mode"). I managed to create the booking slots and booking the time slots is working fine as long as email addresses are typed in correctly. Btw. we set the appointment tool in the way that they have to book the appointment and approve it through their email. So they receive an email being asked to approve the appointment.

→ Now if clients / parents type in their email address incorrectly in the booking form, the booking inquiry will never be delivered hence the time slot can't get approved. Sadly if the email address isn't correct or doesn't exist the time slot gets instant approval. The calendar entries only shows "approved". Unfortunately the approved time slot can't be changed or deleted through the connected calendar in Nextcloud. There's also no way to delete the appointment time slot anywhere. What can we do?

**Comment by SergeyMosin** [comment]
> Sadly if the email address isn't correct or doesn't exist the time slot gets instant approval.

Unless you select `Skip email validation step` in email settings this should not be possible.

![image](https://user-images.githubusercontent.com/10747559/148993912-fa758c22-c169-4699-89fa-8210145a8dba.png)

>time slot gets instant approval

If appointment title starts with ⌛ it means that the appointment has not been approved through email.

![image](https://user-images.githubusercontent.com/10747559/148995784-fcc3050a-ad20-48f1-a003-e770158fd1db.png)

> Unfortunately the approved time slot can't be changed or deleted through the connected calendar in Nextcloud. There's also no way to delete the appointment time slot anywhere. 

User who has setup the appointments (you) must have write access to the calendar and therefore can delete any event/appointment in the NC Calendar App. 

> What can we do?

If you can add appointments you must be able to delete them in NC Calendar App

![image](https://user-images.githubusercontent.com/10747559/148995187-7d9c98e2-1c60-4f0c-8507-10852006a1e6.png)

Just in-case I am missing something, can you please send me your settings dump, Settings > Advanced Settings > Debugging > Settings Dump to  sergey [at] srgdev.com

**Comment by herrselent** [comment]
Sadly I don't get to see the gray-coloured dotted button providing a dropdown menu to choose from delete or download. All I can get is a button that gives me the only option of downloading the calender appointment:

![image](https://user-images.githubusercontent.com/17471811/148998209-c6ccda47-6988-4a01-adab-ed36df8bc837.png)

**Comment by SergeyMosin** [comment]
This very strange...
verfügbar (available) indicates that this appointment has only been created and not booked by anyone yet, which is also indicated by vorläufig (tentative) status.

1. How is this calendar shared ?
2. Who owns this calendar ?
3. What is the version of Calendar App ?

I can only reproduce this when a calendar is shared in READ ONLY mode. For example below DemoUser shares calendar with Admin22 user in read only mode.

DemoUser user view (can edit/delete)
![image](https://user-images.githubusercontent.com/10747559/149005677-6463c019-7b34-412d-8743-266f885fd1ad.png)

Admin22 user view (can NOT edit/delete)
![image](https://user-images.githubusercontent.com/10747559/149005272-f84e75aa-9ad7-4ba2-b0e4-5fcef42ded74.png)

**Comment by herrselent** [comment]
What I can tell you:

- editing the appointments template in „simple mode“ created  all the time slots in the connected calendar saying „vorläufig“ (tentative)

- version of Calendar app is 3.0.4



- calendar of owner „termine“ was shared with 3 other users within the same group of which 2 users in READ ONLY and 1 user in READ/WRITE mode

- user in READ/WRITE mode had edited events on his iPadOS 15 calendar client


Might there be compatibility issues between nextcloud calendar and the iOS calendar client?

**Comment by SergeyMosin** [comment]
After digging deeper I found two more ways to replicate a situation where a owner of a calendar can not edit or delete events(appointments) in his/her own calendar. Both are related to event `ORGANIZER` field mismatch to the calendar owner in Calendar App ( more info: https://github.com/nextcloud/calendar/issues/3866#issuecomment-1007449287 )

Lets assume we have the flowing:
- A shared **Calendar**
- **Owner**: a user who owns the calendar
- **Editor**: a user to whom the owner granted write access for the calendar
- When the Owner or the Editor create an event in the calendar the put themselves as the _Organizer_ in the _Attendees Section_ (this is how Simple Mode appointment time slots are created).

![image](https://user-images.githubusercontent.com/10747559/149038882-520693f1-52b3-47b6-97a1-df595bf7aaf1.png)

**Use Case 1:**

When the Owner creates some events and then changes email address in NC setting all events that use old email address in `ORGANIZER` field will become READ-ONLY

**Use Case 2:**

The Editor creates some events in the calendar (the Editor is the `ORGANIZER`) in this case the Owner is not able to edit/delete events created by the Editor

**Use Case 2a:**
The Owner revokes write access from the Editor and now NO ONE can edit/delete events created by the Editor in "Use Case 2"

Possible Use Case 3 (from here: https://github.com/SergeyMosin/Appointments/issues/279#issuecomment-1010384288 )
> user in READ/WRITE mode had edited events on his iPadOS 15 calendar client
>Might there be compatibility issues between nextcloud calendar and the iOS calendar client?

I don't have a way of testing it but it is possible that some calendar clients can change event ORGANIZER in away that it does not match calendar owner.

---

@herrselent 

> What can we do?

I would check who the organizer is and then grant read/write access to that user so they can delete/edit the time slots. If that is not possible please file a bug in NC Calendar App repo.

Thanks

**Comment by herrselent** [comment]
Dear Sergey,

through deeper testing I found that

→ time slots created in the appointments app through the editing-function found with the "simple mode“ can’t be edited neither by organizer nor editor in the calendar app in Nextcloud or any other client. I can however delete the time slot in my iOS calendar client being the editor (I guess also the organizer) but I have no chance deleting it in the Nextcloud web-interface within the calendar app





→ I can create, edit or delete time slots that are manually set up in the Nextcloud calendar app or in the iOS calendar client.

Sadly none of your use cases are applicable to what we are doing.

Let me reformualte what we are doing:

1) Organizer „termine“ creates appointments through the appointment app in simple mode using the editor (see attached picture, black circle) within the app.
2) Time slots can be booked by people → they have to approve their appointment
3) No editing of these time slots is possible whatsoever in Nextcloud except deleting through the editor (see attached picture, green circle) in the appointments app (only deleting old appointments) which is a very long way round and doesn’t help with the following:

- user typed in wrong email address so he/she can’t approve/disprove the appointment, neither can we but have to manually delete the time slot with an iOS device that has read/write access



Kind regards 

Ben

**Comment by SergeyMosin** [comment]
Just  to iterate if `Email` in the `User/Organization` section is different of that of calendar owner or a user with write access, appointment time slots not be editable/delete-able by the user in NC Calendar App but other calendar clients are are able to delete/edit them. I think this change was made in calendar v3.0.4 or one version earlier.

![image](https://user-images.githubusercontent.com/10747559/149144435-6b2217ad-d3d9-4fcc-98e3-8020c4f3beb2.png)

As a temporary solution I can add a warning or disable "Add time slots" functionality for users whose email does not match the one in Appointment settings until the Calendar App is fixed.

**Comment by SergeyMosin** [comment]
fixed in calendar v3.0.5
