### ISSUE TITLE
appointments made become locked

### ISSUE THREAD

**Issue by Roderique76** [SergeyMosin/Appointments#281]
Hello,

Currently appointments made are locked in my Nextcloud calendar. This behaviour is new and undesirable. 
Previously we would let people make an appointment with the planner, appointments would show up in our Nextcloud calendar, and we would manually assign available colleagues to the appointment and add extra info (like a ticket link) to the appointment. This way all info was present. 
Now an appointment shows up locked and isn't editable at all, we can only change the name or move it to a different day.  Any pointers on why this is happening would be appreciated.

Nextcloud version 21.0.7
Appointments version unknown (I don't know if it auto-updates)

**Comment by SergeyMosin** [comment]
This is a bug in the Calendar App. Please see this thread #279 here this one in the calendar app repo https://github.com/nextcloud/calendar/issues/3866#issuecomment-1007449287. I think maintainers of the Calendar App are working on it and a fix should be available some time this week.

**Comment by st3iny** [comment]
The release just went live. The fix is included in Calendar v3.0.5.
