### ISSUE TITLE
Timeslot shows free and can be booked although it´s not free

### ISSUE THREAD

**Issue by tmoeri** [SergeyMosin/Appointments#282]
I noticed a buggy (?) behavior if a have a double booking in my calendar. The appointment app let me select a timeslot although it´s not free:
![image](https://user-images.githubusercontent.com/97988110/150016626-e140cd4b-0105-44e5-aaa0-f6dda4a601a1.png)

I’m using the weekly template. 
The example above is created with a new calendar – the events are created with the Calendar app of nextcloud. 
Nextcloud version 23.0.0
Appointment version 1.11.10

**Comment by SergeyMosin** [comment]
Can you please send me your settings dump `Settings > Advanced Settings > Debugging > Settings Dump`  and an `.ics` file for `b1` or `b2` event ( .ics file download instructions are here: https://github.com/SergeyMosin/Appointments/issues/255#issuecomment-970587216 ) to sergey [at] srgdev.com so I can replicate this on my machine

**Comment by SergeyMosin** [comment]
fixed in v1.11.11

**Comment by tmoeri** [comment]
@SergeyMosin 👍  Many thanks for the quick bug fix. It's working fine now!
Great app!
