### ISSUE TITLE
Wholeday Calendar entries are not recognized when created by MacOS Calendar App

### ISSUE THREAD

**Issue by stefkos** [SergeyMosin/Appointments#284]
First, I would like to thank you for your time an effort to build this fantastic Application!

Anyway, I'm experiencing a problem when creating whole day calendar entries. If I create a whole day entry I would expect that booking an appointment an that specific day is not possible. This is actually the case when I create a whole day entry using nextcloud calendar. But If I create this entry using MacOS calendar App or IOS calendar app the event gets sync correctly to nextcloud calendar but I'm able to booking appointments on that day.

Could you please check that?

**Comment by SergeyMosin** [comment]
Can you make sure that `Include all day events in conflict check` is enabled in `Advanced Settings` if that does not help can you send me the .ics file for the event created via MacOS/IOS to sergey [at] srgdev.com ( .ics file download instructions are here: https://github.com/SergeyMosin/Appointments/issues/255#issuecomment-970587216 )

![image](https://user-images.githubusercontent.com/10747559/150350496-58961bfb-91c7-4cfd-ad79-3fdc88a60c49.png)

**Comment by SergeyMosin** [comment]
@stefkos Thanks for the debug data.
I see what is happening. It is related to Free/Busy settings and Apple Calendar vs NC defaults.

Your MacOS/IOS event has the `TRANSP` property set as follows:
```
...
BEGIN:VEVENT
TRANSP:TRANSPARENT
...
```

And according to specs: https://www.kanzaki.com/docs/ical/transp.html it should NOT block in Free/Busy search.
```
transvalue = "OPAQUE"      ;Blocks or opaque on busy time searches.
             "TRANSPARENT" ;Transparent on busy time searches.
                           ;Default value is OPAQUE
```
Nextcloud calls this Free/Busy and it can be changed in event properties. I do not have Apple Calendar to verify but other user have reported that the option to change/set this has been removed from Apple Calendar a little while ago and now `TRANSP` defaults to `TRANSPARENT`

![image](https://user-images.githubusercontent.com/10747559/150370501-e2143d8c-c228-4f77-9a35-a1c037b8129b.png)

Currently there is no good automated solution to deal with this. Maybe something like `Allow Free/Transparent events to block` option can be added but it could potentially add more problems than it would solve.

**Comment by stefkos** [comment]
You saved my day:-). This option is hidden, but still available... Once I set it the all day event to "busy" I could make appointments. So consider this issue as solved.

Thanks again and keep up your good work!

**Comment by stefkos** [comment]
I ment couldn't of course;-)

**Comment by nolens** [comment]
> his option is hidden, but still available... Once I set it the all day event to "busy" I could make appointments. 

Just want do clarify where to find this option in MacOS calendar app 
(thanks @stefkos for pointing this out! ): 

![Bildschirmfoto 2022-01-28 um 09 39 45](https://user-images.githubusercontent.com/21305551/151514842-c30d1b27-aeee-4bba-914d-8ef5297cb5e3.png)

@stefkos 
I guess you can close this issue now ;=)
