### ISSUE TITLE
My days beginning before 8am

### ISSUE THREAD

**Issue by Alternativend** [SergeyMosin/Appointments#285]
Hi there,
i would like to accept appointments before 08:00AM and after 9:45PM. 

How to change these hours?

**Comment by SergeyMosin** [comment]
Currently this is only possible in `External Mode` , you would use one (hidden) Calendar as a template(source) and another as the destination for booked appointments. You can use NC Calendar App to create available events/time-slots in the source calendar and set any date time and recurrence pattern. There is more info in the Help/Tutorial section, and here: https://github.com/SergeyMosin/Appointments/issues/250
