### ISSUE TITLE
Datepicker: Days with no available appointments should be greyed out

### ISSUE THREAD

**Issue by pymnh** [SergeyMosin/Appointments#288]
Currently it is possible to choose a date where there is no appointments available, this is very confusing. 
When I was using the appointment form for the first time, the UI indicated that "No timeslot is available" but it took me some time to realize that there might be free appointments at another date, and that "no timeslots available" refers to the specific date that is picked.
This is also because the date, when opening the form, is automatically set to the current day, even if there is no appointments available today. 

![grafik](https://user-images.githubusercontent.com/80954461/152325228-ad35d9b9-eed1-4613-b1e6-1c532644cfaa.png)

IMO it should not be possible to pick a date where there are no free timeslots:
1. days in the datepicker with no available appointments should be greyed out
2. the default date when opening the form should point to the earliest day where there will be a appointments available, __or__ to none at all. 

I believe this would improve the usability a lot

**Comment by SergeyMosin** [comment]
I think you are referring to NC Calendar App Appointments functionality, which is different from NC Appointments App (this repo). More info here: https://github.com/SergeyMosin/Appointments/issues/270#issuecomment-986075781 . You probably want to file this issue in NC Calendar App repo: https://github.com/nextcloud/calendar

**Comment by pymnh** [comment]
you are right, sorry for the noise!
