### ISSUE TITLE
Sunday and 24 hours in the weekly template

### ISSUE THREAD

**Issue by hurgelwurz666** [SergeyMosin/Appointments#290]
Hello, 
thank you for the nice app!
It would help a lot if you could include Sunday in the "weekly template". In addition, it should also be possible to assign times outside of 8:00-21:45 as appointments.
I know Sunday and 24/7 are available in the "external template". However, for my use case, I need the ability to provide different durations to choose from. So far this is only possible in the "weekly template".

**Comment by SergeyMosin** [comment]
Sunday is available in v1.12.0

**Comment by SergeyMosin** [comment]
Discussion about "_times outside of 8:00-21:45 as appointments"_ is located in #250 
Closing.
