### ISSUE TITLE
Remove checkbox for GDPR compliance

### ISSUE THREAD

**Issue by absynth47215** [SergeyMosin/Appointments#292]
Currently, if you add a label to the GDPR form field, the checkbox is automatically (and hard coded) available. However, there's no hard requirement in GDPR to actually mandate this checkbox. You merely have to make the privacy policy available to the user, and you have to prove that it was made available at the point of interaction. 
Can you make it configurable so that the <label> still exists but the checkbox doesn't?

**Comment by SergeyMosin** [comment]
`GDPR text only (no checkbox)` options is available in v1.11.14

![image](https://user-images.githubusercontent.com/10747559/153894296-2427400b-4021-4b06-88e7-48a68a54ef4d.png)

**Comment by absynth47215** [comment]
Thanks, much appreciated!
