### ISSUE TITLE
Error: Call to a member function addAllowedFrameDomain() on null

### ISSUE THREAD

**Issue by tombou** [SergeyMosin/Appointments#30]
Hi,

I'm trying to install the app into my installation. So far, I've tried in Nextcloud 15.14 and 16.09 and I'm getting the error below. The calendar works well and everything else works well also. I've installed 1.15 and updated to 1.16. Thanks!

[index] Error: Error: Call to a member function addAllowedFrameDomain() on null at <<closure>>

0. /nextcloudpath/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Appointments\Controller\PageController->index()
1. /nextcloudpath/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Appointments ... {}, "index")
2. /nextcloudpath/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Appointments ... {}, "index")
3. /nextcloudpath/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Appointmen ... r", "index", OC\AppFramework\ ... {}, {_route: "appointments.page.index"})
4. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "appointments.page.index"})
5. /nextcloudpath/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "appointments.page.index"})
6. nextcloudpath/lib/base.php line 972
   OC\Route\Router->match("/apps/appointments/")
7. /nextcloudpath/index.php line 42
   OC::handleRequest()

GET /apps/appointments/
from xx by admin at 2020-03-16T19:33:50+00:00

**Comment by SergeyMosin** [comment]
The fix will be available in the next release

Thanks for reporting.

**Comment by ingoha** [comment]
Manually patched my installation and confirming that it works - thanks :-)

**Comment by tombou** [comment]
Good idea, just manually patch mine and it works. Thanks!
