### ISSUE TITLE
Booking all day clash detection not working

### ISSUE THREAD

**Issue by rightsaidfred99** [SergeyMosin/Appointments#301]
I'm not sure if it's a limitation with all the nextcloud calendars, but it seems on my end that clash detection doesn't work on all day events when using multiple calendars. 

I've the "all day event clash detection" enabled. However testing it out, I'm still able to make appointments for that day. 

Can expand on this further if it's not reproducible.

**Comment by SergeyMosin** [comment]
Can you please send me(sergey [at] srgdev.com) the text from the settings dump `Settings > Advanced Settings > Debugging > Settings Dump` so I can try to reproduce it.

**Comment by SergeyMosin** [comment]
And the .ics for the "All day event" if you can. Thanks.

**Comment by rightsaidfred99** [comment]
I can't send through the ics unfortunately. 

I can see this issue happens when there are multiple calendars loaded though. It seems all day clash detection isn't working for me on the secondary calendar. 

I will have a look at the settings dump to post.
