### ISSUE TITLE
Timeslot keep booked after cancel Appointments since 1.11.14

### ISSUE THREAD

**Issue by vampsm** [SergeyMosin/Appointments#302]
Hello,

when i cancel an Appointments, keep the Appointments Termin at the Booking Calendar!?

**Comment by SergeyMosin** [comment]
What is your setting for "Wenn ein Teilnehmer absagt" and what "mode" are you using ?

![image](https://user-images.githubusercontent.com/10747559/154970181-a0ba3681-865f-4362-842a-7ffb65cdedea.png)

If possible, can you please send me(sergey [at] srgdev.com) the the settings dump `Settings > Advanced Settings > Debugging > Settings Dump` so I can try to reproduce it.

**Comment by SergeyMosin** [comment]
@vampsm Thank you very much for detail debug info.

Confirmed in "Simple" mode when a different destination calendar is used. Reminders might be effected as well with the same setup. 

Will be fixed in next release.

**Comment by SergeyMosin** [comment]
fixed in v1.12.0

**Comment by vampsm** [comment]
WOW Thank You
