### ISSUE TITLE
Using an external calDAV calendar

### ISSUE THREAD

**Issue by Taxicletter** [SergeyMosin/Appointments#303]
Hi,
I'm configuring the appointment-app and it looks like a very useful and user-friendly tool. I would like to use it with an external calDAV calendar, if possible. The manual says "External mode - Use Nextcloud's Calendar App or any other CalDAV compatible client to add "available" timeslots.", but I don't find how to use an external calendar.
I was also wondering if you can combine the weekly schedule with an external calendar.

If I overlooked the info, I'm sorry, just put me to the right webpage in that case ;-)

Thank you!

**Comment by Jaxom99** [comment]
I think you must add the calendar to Nextcloud first, as a CalDAV subscription. Then it should be available in the list of calendars in the app, when you choose "external mode".

**Comment by Taxicletter** [comment]
Thank you Jaxom99. I thought so too, but I also don't find how to ad the calendar there :-).
I'll post my question there as well (after searching again before doing so).

**Comment by Jaxom99** [comment]
When adding a new calendar via the web interface , you have 3 options (in NC22 at least) : classic, with tasks, "from link (read only)". The third one is your goal ;)

**Comment by Taxicletter** [comment]
Yes!
I'm searching for the correct server-link for my Fruux calDAV. I think I have to add a device in my free account, so I have to delete another.

**Comment by SergeyMosin** [comment]
If you can add events(appointments) to NC Calendar App via an external CalDAV client then the Appointments App will be able to use then, but if you are having a problem adding events to NC calendar, https://github.com/nextcloud/calendar is the better place to ask for help.


>I was also wondering if you can combine the weekly schedule with an external calendar.

All calendars that are available in NC Calendar App (including external/subscriptions with some restrictions) can be used for `Conflict Check` in "Weekly Template" mode.
