### ISSUE TITLE
[Bug] An Error occurred - Appointments cannot be booked

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#304]
Hello @SergeyMosin,

with latest version, customers cannot book apointments. 

- appointments are visible and can be chosen
- form can be filled
- after sending form, system displays "an error occurred, please contact  [my email-adress]

System: 
- nextcloud 23.02
- latest appointments app
- external mode with apple calendar

How can I send you more relevant information?

Best
Tom

**Comment by SergeyMosin** [comment]
Thanks for the info. Bug related to `Skip email validation step` is confirmed. A fix will be released ASAP.

**Comment by sutidor** [comment]
```
[appointments] Error: getCalendarTimezone fallback to getUserTimezone: Calendar with ID 999 for user xyz missing 'timezone' prop

GET /index.php/apps/appointments/pub/Hcd3cr4ldqdEBv2YgXn0vo001/form
from 2.204.95.21 at 2022-02-28T16:57:41+00:00
```

same error. Nextcloud shows log:

**Comment by SergeyMosin** [comment]
Fixed in v1.12.1
I just published it to NC Store so it should be available in about 20-30 min in the `Apps` section.

**Comment by sbolay** [comment]
Hello Sergey,

I confirm that the bug is fixed!
Thank you very much for the quick reaction and for this app in general!

Best regards,
Sylvain

**Comment by nolens** [comment]
Thanks, issue is solved!
