### ISSUE TITLE
[Feature request] Send appointment confirmation to an external calendar

### ISSUE THREAD

**Issue by korozif** [SergeyMosin/Appointments#305]
Thanks again for Appointments! 
It's a great plugin for Nextcloud and I'm happy to use it on a daily usage. 

In my current situation, Appointments looks in two different external calendars to see if I'm free to take an appointment with a customer.
When an appointment get confirmed by the customer, the slot is only reserved in Nextcloud and not updated in my external calendars.

Do you think it's possible to extend the appointment invitation to external platforms? I think it would be a nice improvement to the application :-)

Thanks for your attention
Vincent

**Comment by SergeyMosin** [comment]
As of v1.12.5 a rudimentary extension system is available for notifications, more info: https://github.com/SergeyMosin/Appointments/issues/26#issuecomment-1135863648 . However, you would still need the code to interact with external calendars providers/platforms APIs.
