### ISSUE TITLE
[ ? ] Empty days 

### ISSUE THREAD

**Issue by q-ki** [SergeyMosin/Appointments#306]
latest app-version / NC 22.2.0

Hey Sergey.

Thanks for this awesome app! 

One question in relation to the function "show empty days" ...

I would assume that, if I uncheck this function, only the days with appointments would show up in the booking calendar. 
But it shows always a whole week with all days visible, even that with no appointments. 
I can see no difference/effect with this box checked/unchecked. 
This is the same with all three calendar-methods (external, simple, weekly).

Thanks for your support ... 
qki

**Comment by SergeyMosin** [comment]
I can not reproduce this.

`Show Empty Days` is set:

![image](https://user-images.githubusercontent.com/10747559/157253030-096261a5-01e8-40b9-b4a5-0166629f2844.png)

----

`Show Empty Days` is NOT set:
 
![image](https://user-images.githubusercontent.com/10747559/157253288-fe9e2812-9ee7-4090-aac0-33a1f729551c.png)

----

However there are `trailing "empty"` days that are displayed when for example 7 days of appointments do not fit into two pages of "5 day slots"...

![image](https://user-images.githubusercontent.com/10747559/157254950-66ea17e2-48dc-4497-a777-78d49529d626.png)

I think we can change the message to something like `No Data Available` or remove the `trailing "empty"` days

**Comment by q-ki** [comment]
Thanks for the detailed description. I thin I was encountering the last version, while thinking ALL empty day are definetly gone.

Cheers ...
qki
