### ISSUE TITLE
[Feature] Different Talk Settings for each site 

### ISSUE THREAD

**Issue by q-ki** [SergeyMosin/Appointments#307]
Hey Sergey.

It is possible to choose different settings for each site.
But if I get it right the talks settings cannot be set seperatly for each site.

This would be nice. So for one type of booking a invitation for talk would be sent and for another not.

Thanks a lot ...
qki

**Comment by SergeyMosin** [comment]
Yes, some settings are only configurable on user level and there are no immediate plans for making all settings available per page. Closing this, but discussion can continue in #232

**Comment by q-ki** [comment]
Ok... thanks.
