### ISSUE TITLE
select multiple dates

### ISSUE THREAD

**Issue by Tealk** [SergeyMosin/Appointments#309]
Hello,

currently you can only select a predefined time, but this may not be very practical
e.g.: if you have 30 minute times to choose from but you know you need 1.5h for clarification, it would be great if you could choose 3x30 minutes.

**Comment by SergeyMosin** [comment]
Selecting multiple slots is not possible, but you can make your time slots as large as you want (up to 8 hours).

Also, I am not sure if buffers(blockers) would work for this use case but this option is available as of v1.12.2, more info https://github.com/SergeyMosin/Appointments/issues/163#issuecomment-1064219303
