### ISSUE TITLE
Button "copy public link" does not work

### ISSUE THREAD

**Issue by ingoha** [SergeyMosin/Appointments#31]
What should this button do? Copy the public link to the clipboard? Is there any other way to construct the public link?

**Comment by ingoha** [comment]
This appears in the dev console when I click the link:
![Bildschirmfoto vom 2020-03-17 19-37-50](https://user-images.githubusercontent.com/4852519/76890012-dcf26180-6886-11ea-941a-208071d84e12.png)

**Comment by ingoha** [comment]
The cause seems to be (from the server log):
url":"\/apps\/appointments\/state","message":{"Exception":"Error","Message":"Call to undefined method OC\\App\\AppManager::getAppWebPath()

**Comment by SergeyMosin** [comment]
I see thanks,
What's you NC version btw?

**Comment by ingoha** [comment]
16.0.7

**Comment by ingoha** [comment]
I succeeded to get the url by patching PageController.php (q&d):
327,329c327,328
<             $u=$s->getURLGenerator()->getBaseUrl()
<                       //.$s->getAppManager()->getAppWebPath($this->appName).'/'
<                       .'/apps/appointments/'
---
>             $u=$s->getURLGenerator()->getBaseUrl().'/index.php'
>             .$s->getAppManager()->getAppWebPath($this->appName).'/'
811,813c810,811
<         $btn_url= $s->getURLGenerator()->getBaseUrl()
<                       //.$s->getAppManager()->getAppWebPath($this->appName).'/'
<                       .'/apps/appointments/'
---
>         $btn_url= $s->getURLGenerator()->getBaseUrl().'/index.php'
>             .$s->getAppManager()->getAppWebPath($this->appName).'/'

**Comment by ingoha** [comment]
The form shows up but the form action url is broken (it just points to /index.php). Should your app be compatible to NC 16 anyhow?

**Comment by SergeyMosin** [comment]
I'll have to test the form action url in NC16 but it's just the ``$_SERVER['PHP_SELF']`` variable. 
next release will include the fix.
Thanks for reporting.

**Comment by ingoha** [comment]
Yes, but `$_SERVER['PHP_SELF']` expands to `/index.php`. And in my case, that's wrong because my nc sits behind nginx and urls are not prefixed with `index.php` :-/ When I replaced the action with `"?"` it worked.

**Comment by SergeyMosin** [comment]
I see, I'll just get rid of the form _action_ attribute, that should make the form "post" to it self.

Thanks

**Comment by SergeyMosin** [comment]
Fixed in v1.1.10
