### ISSUE TITLE
Support for booking multiple successive timeslots

### ISSUE THREAD

**Issue by madsl** [SergeyMosin/Appointments#310]
Great app! I found out it was perfect for a public meeting area booking, very neat!

Would it be possible to add support for selecting several slots during a single booking, so you in effect could book 2 or several successive hours (if available) without having to do the booking several times?

**Comment by SergeyMosin** [comment]
There are no plans to implement booking/selecting of multiple appointments at the same time, however there other options to let visitors chose different appointment durations:

- Add multiple duration in the "Weekly Template" mode, info https://github.com/SergeyMosin/Appointments/issues/186#issuecomment-792134114
- Use multiple pages with different durations and the same destination calendar ( + a "Directory Page") to direct visitors to for example "30 min" and "1 hour" appointments, more info https://github.com/SergeyMosin/Appointments/issues/21#issuecomment-696738211
