### ISSUE TITLE
Two confirm booking button

### ISSUE THREAD

**Issue by Vince2956** [SergeyMosin/Appointments#311]
There are two buttons to confirm an appointment : one in the confirmation email, the other on the web page.

This has the effect of disturbing the confirmation, the risk of not confirming is great, if you think you have confirmed just with the email button.

The best would be to validate just with the email.

**Comment by SergeyMosin** [comment]
Please see issue #293 (antivirus / antimalware email link scan cancelling appointments automatically), however maybe we can make the web page step optional in the future I guess.

**Comment by Vince2956** [comment]
Alright, I'm OK with this.
