### ISSUE TITLE
Request: Reduce Iframe to strictly the form itself, not the surrounding background styling of public page

### ISSUE THREAD

**Issue by NomenCognomen** [SergeyMosin/Appointments#313]
When attempting to embed an appointment page with an iframe, one is forced to incorporate the appointment page background into the main page (outside of the appointment form) where the scheduler is to be embedded, which may not be appropriate styling for all places where the scheduler needs to be embedded.  This greatly diminishes usability because the appointment page must either be styled specifically to fit into a given page, or one must settle for haphazard web pages.

Attempting to crop the iframe down to strictly the exact height and width of the appointment form is unable to overcome the issue.  First of all, there is header space above the form that will persist and cannot be effectively cropped away.  Also, because as the size of the iframe is reduced to sizes approaching the form, the linked page develops empty white space to the right and bottom of the form.

There is a great usability benefit to being able to limit the iframe to strictly the form itself.  Aside from being able to more readily use the embeddable in essentially any web page, the form could in turn be readily embedded into emails as well.  It would be a huge tool for anyone looking for a way to convert leads directly into sales meetings or billable bookings.  This could help the app take yet another leap beyond the limited functionality of the calendar appointment system (which seems to be clearly aimed at user-to-user scenarios).

![form empty surrounding space](https://user-images.githubusercontent.com/98632073/159768399-5e9f8b71-0b9e-4ead-8751-b3607cc6d638.PNG)

**Comment by bmclean2** [comment]
@NomenCognomen I agree this would be helpful. One pseudo workaround I used was to set the <form> tag to `height: 100%` and `width: 100%` and then setting a defined size for the iframe itself on my site's css, but I am running into issues with the confirmation page--I haven't figured out if I can style that yet.

**Comment by SergeyMosin** [comment]
> but I am running into issues with the confirmation page--I haven't figured out if I can style that yet.

Yes, it's a bug. Custom styles are not applied to confirmation ( and error ) pages. I'll fix it for the next release.

Thanks for the report.

**Comment by SergeyMosin** [comment]
iframe pages already use the simplest layout ( https://github.com/nextcloud/server/blob/master/core/templates/layout.base.php ) provided by NC so there is nothing much I can do about removing the page background.

As of v1.12.3 confirmation and error pages can be styled, also now the form sends messages to the parent indicating what content is being shown: https://github.com/SergeyMosin/Appointments/blob/master/tests/embedding/php-page.php#L28-L49

More examples are here: https://github.com/SergeyMosin/Appointments/blob/master/tests/embedding/
