### ISSUE TITLE
Style Override: Button Color 

### ISSUE THREAD

**Issue by 2zla** [SergeyMosin/Appointments#314]
I noticed your documentation provides an example for Style Override. However, I could not sort out how to change the button color.

Viewing the source code for the embed page, I'm able to add this `style=` tag to the following:
`<button style="background: #2188ff" id="srgdev-ncfp_fbtn" class="primary srgdev-ncfp-form-btn" data-tr-ses-to="Session Timeout. Reload.">`

However adding these line to the Style Override portion of the Appointment app does not change the button color:
`.srgdev-ncfp_fbtn{
     background: #2188ff;
}`
or 
`.srgdev-ncfp-form-btn{
     background: #2188ff;
}` 

Can you provide an example of how I may accomplish this?

**Comment by SergeyMosin** [comment]
Something like this should work, use `#`(id) instead of `.`(class) for `#srgdev-ncfp_fbtn`:
```
<style>
#srgdev-ncfp_fbtn{
  background: red;
  border-color: red;
}
#srgdev-ncfp_fbtn:hover{
  background: green;
  border-color: green;
  color: red;
}
</style>
```

**Comment by 2zla** [comment]
That works perfectly. 
Thank you for the quick response, and the amazing nextcloud app!
