### ISSUE TITLE
Redirect to a custom "All done"/"Your appointment scheduled..." page

### ISSUE THREAD

**Issue by kirkawolff** [SergeyMosin/Appointments#315]
After a person confirms the appointment, rather than just showing the text "Your appoint is scheduled .." page, I would like it to redirect back to the main website for them to fill-out a questionnaire. 

Right now Appointments only allows one question to be asked about the person making the appointment, and rather than waiting for you to implement the multiple custom fields feature I'd rather just have them fill out a questionnaire as a final step after confirming the appointment. This final page I want them redirected to will be emailed to me when they press submit, very simple and my marketing director doesn't need to edit code to change the questionnaire.

I looked through your plugin code and it doesn't appear you have support for a custom "all done" page, or a method for the "All done" page to redirect back to the main website.

As an aside, I'm also using the iframe feature with emb_afad_YourUserName, and have found that emb_cncf_YourUserName severely breaks the links in the confirmation email.

**Comment by SergeyMosin** [comment]
A redirect to a custom "All done" page sound like a good idea. I'll try to include it into the next release. A query param with an appointment date would be appended as well, something like this probably:
```
https://www.example.com/your_page.php?appt_date=Monday%20Feb.%207th%202022
``` 
>  and have found that emb_cncf_YourUserName severely breaks the links in the confirmation email.

New bug, regression from double confirmation update. I'll post new instructions ASAP.

Thanks for the report.

**Comment by SergeyMosin** [comment]
As of v1.12.3 a custom "All Done" URL can set in `User/Organization Info > Advanced Settings > Redirect Confirmed URL` , additional details are available in the `Help/Tutorial` section.

See https://github.com/SergeyMosin/Appointments/tree/master/tests/embedding for embedding examples.

**Comment by kirkawolff** [comment]
This is very exciting! Thank you. It looks like nextcloud has this version on their website, but I don't see it in the occ-tool when I try to perform a "occ app:update appointments" and the version is stuck at  1.12.2. Do you know when this version will be made available through update?

**Comment by SergeyMosin** [comment]
> ...but I don't see it in the occ-tool when I try to perform a "occ app:update appointments" and the version is stuck at 1.12.2

This is very strange, I'll try to reproduce a `1.12.2 -> 1.12.3` update via the `occ` tool tomorrow and will post results here.

**Comment by SergeyMosin** [comment]
I can not reproduce the update issue. I can see the new version in both GUI Apps screen and via the `occ` command.

![Screenshot from 2022-04-26 09-50-44](https://user-images.githubusercontent.com/10747559/165333813-53255187-0e53-4f22-8280-7ed37a19fa68.png)

---

```
sergey@ubnt:~/nextcloud/nextcloud23$ sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - appointments: 1.12.2
  - calendar: 3.2.2
  ...

sergey@ubnt:~/nextcloud/nextcloud23$ sudo -u www-data php occ app:update --showonly
appointments new version available: 1.12.3

sergey@ubnt:~/nextcloud/nextcloud23$ sudo -u www-data php occ app:update appointments
appointments new version available: 1.12.3
appointments updated
```

Further more it looks like NC is using the same code for GUI and `occ` update. It fetches a list(large json file) of available apps/updates from this URL: https://apps.nextcloud.com/api/v1/apps.json . I can see latest Appointments app version there:
```
...
{"version":"1.12.3","phpExtensions":[],"databases":[],"shellCommands":[],"phpVersionSpec":"*","platformVersionSpec":">=21.0.0 <24.0.0","minIntSize":32,"download":"https://github.com/SergeyMosin/Appointments/raw/95c9fcb8ef495a032ac5f1ea58dfb47fca871e55/build/artifacts/appstore/appointments.tar.gz","created":"2022-04-11T18:38:27.429811Z","licenses":["agpl"],"lastModified":"2022-04-11T18:38:27.804939Z","isNightly":false,"rawPhpVersionSpec":"*","rawPlatformVersionSpec":">=21 <=23"
...
```
This file is cached for one hour in `[NC_INSTALL_DIR]/data/appdata_oc.../appstore/apps.json`

The URL is constructed here:
https://github.com/nextcloud/server/blob/dffbddcca6fa0221b8f2ac138732cf01154a5187/lib/private/App/AppStore/Fetcher/AppFetcher.php#L71

and here:
https://github.com/nextcloud/server/blob/036f871d01ed6903467861b0fa2b18d5f5ae4a0c/lib/private/App/AppStore/Fetcher/Fetcher.php#L255-L257

Please note that default `endpoint` URL can be overridden in your `[NC_INSTALL_DIR]/config/config.php` file with `appstoreurl` key.

So possible reasons can be:
1. Overridden `appstoreurl` which is not in sync with the NC store
2. Timeout or other connectivity problems to the default ( https://apps.nextcloud.com/api/v1/apps.json ) API gateway

**Comment by kirkawolff** [comment]
I've traced the root cause to ipv6. I changed /etc/gai.conf to prefer ipv4 connections, and now snap is able to sucessfully update the jailed package and it was also able to update the apps from the nextcloud appstore.  Thank you for looking into this for me, it turned out to be a routing problem with my ISP.

**Comment by kirkawolff** [comment]
I just gave it a try and the redirect works perfectly! Thank you!
