### ISSUE TITLE
On Public Page, use instance name, not 'Nextcloud' hardcoded

### ISSUE THREAD

**Issue by nooblag** [SergeyMosin/Appointments#316]
On public pages, it appears Nextcloud is hardcoded text.

![screenshot3](https://user-images.githubusercontent.com/1122344/161486063-35c7dfc1-66d6-4059-8202-495308b23dfc.jpg)

It would be good if this text was pulled from Nextcloud Theme (to maintain consistent branding) OR better yet, was a heading that could be customised in the plugin settings.

![theming-nw](https://user-images.githubusercontent.com/1122344/161486079-1fb9dfba-2991-4fdc-ab49-9b34c52cdc16.png)

**Comment by SergeyMosin** [comment]
The header text is customizable via `Settings > Customize Public Page > Advanced Settings > Page Header Title (and Page Header Subtitle)`

![image](https://user-images.githubusercontent.com/10747559/161623860-a1a3550f-a9fa-421b-81be-b10ac4c1a46f.png)

@nooblag also it looks like your public page screenshot is from an older version of NC and/or appointments app. What version are you using ?

**Comment by nooblag** [comment]
Ah those settings are even better!!! I just missed all that because I didn't look properly that it was an accordion menu. Apologies for the hassle...

And yes, screenshots are just illustrative, I took them from the web cos it was easier that getting screenshots from my theme and removing company logo, etc. I'm on the latest versions: Nextcloud 23.0.3 and Appointments 1.12.2.
