### ISSUE TITLE
[Feature Request] Disable particular fields in the form

### ISSUE THREAD

**Issue by SomeThink1729** [SergeyMosin/Appointments#317]
I would like to disable the email field and for some occasions maybe some others too. I haven't set up a mail server and I'm not considering to do so. Furthermore I don't need any confirmation on my appointments via mail, notifications are enough.

**Comment by SergeyMosin** [comment]
Email is the main communication channel between Organizers and Attendees an therefore can not be disabled. There is an option to remove the "Phone" field already, but all other fields are required for the app to function properly.
