### ISSUE TITLE
Public link does not work

### ISSUE THREAD

**Issue by schniepp** [SergeyMosin/Appointments#32]
I believe I set up the appointments correctly. I used a new calendar (does this need to be shared publicly?), I added the Organization and Address info, and I added appointments. The appointments correctly show up in the calendar. Then, I turned on public sharing via choosing "share onine". After that, it says "Public Page [online]".

However, when I do the "Copy public link" and paste that link in a browser, it does not resolve correctly. In an incognito browser window (without being logged in), this redirects to a login screen asking for username and password. When pasted in a new tab, this redirects to the root view of the "files" app — without showing the appointments app. 
However, when I manually add "apps/appointments/#" to the root of my public nextcloud instance (from a logged in session), the appointments page correctly shows up. 

Interestingly, when I run a occ app:check-code appointments, I get this:
`Invalid appinfo.xml file found: Element 'namespace': This element is not expected. Expected is ( category ).
App is not compliant`

In the logs I find lots of these:
`[PHP] Error: Undefined index: appt_pps at ****/apps-added/appointments/templates/public/form.php#14
GET ****/apps/appointments/form?v=1584564520020
from ***.***.111.45 by ******** at 2020-03-18T20:48:40+00:00`

This is v1.1.6, nc18.0.2, php7.2, chrome client.

**Comment by SergeyMosin** [comment]
Can you please check browser console: it should have ``data-state:  ?`` line there.

The is just a liner thing and should not effect anything, I'll fix it in the next release.
Thanks

**Comment by SergeyMosin** [comment]
And can see the public link provided by the "Copy public link" button

**Comment by schniepp** [comment]
> And can I see the public link provided by the "Copy public link" button

Is this a question for me?
But anyway, as mentioned above, I can see the "Copy public link" button. That is where I am getting the link from. But that link does not work. (Asks for login.)

**Comment by SergeyMosin** [comment]
@schniepp yes, I just want to see the part after ``apps/appointments/pub/`` . Also, v1.1.8 is out, that should fix the ``Error: Undefined index: appt_pps`` and occ validation
Thanks

**Comment by schniepp** [comment]
> @schniepp yes, I just want to see the part after `apps/appointments/pub/` . Also, v1.1.8 is out, that should fix the `Error: Undefined index: appt_pps` and occ validation
> Thanks

OK, this is interesting. The public link looks like this: 
[***/owncloud/index.php/owncloud/apps-added/appointments/pub/mJ%2BuBa71hq1oMisb/form](***/owncloud/index.php/owncloud/apps-added/appointments/pub/mJ%2BuBa71hq1oMisb/form). The address of my instance is [***/owncloud/](***/owncloud/). (It's a legacy URL from times before the nextcloud fork.)
But why does the "owncloud" show up twice? Is this coincidentally also used by the app? I also should add that I have all the non-standard apps in a separate folder "apps-added", and I have configured the system accordingly. I do this to make the upgrading easier, since I usually upgrade manually and unpack the ZIP as released from nextcloud.

**Comment by schniepp** [comment]
OK, I now found that this link works: [***/owncloud/index.php/apps/appointments/pub/mJ%2BuBa71hq1oMisb/form](***/owncloud/index.php/apps/appointments/pub/mJ%2BuBa71hq1oMisb/form).

(I actually had symlinked `apps/appointments` to `apps-added/appointments`.)

**Comment by schniepp** [comment]
> @schniepp yes, I just want to see the part after `apps/appointments/pub/` . Also, v1.1.8 is out, that should fix the `Error: Undefined index: appt_pps` and occ validation
> Thanks

I saw that there is already 1.1.9 out! Indeed, now the validation check passes. Thanks so much!

**Comment by schniepp** [comment]
> Can you please check browser console: it should have `data-state: ?` line there.
> 
> The `Invalid appinfo.xml file found: Element 'namespace'` is just a liner thing and should not effect anything, I'll fix it in the next release.
> Thanks

I was unable to find the `data-state` message. I am not experienced using the browser console, though. So in Chrome I activated the console, which shows about 40 messages, a few errors, warnings, etc. Then, I put "data-state" into the search window of the console, but nothing came up. Would you like me to do something else?

**Comment by SergeyMosin** [comment]
Thanks for troubleshooting the URL situation. The culprit seems to be the ``getAppWebPath`` function in the ``IManager``. I'll just probably end-up hard-coding the ``apps/appointments`` part of the URL in the next release. I would not worry about the ``data-state`` message for now. FYI: The confirm/cancel links in the "action required" email most likely have the wrong URL as well.

Thank you very much.

**Comment by schniepp** [comment]
I just confirmed that the link in the confirmation email is indeed wrong. Thanks for letting me know!

**Comment by SergeyMosin** [comment]
Should be fixed in v1.1.10

**Comment by schniepp** [comment]
Awesome! I confirmed that it works. That was fast!!!
Thanks for much for all your work!
