### ISSUE TITLE
[I18N] String needs clarification

### ISSUE THREAD

**Issue by meskobalazs** [SergeyMosin/Appointments#320]
There is this line in the code:
https://github.com/SergeyMosin/Appointments/blob/3fa59e8295ce1bf0b053b71f7a91a8f401865684/src/components/settings/UserContactSettings.vue#L84

What does this mean exactly? I would like to understand when this URL is used, because currently I am not sure about its translation.

**Comment by SergeyMosin** [comment]
https://htmlpreview.github.io/?https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php#srgdev-sec_confirmedUrl

or

https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php#L189

**Comment by meskobalazs** [comment]
Thank you, this is just what I needed.
