### ISSUE TITLE
Events with class: CONFIDENTIAL do not produce time slot conflict

### ISSUE THREAD

**Issue by evilham** [SergeyMosin/Appointments#321]
Hello,

this plugin has obviously had tons of love and thought put into it, thank you!

I realised that some events are ignored when checking for conflicts, indeed events from a subscription calendar to another nextcloud instance, where they have the visibility setting in nextcloud set to "When shared, only show if busy", which results in events that look like this for the public subscription:

```
BEGIN:VEVENT
CREATED:20220413T161829Z
UID:UUID
DTSTART;TZID=Europe/Berlin:20220420T160000
DTEND;TZID=Europe/Berlin:20220420T170000
SUMMARY:Busy
CLASS:CONFIDENTIAL
END:VEVENT
```

I found following lines that check for whether or not the class of the event is `PUBLIC`, and destroys the events otherwise; could we support class `CONFIDENTIAL` there?
https://github.com/SergeyMosin/Appointments/blob/0236e48f065c902371d9321fb376a2700082acf6/lib/Backend/BCSabreImpl.php#L252
https://github.com/SergeyMosin/Appointments/blob/0236e48f065c902371d9321fb376a2700082acf6/lib/Backend/BCSabreImpl.php#L511

Asking before I open a PR because... well, there might be a good reason not to :-).

Cheers,

**Comment by SergeyMosin** [comment]
@evilham that's a good find, I did not realize that NC marks events as `CLASS:CONFIDENTIAL` in the case you described.

For the next release I'll add `Include 'CONFIDENTIAL' events in conflict check` option in `Settings > Advanced Settings` ( under the '_Include all day events in conflict check_'). I'll also link to this issue for more info in the help/tutorial section.

_P.S. If you want a contributor key please contact me: sergey[at]srgdev.com_

**Comment by evilham** [comment]
Having the option sounds great!

However: RFC5545 doesn't really define how an event's class is to be used https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.3
But rather that it is up to each application to decide how to treat them.

From my understanding of this plugin (a particular user's perspective), I would expect it to just look for conflicts regardless of whether or not we can see the details of the event.
Of course some people might disagree, so the option to change the default behaviour is a great idea :-D

But wouldn't it make a tad more sense to have all events be a conflict by default, regardless of their `CLASS`?

Tacking this issue also raises the question about `CLASS:PRIVATE` (and x-name and iana-token values which should be treated the same as PRIVATE), which I reckon I haven't seen around >,<.

**Comment by SergeyMosin** [comment]
Upon digging deeper NC adds CLASSes as follows:
```
PRIVATE = when shared hide this event
CONFIDENTIAL = when shared show when busy
PUBLIC = when shared show full event
```
so by default as of v1.12.4 both `PUBLIC` and  `CONFIDENTIAL` events will be used in conflict check and `PRIVATE` events will be ignored

**Comment by evilham** [comment]
Juhuuu! I think that's great news <3

Shouldn't this check be amended as well though?

https://github.com/SergeyMosin/Appointments/blob/0236e48f065c902371d9321fb376a2700082acf6/lib/Backend/BCSabreImpl.php#L252

**Comment by SergeyMosin** [comment]
> Shouldn't this check be amended as well though?
> 
> https://github.com/SergeyMosin/Appointments/blob/0236e48f065c902371d9321fb376a2700082acf6/lib/Backend/BCSabreImpl.php#L252

This code scans "source" calendars for available time-slots which must be marked as **free** ( `TRANSP:TRANSPARENT` ), and as per NC `CONFIDENTIAL = when shared show when busy` specs these events are never **free** when shared, therefore they should be ignored by the Appointments app. I hope this makes sense :slightly_smiling_face: .

**Comment by evilham** [comment]
Oh, that makes sense! Thank you for explaining!
