### ISSUE TITLE
Reminder email in EN + broken URL to cancel appointment.

### ISSUE THREAD

**Issue by KapriQ** [SergeyMosin/Appointments#323]
Hello,

I am using SK translation/language in my NextCloud, and all email sent from appointments are fine, in the SK language, but REMINDER email stays in EN + has broken link to cancel the appointment.
The link is missing domain, it start with "http://localhost...."

Thanks,

**Comment by SergeyMosin** [comment]
> RE: The link is missing domain, it start with "http://localhost/...."

Because "reminders" code uses `cron`, please see `overwrite.cli.url` configuration parameter https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations
From NC manual:
> Use this configuration parameter to specify the base URL for any URLs which are generated within Nextcloud using any kind of command line tools (cron or occ). The value should contain the full base URL: https://www.example.com/nextcloud

----

> RE: REMINDER email stays in EN

I'll try to replicate this. Thanks for the report.

**Comment by KapriQ** [comment]
I have change overwrite.cli.url in config, and link for cancel the appointment is working now, but the mail of reminder is still in ENGLISH, can you help me? Thanks

**Comment by SergeyMosin** [comment]
It looks like `cron` language uses `'default_language' => 'en'`  setting as per here: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#user-experience which defaults to English if it is not specifically set to `sk`. Can you check this setting in your `config/config.php`

**Comment by KapriQ** [comment]
I have no default_language set in config pho, should I set it to: 'default_language' => 'sk' ?

**Comment by KapriQ** [comment]
If i set the `'default_language' => 'sk'` no email is sent...

**Comment by SergeyMosin** [comment]
Documentation is updated in v1.12.5
