### ISSUE TITLE
Multiple Hostname support in iframe

### ISSUE THREAD

**Issue by kirkawolff** [SergeyMosin/Appointments#325]
When iframe embedding with the command:
 occ config:app:set appointments "emb_afad_YourUserName" --value "your.domain.com"

Only one hostname is supported. However, there are circumstances where webmasters will alternate between www.domain.com and domain.com which breaks the "afad" setting. Is there a way to support more than one hostname in an iframe?

**Comment by SergeyMosin** [comment]
Not tested but as per [specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src) it should be possible to add a space separated list of domains like so:
```
occ config:app:set appointments "emb_afad_YourUserName" --value "your.domain1.com your.domain2.net"
```
additional [CSP Sources specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources)  allow wild card '*' character so for the `www` case something like this should work:

```
occ config:app:set appointments "emb_afad_YourUserName" --value "*.domain.com"
```

**Comment by kirkawolff** [comment]
This works great. I did not try the wildcard, but entering "www.domain.com domain.com" produces the necessary behavior. Thank you!

**Comment by pongraczi** [comment]
One more question, is this true for the ```emb_cncf_YourUserName``` , too?

Like this:  

```
occ config:app:set appointments "emb_afad_YourUserName" --value "your.domain1.com your.domain2.net"
occ config:app:set appointments "emb_cncf_YourUserName" --value "your.domain1.com/appointments?some_param= your.domain2.net/appointments?some_param="
```

**Comment by pongraczi** [comment]
Seems working.
