### ISSUE TITLE
Weekly Template Editor header not properly adapting to dark theme

### ISSUE THREAD

**Issue by xeruf** [SergeyMosin/Appointments#327]
both in native dark theme:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/13354331/166934108-91a57850-20ea-413a-81b2-83b6bd082015.png">
and in breeze dark:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/13354331/166934141-316e6d80-629c-41c8-818b-78cd446ea13b.png">

Probably missing some attribute.

**Comment by SergeyMosin** [comment]
fixed in v 1.12.4
