### ISSUE TITLE
Booked Appointment Buffers (Should take into account existing conflicts)

### ISSUE THREAD

**Issue by rightsaidfred99** [SergeyMosin/Appointments#328]
Hello, 

The new Booked Appointment buffers is great! 
However It does not seem to work for "After" with existing conflict when source is Google Calendar. 

So if I have a 1hour booking at 2pm with 30 minutes in between bookings. 

Client should only be allowed to next book 3:30pm. 

Currently, the app only reads the start point thus currently a client can actually book 3pm despite there being a 30 minute buffer on the "After" option. 

Hope that makes sense. 

I just propose that the app takes into consideration the length of the existing calendar event with Google Calendar

**Comment by rightsaidfred99** [comment]
Buffers for all option would be awesome. 

Many times clients send me ICS invites which I accept, so to have appointments buffer time from existing appointments would be awesome

**Comment by SergeyMosin** [comment]
If I remember correctly some test failed on subscription/external (google, office360) calendars. I'll circle back to this over the weekend and see if at least NC native calendar events can be included into the "buffer check".

**Comment by sschachamayr** [comment]
Also very interested, I'm using nc calendar as the main 'conflict-base'
Many thanks to @SergeyMosin 
Regards from Austria

**Comment by SergeyMosin** [comment]
Buffers apply to ALL blocking events as of v1.14.14
