### ISSUE TITLE
Send confirmation mail to administrator Email instead

### ISSUE THREAD

**Issue by audelorAd** [SergeyMosin/Appointments#330]
I'd like te be able to manage booking requests from attendees.
Is there any possibility to send the confirmation email to my email adress instead the attendees one ?

**Comment by audelorAd** [comment]
Yes it's similar ! Sorry for duplicating issue. It would be a great improvement.
Whatever, thanks for your work ! Appointments App is very useful.

**Comment by SergeyMosin** [comment]
Since #222 is tagged closing this.
