### ISSUE TITLE
Zoom connection available?

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#331]
Hallo, is there any possibility, to make automatically a new zoom appointment with the appointments app?

**Comment by SergeyMosin** [comment]
Current it is not possible. More info about third party services integration proposals is here: https://github.com/SergeyMosin/Appointments/issues/286#issuecomment-1024346525 , but in general we need a separate NC app first to manage zoom API calls, tokens, etc... something like this:

```
Appointments App   < -------- >  NC Zoom Manager App  < -------- >  Zoom
```

**Comment by stefan-franz** [comment]
Hello, i have an idea for an workaround - maybe you find it good. 

I have 2 Appointments: Zoom Calls and Telefon Calls where people can book. 
It would for me great if i get a fielt for every appointment, where i can put individual informations that is sent with the confirmation e-mail and with the reminder:

In the Zoom Appointment i can add e.g. a zoom link (recuring zoom meeting, always the same link would be easy and ok for me)
In the Telephone Call Appointment i can add my telephone nr. 

After booking so the customer gets autoamtically the information who is needed. With my manual dates i use always the same zoom link for a recurring zoom meeting - so your app would have all features for 100% automatically information. 

And if this information would also displayed in my confirmation e-mail and calender entry it would be great. 

Best Regards, Stefan
