### ISSUE TITLE
What means the Directory Page (comes after add more than 1 Appointment)

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#333]
Hello, what is the function of the directory page that appears, after making more than 1 appointment?
Is there anywhere a manual for it?

**Comment by SergeyMosin** [comment]
>Is there anywhere a manual for it?

Not really, but people use it as a "landing page" for different types of appointments they offer. For example:
- Two barbers in a barbershop
- "Product A" and "Product B" demos that might take different amount of time and be offered on different days
![image](https://user-images.githubusercontent.com/10747559/168083131-5e6c1371-4b3d-4727-9e31-f18771dc78bb.png)

Some more info: https://github.com/SergeyMosin/Appointments/issues/21#issuecomment-696738211
