### ISSUE TITLE
Suggestion - 2-3 option fields in further versions

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#334]
Hello, i love your app. Let me suggest an additional function:

Useful would be for me (as in Calendly possible) to have at the page, where a person selects a date, 2 possible fields every appointment type, where i can ask a question or a person can add some information. 

Every field may be the follow options would helpful:
Switch for on/off
Headline (Question, what the user should write in the field)
Field for User

And all transmitted to the calendar entry and transmitted via e-mail.

**Comment by SergeyMosin** [comment]
This feature request is tracked here: #223
