### ISSUE TITLE
Change name of field 

### ISSUE THREAD

**Issue by vithusel** [SergeyMosin/Appointments#336]
Im not entirely too sure why. But one of the fields for me is showing as "surname"
Is there any way i can change this? 

![image](https://user-images.githubusercontent.com/31311292/169399239-f605d2a1-6a75-420b-aa4f-1f0bbf3aa1ea.png)

This is my Style Override: 
<style>
#header{
    background: transparent !important;
}
#content{
    background: linear-gradient(to bottom, #102e4b98, #000000) !important;
}
#body-public #content {
    min-height: 100%;
}
form{
    background:whitesmoke;box-shadow: 3px 3px 25px 0px rgba(0,0,0,0.75);
}
.srgdev-ncfp-form-header{
    border-bottom: 3px solid #961AB1;
}
</style>

This is my JSON Object: 
{
  "tag": "textarea",
  "label": "Summary (optional)",
  "placeholder": "Include ticket reference number or a brief description"
}

**Comment by SergeyMosin** [comment]
> But one of the fields for me is showing as "surname"

You are most likely using  `English (British English)` language in NC settings and according to the translation file (see below) provided by NC community, `Name` [English (US)] translated into `Surname` [English (British English)]. So you have a couple of choices:
1. Use `English (US)` language
2. Update the translation on https://www.transifex.com/nextcloud/nextcloud/ and it will be included in the next release 
3. Not tested ,but I think it is possible in CSS Override to hide the `<label for="srgdev-ncfp_fname" class="srgdev-ncfp-form-label">Surname</label>` element and then use `:before` pseudo class element on `<input name="name" placeholder="Enter name" id="srgdev-ncfp_fname" class="srgdev-ncfp-form-input" type="text">` to add the "label" text you want.

https://github.com/SergeyMosin/Appointments/blob/1e144e8b81b3be0a35d0788065036686e6737670/l10n/en_GB.json#L70-L74

**Comment by vithusel** [comment]
Ah ok. 

Thank you for the fast reply. 

I've changed the language for the moment. I'll make the changes to the translation files later today.
