### ISSUE TITLE
When appointment is cancelled, change calendar event name to "Avaliable" and event status to "Tentative".

### ISSUE THREAD

**Issue by antonkarliner** [SergeyMosin/Appointments#34]
In my opinion, when appointment is cancelled by client, calendar event name shoud be changed back to "Avaliable" and event status to "Tentative". This will set free the appointment slot and it will be avaliable for booking again.

Admins could be notified about the booking cancelation via e-mail or Nextcloud notifications.

**Comment by SergeyMosin** [comment]
Available in version 1.4.0 ``Customize Public Page > Advanced Settings > When Attendee Cancels``

>Admins could be notified about the booking cancelation via e-mail or Nextcloud notifications.

Available in version 1.4.0 ``Email Settings > Email Me when an appointment is: ...``

**Comment by antonkarliner** [comment]
Amazing! Thanks
