### ISSUE TITLE
optional disable email and phone requirement in appointments

### ISSUE THREAD

**Issue by viisauksena** [SergeyMosin/Appointments#340]
we have some very personal data sensitive use cases where we NEED to disable email and phone - or make them at least optional, is there a way to do so?
If not we strongly suggest to consider adding it.

**Comment by trevor87** [comment]
I know that this is definitely possible for phone numbers. You can find it in Settings -> Advanced settings -> Hide Phone number field (the texts might be slightly different as I use the German translation)

**Comment by hackvokat** [comment]
Marking email and phone number as optional would be important to me too!

**Comment by viisauksena** [comment]
by chance - any update on this issue?

**Comment by SergeyMosin** [comment]
This is an inserting feature which would probably be limited to registered NC users since we DO NEED to communicate with the potential attendee somehow. Closing this in favor of #56 as they are very similar.

**Comment by hackvokat** [comment]
Is there any chance to change that email field optional like the phone number?

Or is there a possibility to replace the existing email field with a custom field which is then not required? 
I would be fine with the emails being sent to myself if no email was specified.

In my case an online service provider enters appointments of callers, unfortunately not all callers have an email address. Especially older people are excluded in this way.
