### ISSUE TITLE
Bug: "Additional ICS file description" not working

### ISSUE THREAD

**Issue by trevor87** [SergeyMosin/Appointments#342]
Hello,

I am using Nextcloud Version: 22.2.8 with Appointments Version: 1.12.3 and have noticed the following issue:

When entering text in the Email Settings -> Additional ICS file description field this text is not actually added to the ics file description. In fact, the ics file the user gets sent does not contain a description field at all.

PS: I did not add any html.

Thanks for the great nextcloud app, it is very useful!

**Comment by SergeyMosin** [comment]
I can not reproduce this. Here is my test results (in Thunderbird preview)

![image](https://user-images.githubusercontent.com/10747559/171695958-a4e4e3c5-16bd-4ec6-b158-5d4bab0992c2.png)

Can you please send me (sergey [at] srgdev.com) your settings dump `Settings > Advanced Settings > Debugging > Settings Dump` so I can match your settings on my machine.

**Comment by SergeyMosin** [comment]
The bug is confirmed: ICS file `Description` is unset when organizer phone number is not provided.

@trevor87 thanks for the report.

**Comment by SergeyMosin** [comment]
Fixed in v1.12.6
