### ISSUE TITLE
Bug: Form-Title not saved

### ISSUE THREAD

**Issue by trevor87** [SergeyMosin/Appointments#343]
Another possible bug I wanted to post using the same config as previous: I have created two forms and noticed that the form-title (Formulartitel) is not saved in the first one (although in the second one this works).
See here:
1. I enter all values
![grafik](https://user-images.githubusercontent.com/6329259/171861419-a54a47e8-8dac-4ef4-92c7-4a60964b8d85.png)

2. All values except Formulartitel are updated
![grafik](https://user-images.githubusercontent.com/6329259/171861490-32aa1181-34af-4e1c-8fb4-9a4b3d919b5a.png)

3. When opening the settings menu again, Formulartitel is empty again.
![grafik](https://user-images.githubusercontent.com/6329259/171861559-144c30c8-f90c-4f6c-b535-24e90b086243.png)

**Comment by SergeyMosin** [comment]
`Form Title` fields on `User/Organization Info` should have been shown for secondary pages only (fixed in v1.12.6). Main page `Form Title` is set in `Settings > Customize Public Page > Form Title`
