### ISSUE TITLE
Batch create new items.

### ISSUE THREAD

**Issue by enaut** [SergeyMosin/Appointments#347]
Hey all,

for a two day event with 30 hosts I need to create a bookable schedule - Each having 10 appointments. For a single person it is relatively easy to do with this app. But I'd have to repeat doing the steps 30 times which is error prone and time consuming since it is a multiple steps process.

Is there a way to create the 30 "calendars/appointments" with a script or in a batch?

Thank you for the help.

**Comment by SergeyMosin** [comment]
Sorry, this is beyond the scope of this app.
