### ISSUE TITLE
Appointments: Could not book appointment.  Please try again later or contact the organizer.

### ISSUE THREAD

**Issue by CSchaefer70** [SergeyMosin/Appointments#348]
I really love this booking idea and everything works as I would expect until I preview (any browser) and I can pick Dates and Times.  Then I receive a warning: Could not book appointment.  Please try again later or contact the organizer.

Appointment version = 1.12.7
Calendar version = 3.4.2

Where am I going wrong?

My PhP is 8.1.7, MariaDB 10.6.7, Baso OS = Ubuntu 22.04, NextCloud version 24.0

<img width="584" alt="2022-07-11_16-09-22" src="https://user-images.githubusercontent.com/26978180/178350028-98e75cf2-7874-4a09-9723-dccfa41ef8b4.png">

**Comment by SergeyMosin** [comment]
More info: https://github.com/SergeyMosin/Appointments/issues/270#issuecomment-986075781

**Comment by CSchaefer70** [comment]
Hello,

Thx for the prompt reply.  Actually, completely my fault.  Firewall on my VPS.  I thought is was updated, but, forgot I reloaded for other reasons a few days ago.

So actually nothing was wrong with NextCloud Calendar or Appointments!!

URL = https://kingdomharvest.club/nextcloud/index.php/apps/calendar/appointment/GezCmEKMn4ik

Great work!!!!!

<img width="484" alt="2022-07-11_17-51-37" src="https://user-images.githubusercontent.com/26978180/178367508-edf794c1-0c6f-48a7-a5d0-7c3b37167892.png">

<img width="531" alt="2022-07-11_17-50-55" src="https://user-images.githubusercontent.com/26978180/178367510-ba709f5d-2232-419c-8acd-30e6674990ce.png">
