### ISSUE TITLE
Cant Add New Timeslots after an Link is created

### ISSUE THREAD

**Issue by unclesam87** [SergeyMosin/Appointments#349]
[Nextcloud Version 24.0.2]
[NGINX]

I discovered an strange error:
I created an link with an date in it and several time slots (simple mode) for one day. I sended it out and people book dates, then the customer asked me to add an second day, so i added some timeslots, they show up in my calendar as available but arent bookable over the link as the second day isnt their.

**Comment by SergeyMosin** [comment]
Can you check your "show for next weeks" setting, Info: https://github.com/SergeyMosin/Appointments/issues/221#issuecomment-863543374
