### ISSUE TITLE
Option to use without time slots for resource booking

### ISSUE THREAD

**Issue by juliencarnot** [SergeyMosin/Appointments#351]
I was hoping to be able to use this app to manage resource bookings (for example, booking a car from a fleet for X days/hours if it is available), but it seems like the time slot feature is complicating this: I'd have to set a weekly template and be able to set only 2 different slot length, rather than letting the user set a starting time and a duration (unlimited and regardless of holydays).

Would it be possible to add a resource mode to the available modes? If so, depending on the cost, I'd be happy to contribute to this feature.

An alternative would be setting cars as resources with https://github.com/nextcloud/calendar_resource_management but there's no UI for that and the users would need an account and to log in to be able to create an event/booking...

Thanks!

**Comment by SergeyMosin** [comment]
Similar  / duplicate of #177 
Technically it is possible but unfortunately mostly due to the lack of time this feature will not be added any time soon.

**Comment by Tuetenk0pp** [comment]
> Similar / duplicate of #177 Technically it is possible but unfortunately mostly due to the lack of time this feature will not be added any time soon.

How does it look today? I would very much appreciate this feature!
