### ISSUE TITLE
How to show Weekly Template for more than one week

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#352]
When I use the weekly template only the current week is displayed in the form and not the following weeks. How can I extend the settings?

Example: https://nextcloud.roundaboutweb.info/index.php/apps/appointments/pub/V38INIMGxWLhRlb70/form

**Comment by SergeyMosin** [comment]
`Settings > Public Page Settings > Show appointments for next`
more info: https://github.com/SergeyMosin/Appointments/issues/221#issuecomment-863543374

**Comment by RoundAboutWEB** [comment]
There are 4 weeks:
![grafik](https://user-images.githubusercontent.com/26809494/180274986-2734ad11-69b5-4510-aa3e-7034f984775c.png)

**Comment by RoundAboutWEB** [comment]
Now it works:
![grafik](https://user-images.githubusercontent.com/26809494/180278139-a9779c2c-2bd3-457f-92a4-410153e9d288.png)
