### ISSUE TITLE
Event Name and Date Mixed Up in German Translation of Invitation Mail Message

### ISSUE THREAD

**Issue by gohrner** [SergeyMosin/Appointments#355]
The Invitation Mail Message in German reads as follows:

> Tester Tester,
>
> Ihr für Telefonat geplanter Dienstag, 6. September 2022, 15:00 Mitteleuropäische Sommerzeit-Termin ist jetzt bestätigt.
>
> Danke

My name and the event date are mixed up in the text.

Backtranslated to English, it currently reads:

> Planned for phone call your Tuesday, 6th of September 2022, 3 PM CEST event is now confirmed.

Mh... ;)

**Comment by SergeyMosin** [comment]
Thanks for the report,

It looks like a new translation has been provided by nextcloud community on [transifex.com](https://www.transifex.com/nextcloud/). It will be included in the next release.

![image](https://user-images.githubusercontent.com/10747559/187929237-e089ad57-4a8e-4488-a4d6-89dd4ca010e3.png)

**Comment by gohrner** [comment]
The new translation looks correct! Shall I close this issue now, or will it be closed when the next release is finalized?
