### ISSUE TITLE
feature request: to add to the form a "Choose appointment type" field

### ISSUE THREAD

**Issue by Flashpok** [SergeyMosin/Appointments#360]
Hello,
I am a user who supports (since yesterday) your application financially.
Would it be possible to add to the form a "Choose appointment type" field. In the administration interface, the administrator could add the following types (which would be automatically added as comments in the calendar):
-First appointment
-Follow-up appointment
-etc.

Thanks for your work!

**Comment by SergeyMosin** [comment]
Is this similar to what you need: https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-731510809

**Comment by Flashpok** [comment]
Thank you !
