### ISSUE TITLE
[BUG] Cannot edit Appointments (neither booked nor free) with Nextcloud Calendar or Caldav Calendar

### ISSUE THREAD

**Issue by L00tz1ffer** [SergeyMosin/Appointments#363]
After Creating Calendars and filling them up with free appointments (or still after booking those appointments for test purpose) and clicking them in calendar, the Calendar loads for infinity and there is no option to change Calendar Entries after theire done once....

Hopefully this info helps you, as this is all i got...

using nextcloud 24.05 on a strato.de webserver.

**Comment by SergeyMosin** [comment]
I can not replicate this issue (see pics). Can you please send me (sergey [at] srgdev.com) your settings dump `Settings > Advanced Settings > Debugging > Settings Dump` so I can match your settings on my machine and try again.

Appointments:
![image](https://user-images.githubusercontent.com/10747559/191262842-da26f1b9-8282-436c-ae04-8494f5f7558d.png)

and Calendar:
![image](https://user-images.githubusercontent.com/10747559/191263207-8ab6a91d-0c8a-48c0-99f1-827ae7c97411.png)

**Comment by zvknikoleit** [comment]
We have the same problem. If a booked appointment is viewed by a user with restricted rights, only the loading bar appears. (see screenshot 1)
However, if the user is an administrator, they can also see the entry (see screenshot 2). For the calendar itself, however, both actually have the same rights.

![image](https://user-images.githubusercontent.com/115080660/197777094-c3b5a7b3-2d41-4db6-b286-55319022ed5d.png)
(screenshot 1)

![image](https://user-images.githubusercontent.com/115080660/197777527-4e8019a2-6043-4a6e-a8a2-30a0ff3df390.png)
(screenshot 2)

**Comment by SergeyMosin** [comment]
@zvknikoleit Can you please check that your "user with restricted rights" is not effected by #368 (the user has an actual email address in the profile)

Thanks.

**Comment by zvknikoleit** [comment]
Yes, thanks, that seems to be the problem, but the peculiarity here was that the owner of the shared calendar did not have an email address. After adding this at least registered users could access it. However, external users accessing it via the public share still have this problem.

**Comment by SergeyMosin** [comment]
RE: `However, external users accessing it via the public share still have this problem.`
Thanks, I'll try to replicate this.

**Comment by SergeyMosin** [comment]
This issue can further be tracked in nextcloud/calendar repo: https://github.com/nextcloud/calendar/issues/4706
