### ISSUE TITLE
[Feature] let person making appointment choose location

### ISSUE THREAD

**Issue by WoutVanAelPXL** [SergeyMosin/Appointments#365]
Hello

Thank you for making this usefull nextcloud app

I would like to propose a feature:
Let person making appointment choose location with and extra field where he can enter his address. 
So it would also put the address in the agenda as location.

Greetings
Wout 🐑

**Comment by SergeyMosin** [comment]
please see this: https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-731510809
