### ISSUE TITLE
Approval in Confirmation mode

### ISSUE THREAD

**Issue by emagdybob** [SergeyMosin/Appointments#367]
1-I have problem that the confirmation goes to the user that ask for appointment and  i need to be send to the organizer to confirm not the user to confirm, any solution 
2- Can I add notes to the public page?
thanks

**Comment by emagdybob** [comment]
Sorry last question can I change in the context of the confirmation  , I need to add my own text

**Comment by SergeyMosin** [comment]
@emagdybob This currently not possible without modifying the code directly. The next best thing is to put additional info into validation and or confirmation emails:

![image](https://user-images.githubusercontent.com/10747559/195115943-398823ad-24e2-4f68-889f-aaa3c9907f6a.png)

**Comment by emagdybob** [comment]
My idea that the word "confirmed" give idea to the user that it is done but the organizer might change the acceptance for the appointments also it is better to say received or to be checked , if you guide me how to change in code it will be great.

Thanks
