### ISSUE TITLE
Cancel email button for two pages (calendar)

### ISSUE THREAD

**Issue by clem-nesta** [SergeyMosin/Appointments#372]
Hello, thanks for this good work !
Now I have 2 pages and 2 agenda in iframe.

How to integrate the good form url in the cancel mail link ?

Because with the script to detect the params_url, and the fixed form url, it always point on the same page (form).

**Comment by clem-nesta** [comment]
For me the probleme is with the redirection of embed page :
php occ config:app:set appointments "emb_cncf_YourUserName" --value "http(s)://your.domain.com/page_url?some_param_name="

To work, the mail link nead to point on the good page, right ?

So, how to make a redirection with two page url ?

**Comment by SergeyMosin** [comment]
There is no way to do it as of now for the same user. I can add `pageId` parameter to the URL in the next release but then you would still need to write an other scrip to handle it, for example:

When you set `php occ config:app:set appointments "emb_cncf_YourUserName" --value "http(s)://your.domain.com/catch_all.php?some_param_name="`

Button URL would look like this: `http(s)://your.domain.com/catch_all.php?some_param_name=xxxxxxx&pageId=yy`

then in your `catch_all.php` you would do something like this:
```php
...
$page1_handler_url = 'http(s)://your.domain.com/page1.php?some_param_name=';
$page2_handler_url = 'http(s)://your.domain.com/page2.php?some_param_name=';
$key_name = "some_param_name";
if (isset($_GET[$key_name]) && isset($_GET['pageId']) ) {
    // Email Confirm/Cancel button was clicked

   if ($_GET['pageId'] === 'y1') {
      // redirect to page1 handler
      header("HTTP/1.1 303 See Other");
      header("Location: ". $page1_handler_url . $_GET[$key_name]);
   }else{
      // redirect to page2 handler
      header("HTTP/1.1 303 See Other");
      header("Location: ". $page2_handler_url . $_GET[$key_name]);
   }
}
```

**Comment by clem-nesta** [comment]
Yes, thanks for your response !
It's exactly what I'm trying to do.

Maybe I can push the code ?

**Comment by SergeyMosin** [comment]
Not tested yet, but the change will be in the `makeBtnInfo` function:
https://github.com/SergeyMosin/Appointments/blob/8022d093eea2411f69cd50beb6738d8d7ecf4759/lib/Backend/DavListener.php#L987-L1006

Line 1004 will be changed to :
```php
urlencode($utils->encrypt(substr($uri, 0, -4), $key)) . "&pageId=" . $pageId
```

Next release is planed for the end of November

**Comment by clem-nesta** [comment]
One more time thank you for your work !
