### ISSUE TITLE
Cooperation to get anonymized user data as app developer

### ISSUE THREAD

**Issue by christianlupus** [SergeyMosin/Appointments#374]
Hello,

I am an app developer (of the cookbook app) and I recently opened this [discussion on the forum](https://help.nextcloud.com/t/generic-domain-for-app-development/147153). The idea was to provide a central domain for all app developers as a starting point. One could create sub-domains for each app to be used for documentation and other, more app-specific tasks.

One such issue was my request to have the option to collect some statistics on the installed versions. This triggered a significant push-back by some users that fear that their data is leaked out. They fear that the valuable name of Nextcloud as independent and not collecting any personal data might be at stake.

I personally think this is not too critical as I would like to collect only anonymized data and any app can do so once installed. It is just a matter of willingness.

Long story short: I would like to get the opinion on this by some other devs that might have their own agenda and pain points. Maybe this could be useful for you as well.

I will post this in a few repos in order to trigger a bit of honest discussion about the pros and cons.
Christian

**Comment by SergeyMosin** [comment]
Hi Christian,

Appointments App does not collect any user data, also there absolutely no plans for any kind of user data collection.

As for your idea for statistics about installed apps and their versions, I think you are better-off creating a separate stand alone app like "Dev Community Helper" that user can install/uninstall, which would let users help developer community by sending some anonymous usage reports. The key here is to let users decide what info, when and where it is being send.

Good luck,

Sergey

**Comment by christianlupus** [comment]
Yes, as I said, this is just a collection of information/opinions. It is not necessarily about telemetry. There are 3 main points in the forum post:

1. Registering of a common domain for whatever reason of the app devs (documentation, presentation, .... what you can think of)
2. Yes, telemetry is part of some apps in the current state (which is questionable)
3. The centralization of telemetry in a safe environment and if telemetric data can help the devs of the apps

The three points are independent. I am not telling you what to think of it. I just wanted to make you aware of the discussion and if any of the points are relevant to you and your project/app, feel free to step up.

I will close this issue as I consider you "informed". Feel free to do as you like.
