### ISSUE TITLE
Nextcloud 25 talk integration error

### ISSUE THREAD

**Issue by vithusel** [SergeyMosin/Appointments#376]
When someone books a meeting a talk invite is not sent. In the email i get a message saying check logs. 

Can you let me know where i can find logs for the app? 

Kind Regards,

Vit

**Comment by vithusel** [comment]
Not to worry. I found the logs 

See below 

{"reqId":"T5UJqrzYWJK1wltOG6mv","level":3,"time":"2022-11-15T12:09:16+00:00","remoteAddr":"Revoked","user":"Revoked","app":"no app in context","method":"GET","url":"/index.php/apps/appointments/pub/BXY3G9Df8nsMSMBb/cncf?d=1JOHMmR283osXse%2Fx07FruOz0AlnEba%2BOdPn4nAdz1G9u2AJnw1qLNVx7ud%2BKMbxwewdmxqc8Og%3D%3D&h=d4c919d9","message":"Talk room error: TalkIntegration - can not set password","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.1.1","data":[],"id":"6373817a2ab8e"}

Meetings generate when i untick set password. However if i want a password set i get this error.

**Comment by SergeyMosin** [comment]
@vithusel Thanks for the report. Bug is confirmed the fix should be available by the end of the day.

**Comment by SergeyMosin** [comment]
Fixed in v1.14.3
