### ISSUE TITLE
Talk App Integration: "Meeting Type" form field cannot be ticked 

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#377]
In Talk App Integration: The "Meeting Type" form field cannot be ticked. Is this a bug or a special contributor feature?
EDIT: We are running NC 25.0.1 (NC Hub 3)

**Comment by SergeyMosin** [comment]
Yes. Its a contributor feature. Info popup was broken. Fixed in v1.14.3
Thanks for the report.
