### ISSUE TITLE
Featurerequest: Display also "bockingpagename" on calendar entry

### ISSUE THREAD

**Issue by joesch2** [SergeyMosin/Appointments#382]
After entering the activation code for the extended features, you can use several "appointment pages" for the booking. If I now want to display the booked appointments in a calendar, I cannot see from which booking page the booking was created (in the example: calendar 1 or calendar 2), bt only the name.
![grafik](https://user-images.githubusercontent.com/18378305/203348263-bd30874c-0a08-4d34-969d-b77148551f42.png)
![grafik](https://user-images.githubusercontent.com/18378305/203348826-703782e3-756c-4b94-89cc-4e6ac1885ff7.png)
Is it possible to display not only the name of the booker in the calendar but also the name of the booking page?

**Comment by SergeyMosin** [comment]
I guess we can add an option to customize appointment title. Something like this:
`%N` = Attendee Name
`%O` = Organization Name
`%P` = Page Tag

So a template like `%N (%O)` would make a title like `Mein Name (Buchung auf Seite 1)`

I'll try to add it in the next release.

**Comment by joesch2** [comment]
That would be perfect. Thank you very much!

**Comment by SergeyMosin** [comment]
available in v1.14.5
