### ISSUE TITLE
Change duration min=10 to min=5 for appointments

### ISSUE THREAD

**Issue by SteBoun** [SergeyMosin/Appointments#384]
For appointments, the minimal duration is 10 min, but I've got 5 minutes appointments length. How to change duration for appointments ?

**Comment by SteBoun** [comment]
I change min="10" to min="5" in scr/compements/settings/TimelotSettings/SimpleAddAppointments.vue but that changes nothing

**Comment by SteBoun** [comment]
Any help ?

**Comment by mtalmont** [comment]
We want to define 5 mins appointments in weekly template.
It's woks when we use the simple mode and the workaround to overlap the appointments. 
But in weekly template, when we reserve one, the overlapped appointment will be disabled. 

If it's possible to sponsor this, let me know the details of how to do it.

**Comment by SergeyMosin** [comment]
@SteBoun Are you using "Weekly Template" or "Simple" mode ?

@mtalmont As of now multiple attendees (overlapping) appointments are only possible in "Simple" mode. There are plans to extend this feature to other modes in v2 but there is some work that hast be done in other areas before that.

**Comment by Tr-Evan** [comment]
I've succeed to change the minimum duration at 5 minutes for the appointments in "simple" mode ( in [scr/compements/settings/TimelotSettings/SimpleAddAppointments.vue](https://github.com/SergeyMosin/Appointments/blob/master/src/components/settings/TimeslotSettings/SimpleAddAppointments.vue) ). But, when I add slots of 5 minutes in calendar, he display a appointments of 10 minutes. I don't know where this is manage.

Have you a indication for help me to resolve this problem ? What is the file that manage the calendar in mode simple ?

Thanks

**Comment by cyfrax** [comment]
As the minimum ist configurable anyway, could you change the minimum time to 5 minutes? We need to give out appointments in 5 minute intervals sometimes.  Thank you very much!

**Comment by SergeyMosin** [comment]
Available in v1.14.11

**Comment by SteBoun** [comment]
thank you 😄😄😄
