### ISSUE TITLE
Show appointments for 24 weeks

### ISSUE THREAD

**Issue by Flashpok** [SergeyMosin/Appointments#385]
Thank you again for your application !
(I'm a support user)

In my business, I need to enlarge the limit to 6 months (psychologist).
If you can't implement this in the next days, can you tell me if I can temporary edit this in a code file ?
It's very important for me.
Thank you for your help !

**Comment by SergeyMosin** [comment]
I'll try to look at this over the weekend for the next version.
What do mean by "more modulations" ?

**Comment by Flashpok** [comment]
Thank you !
More choice. Possibility to encode a number (of weeks) in text field ?

**Comment by SergeyMosin** [comment]
Available in v1.14.7

**Comment by Flashpok** [comment]
Thank you !
