### ISSUE TITLE
Link for canceling don't work

### ISSUE THREAD

**Issue by RoundAboutWEB** [SergeyMosin/Appointments#386]
The link to cancel an appointment in the email is incorrect. On the one hand a wrong domain is used and on the other hand the "/" between domain and token is missing. If you enter the corrected link you will get to the login mask.

**Comment by SergeyMosin** [comment]
What version are you using ? Are you embedding the for into an iFrame ?

**Comment by RoundAboutWEB** [comment]
Version of App: 1.14.6
Version of NextCloud: 25.0.1
Version of PHP: 8.1.13
iframe: https://ticket.roundaboutweb.net/pages/telefonsupport

You can test it of your own

**Comment by SergeyMosin** [comment]
Form embedding is tricky there are examples here: https://github.com/SergeyMosin/Appointments/tree/master/tests/embedding

What is the value of your `emb_cncf_...` setting ? 

More info in the "iFrame/Embedding" section of the "Help/Tutorial" page.

**Comment by RoundAboutWEB** [comment]
OK, now it work, but this is not fine.
I hope this will be work better in the next version.

**Comment by RoundAboutWEB** [comment]
A proper solution is needed, because this way updates of Nextcloud are no longer possible!

![grafik](https://user-images.githubusercontent.com/26809494/206837724-aea25038-b1f7-4399-9634-64c9ea3aec6f.png)

**Comment by SergeyMosin** [comment]
Current solution is proper and provides multiple ways to make embedding work, there is no easy, one click magic for embedding.

1. `js-page.html` and `php-page.php` are just examples.
2. Code from **ONE** of the example files should be a part of the "parent page"([telefonsupport](https://ticket.roundaboutweb.net/pages/telefonsupport)) **NOT** nextcloud server
3.  Please remove `js-page.html` and `php-page.php` from your nextcloud server and updates will work


General flow should be some thing like this:

![Diagram](https://user-images.githubusercontent.com/10747559/206858012-bbda20bc-0f7a-4be5-95ce-a202e52d5839.jpg)
