### ISSUE TITLE
Auto Style does not seem to work anymore in NC 25.0.2

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#387]
Just updated to NC 25.0.2. Auto Style does not seem to work anymore...

**Comment by SergeyMosin** [comment]
Are you using custom image or color ?

**Comment by SergeyMosin** [comment]
![image](https://user-images.githubusercontent.com/10747559/206909740-6bdf13dc-6306-4668-9546-12d250d0d96c.png)

**Comment by Sarmingsteiner** [comment]
Oddly, after the update to NC 25.0.2. the (old) custom color was re-selected, whilst in NC 25.0.1 the default image was selected.
Thanks for the hint!

**Comment by SergeyMosin** [comment]
As of v1.14.7:`Auto Style` works as follows
- NC Preloaded backgrounds: full support
- Custom colors: full support
- Custom images: fallback to default NC image (clouds), custom images do not work for public  pages because of access permissions
