### ISSUE TITLE
[feature] recurring appointments

### ISSUE THREAD

**Issue by matteoventuri7** [SergeyMosin/Appointments#39]
Hi, It would be convenient to have the possibility to mark an appointment as a recurring one so that it is automatically repeated from week to week.

**Comment by SergeyMosin** [comment]
Recurrence for individual appointments could be a little to complicated but a self replicating weekly schedule should be doable.

**Comment by matteoventuri7** [comment]
Ok for self replicating.
Thanks.

**Comment by jinnko** [comment]
I've been able to create the calendar items outside the addon and I see those come up in the form as expected.  I was hoping that using the regular calendar recurring feature would work, but unfortunately it didn't.  I worked around this by using Thunderbird to copy all appointment slots for the week.

@SergeyMosin - have you considered making use of the standard recurring calendar items feature, especially as it's a well managed feature of calendars in general?  It should help avoid having to build such features within the addon, and people could use whatever calendar interface they prefer to manage their available slots, so long as they set the hook correctly (which I assume is the category field together with a tentative status?).

**Comment by SergeyMosin** [comment]
Recurrence is something to consider for the future, maybe some kind of advanced settings.

> I assume is the category field together with a tentative status?

There is also ORGANIZER with SCHEDULE-AGENT=CLIENT otherwise email notifications might get messed.

**Comment by SergeyMosin** [comment]
See https://github.com/SergeyMosin/Appointments/issues/100#issuecomment-653780651
