### ISSUE TITLE
[Feature Request] When "In-person" is the Meeting Type, get physical address

### ISSUE THREAD

**Issue by WNYmathGuy** [SergeyMosin/Appointments#390]
I noticed while trying to test the appointments as I was going to use it for real, the calendar appointment could have a person booking an in-person meeting getting the option to enter their chosen address. When a Nextcloud account holder does a service like cleaning, carpentry, furniture moving, etc. the location is dependent on the person requesting the booking, not the business location of the Nextcloud account holder.

Also, along the same lines, I noticed that despite entering a name for the booking and choosing the "Online (audio/video)" meeting type, the Talk room brings the client in as "Guest". Can't the parameter they gave for their name be passed along to the Talk room?

**Comment by SergeyMosin** [comment]
> option to enter their chosen address

Please see this https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-731510809

> Talk room brings the client in as "Guest"

Talk integration improvements are on the road map for v2
