### ISSUE TITLE
Duration selection does not work anymore

### ISSUE THREAD

**Issue by hurgelwurz666** [SergeyMosin/Appointments#391]
Hello, I have the following problem since the last update:
I have set up the app so that you can book an appointment every hour. For this appointment you can then select a duration between 1 and 8 hours. Until the last update this worked fine.
Since the last update, it is so that the selection of the appointment only works in the preview. I can click on "Select date and time" and then the selection of the duration opens. In the live system I can click on "Select date and time". When I click on a time, the window does not close and the duration field is not displayed.
I am using Nextcloud 24.0.5 and Appointments 1.14.7.
Thanks for your help
![2023-01-04 10_57_51-Termine - NextCloudPi – Mozilla Firefox](https://user-images.githubusercontent.com/47058806/210530975-1d24a112-6bbd-495b-a5ab-5a49fc3eee80.png)

**Comment by SergeyMosin** [comment]
Bug confirmed.  A fix will be released ASAP.
Thanks for the report.

**Comment by SergeyMosin** [comment]
Fixed in v1.14.8
