### ISSUE TITLE
No email is sent when appointment is deleted completely

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#399]
Whilst there is an email sent when we change the time of a booked appointment (both to us and to the customer), no email is sent when we delete an appointment completely.

**Comment by SergeyMosin** [comment]
Can you please check if you have the `Deleted` option enabled in Email Settings:
![image](https://user-images.githubusercontent.com/10747559/215361106-7db9139f-72c6-4708-a43d-fa376bd4679b.png)

**Comment by Sarmingsteiner** [comment]
Yes, we have checked it before. Btw, we skip the validation step.

**Comment by SergeyMosin** [comment]
Bug is confirmed, session BackendUtils::APPT_SES_KEY_HINT related

Thanks for the report.

**Comment by SergeyMosin** [comment]
fixed in v1.14.11
