### ISSUE TITLE
Be able to create longer timeslots than 1 hour

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#4]
Add the ability to create longer timeslots.

A 2 hour slot would be excellent as well.  Or make it configurable on what you need.

**Comment by fancycode** [comment]
:+1: for making if configurable

**Comment by SergeyMosin** [comment]
FYI you can arrange and extend appointments(events) anyway you like in the calendar and the changes will be reflected in the booking form. MAX DURATION IS 2 HOURS.

![arrange_appointmets](https://user-images.githubusercontent.com/10747559/75376537-37a72780-589e-11ea-99f5-8fccb2635304.png)

**Comment by nolens** [comment]
@small1 
This is fixed in version 1.10
please close this issue.

**Comment by lars-becker** [comment]
@SergeyMosin is there a reason for the two hour limit? I can think of a lot use cases that require more than two hours.

**Comment by SergeyMosin** [comment]
2 hour limit is actually only enforced on pre-v1.4.* versions. You can adjust appointments' duration in the calendar app to anything you want. I can also give the "Schedule Generator" a grater range in the upcoming releases - 4 hours perhaps.
