### ISSUE TITLE
Mobile browser does not work

### ISSUE THREAD

**Issue by proinovest-gs** [SergeyMosin/Appointments#400]
Hello all,
when the appointment selection link is opened on an iPhone, Android (default brower), no time slot can be selected.
The selection menu does not open. Does anyone know how to fix the problem?

**Comment by SergeyMosin** [comment]
I can not reproduce, what version are you using ?

**Comment by proinovest-gs** [comment]
Hello Serge,
i use the current version 1.14.10.
On the Desktop Device (Linux/Windows) it works fine, only on the mobile devices it does not open the selection menu for the appointments. Unfortunately, I have no explanation for this.

Greetings,
George

**Comment by SergeyMosin** [comment]
I have tried the link on Android (Chrome, FireFox, Opera and OperaMini) and the selection menu opens, I'll try on an iPhone later.

If you get a chance can you try in "incognito tab" , highly unlikely but there might me something going on with browser cache.

Android Chrome screenshot:
![image](https://user-images.githubusercontent.com/10747559/216315754-47136732-f94d-48e4-b8e1-d255da96648f.png)

**Comment by SergeyMosin** [comment]
The provided link works on an iPhone as well...
![image](https://user-images.githubusercontent.com/10747559/216619807-8d763be8-5145-4a24-9217-46b45378850c.png)
