### ISSUE TITLE
[Bug] Overlap of slots from same day - different month

### ISSUE THREAD

**Issue by Jaxom99** [SergeyMosin/Appointments#401]
Hello,

We are satisfied users of this app to manage multiple appointment schedules, on various agendas. We found a bug, that seems to come frome the "symmetrical months" of february and march : the slots for Thursday March 16th are shown in the public link for the day of Thursday **February** 16th. And the date of March 16th is not displayed on the form, but the next slots in april are shown (we use a 12-week window).

We use the '"external" mode with two nextcloud calendars. I can share the public link if needed.
```
Nextcloud Version: 24.0.7
Appointments Version: 1.14.10
```
Settings dump : https://bin.infini.fr/?36b30e7e2833977f#H1hUocjdd79TDadoAkQGcbTpa62BTQpaDufRVL9HCFUn

Is this behaviour known? (I did not find it in previous github issues). What other data would you need to try and fix it?

Thanks for your time and attention, I hope this can move forward and stay available to help as I can.

**Comment by SergeyMosin** [comment]
Can you please send me ( sergey [at] srgdev.com ) the '.ics' file for one of the misplaced March 16th events. '.ics' files can be download by clicking "export" in the "three dot" menu.

![image](https://user-images.githubusercontent.com/10747559/217648831-78ef8eae-a51f-477a-a75e-b52f7317e822.png)

**Comment by Jaxom99** [comment]
Thank you, I just sent it. It turns out it is a repeated event, that has been created via Thunderbird.

**Comment by Jaxom99** [comment]
UPDATE : I pursued investigations, and here are my findings. The bug is more precisely happening when two following slots are exactly one month apart (well, with the same day number)..

If I have a Feb15 16:00 slot then a March15 10:00 slot, the two of them will appear on the Feb15 on the form (but when validated, the resulting apointment from 2nd slot will be on March15).

And if I add a new slot inbetween, say March14 10:00, then all three slots are correctly displayed on the form :open_mouth:

**Comment by SergeyMosin** [comment]
@Jaxom99 Thank you for details. I'll definitely take a good look at this over the next couple of days and will include the fix in the next release.

**Comment by SergeyMosin** [comment]
fixed in v1.14.11

**Comment by Jaxom99** [comment]
I pulled the upgrade and... YES! :smile: The fix is confirmed on my setup, I can close this.

:tada: thanksss
