### ISSUE TITLE
booked appointment buffers take conflict calendar not into account

### ISSUE THREAD

**Issue by tessus** [SergeyMosin/Appointments#403]
I am using the Appointments app 1.14.11 on Nextcloud 24.0.10.

`Check for conflicts in… ` -> `Default calendar`
`Booked Appointment Buffers` -> `Before / After:` 30 minutes

I have already an appointment on day X from 16:00 (4pm) to 16:45 (4:45pm). My appointment time slots in the template are Monday to Friday 10:30 to 18:00 every 30 minutes.

<details>
<summary>expand to see template here</summary>
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/223439/221329287-479e9b46-ead7-4468-b9b7-61fb14ede30c.png">
</details>

Now, when I go to the public page to book an appointment for day X, I see these options (the screenshot starts at 2:30pm, there are all the other time slots before that available too):

<img width="341" alt="image" src="https://user-images.githubusercontent.com/223439/221329375-09ecd4d5-99b6-491c-bf9e-1a7481c60434.png">

As you can see I can book an appointment at 3:30 for 30 minutes, which means it will be back-to-back with my already booked appointment at 4pm. So the buffer of 30 minutes is not honored.
The same is true for 5pm. There is only a 15 minute gap between 4:45pm and 5pm, thus the 30 minutes are not honored there either.

I really want to avoid back-to-back meetings, but currently this is apparently not avoidable.

I also tried to increase the buffer to 60 and 120 minutes, but that didn't help either.

**Comment by tessus** [comment]
@SergeyMosin is this working as designed? I just need to know, if you consider fixing this. If not, I will have to find a different solution.
Don't take this the wrong way. I am not trying to pressure you. I just need to know, so that I can plan my next steps.

**Comment by tessus** [comment]
> Is this appointment booked via this app ?

No, this appoinyment was already in the calendar and was originally created by the Nextcloud Calendar app.

> If the appointment / time-slot is "booked" via some other method, then this is a duplicate of https://github.com/SergeyMosin/Appointments/issues/328 which will be fixed, but I do not have a timeline for that.

Ok, thanks for the info. So you can mark this one as a duplicate of #328 and close it.

Unfortunately this makes this app not very useable (for me), because it is also necessary to take appointments into account that are currently in my calendar.

**Comment by SergeyMosin** [comment]
https://github.com/SergeyMosin/Appointments/issues/328#issuecomment-1501206353
