### ISSUE TITLE
Proposal - Contributor key for issuers

### ISSUE THREAD

**Issue by SamirSaidani** [SergeyMosin/Appointments#405]
I'm experimenting the appointments app, which is way better than the nextcloud one in term of functionalities, but the UX/UI design is pretty confusing. I would love to see the features of this one with the UX/UI with the nextcloud one.

I've seen that there is a kind of contributor incentive to use premium feature. Interesting. My proposal is to allow issuers to also get a contributor key: filling an issue is a contribution per se, in my opinion. We are reporting bugs/features request/proposals and hence contributing to improve the app.

Anyway, thanks a lot for this nice app !

**Comment by SergeyMosin** [comment]
Please contact me ( sergey [at] srgdev.com ) with a bit more info about your use case. Additionally to [PR](https://github.com/SergeyMosin/Appointments/pulls) contributors, most small not-for-profit and STEM for kids educational organizations do get a free key if they ask for it.

Sergey
