### ISSUE TITLE
NC26 compatibility: Blank app page

### ISSUE THREAD

**Issue by mkrecek234** [SergeyMosin/Appointments#406]
Installing app on NC26, the app icon is aded to the topmenu. Clicking on it shows a blank page.
The calendar iapp integration though works.

**Comment by SergeyMosin** [comment]
Bug confirmed, fix is planned for the next release.

**Comment by SergeyMosin** [comment]
fixed in v1.14.12

**Comment by mkrecek234** [comment]
Thank you @SergeyMosin for fixing that fast - confirmed to be working.
