### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by yrammos** [SergeyMosin/Appointments#41]
@SergeyMosin thanks for a most promising and long-overdue app! Any plans to add time zone support? Thanks.

**Comment by SergeyMosin** [comment]
Can you be more specific?
When adding appointments you can choose either the "floating" time or the calendar's timezone (and you can change calendar's timezone in the calendar settings).
There is also a small paragraph in the [help section](https://htmlpreview.github.io/?https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php#srgdev-sec_timezone) about it.

Thank you

**Comment by yrammos** [comment]
This is functional enough @SergeyMosin but a drop-down list of time zones in the booking form would be even better. This is assuming that the time-zone data would be fully up-to-date, e.g. drawn from [CLDR JSON](https://github.com/unicode-cldr/cldr-json)), otherwise indeed it might be better to leave it all up to the NC Calendar. Thanks again!

**Comment by SergeyMosin** [comment]
I am closing this, but it should be considered when/if implementing #25 or #24
Thanks
