### ISSUE TITLE
Timezone weirdness: one person received western european timezone, one received central european timezone

### ISSUE THREAD

**Issue by ccoenen** [SergeyMosin/Appointments#411]
I use appointments in the simple mode, and I created slots in "my" timezone, CEST (central european summertime, or UTC+1).

One of my students booked such an appointment, and we each receiverd a confirmation email.
* She received a confirmation for 08:45 WESTERN european summer time (UTC+0)  
  ![email from the attendee's perspective](https://user-images.githubusercontent.com/124909/230328351-4d077369-b191-421d-be6f-f330675223f0.png)
* I received a confirmation for 09:45 CENTRAL european summer time (UTC+1)
  ![screenshot from the organizer's perspective](https://user-images.githubusercontent.com/124909/230328098-732a0307-55f7-488a-bd0f-1cb08ad14b3a.png)

Both are, of course, the same instant, but it is really easy to miss the timezone. Furthermore, we can't really understand *why* she would have gotten a different timezone at all?

**Comment by SergeyMosin** [comment]
Visitor timezone is take from the visitor's browser at the time of booking. Your student might have wrong timezone set on the computer. In any case, you can enable timezone display on the booking page `Settings > Customize Public Page > Advanced Settings > Show Timezone`. Additionally, for V2 there are plans to have a "Timezone Selector" as per #370

**Comment by ccoenen** [comment]
Thanks for looking at it. This sounds like a reasonable explanation and is likely not a bug then :-)
