### ISSUE TITLE
Time Slots/Appointments are not shown

### ISSUE THREAD

**Issue by criro** [SergeyMosin/Appointments#413]
Hello, 
I set up a calender, defined some time-slots and made them available ("online") but there is nothing shown on the public site. 
Nextcloud 24. Seems, that I am not the only one;-)
https://help.nextcloud.com/t/probleme-mit-der-verwendung-der-appointment-funktion/128769

**Comment by SergeyMosin** [comment]
Are there any errors in NC logs or browser console ? Can you send me ( sergey [at] srgdev.com) the link to the public page.

**Comment by criro** [comment]
Thats very strange, it works now, yesterday I tried with different users and different browsers on my mac, thanks for the quick reaction.
