### ISSUE TITLE
Missing email display name 

### ISSUE THREAD

**Issue by liaham** [SergeyMosin/Appointments#414]
## What I have expected:

When receiving an email via appointment app I would expect to see the same email display name as set in nextcloud administration area.

Let' s say you entered on administration » Design  in field `Name` your company name. Then you will get nextcloud server emails in your inbox with `Company Name <mail@address.tld>`.

## What I have observed instead:

When an email from appointment app comes in the `Company Name` is missing ending up in: ` <mail@address.tld>`.

## How to solve the problem:

To be honest, I don't know exactly since I am not familiar with nextcloud codebase and php. 

But the problem could be in the `sendMail` method. There is  a [NewUserMailerHelper](https://github.com/nextcloud/server/blob/master/apps/settings/lib/Mailer/NewUserMailHelper.php) where it looks good for me since it uses:

```php
$message->setFrom([$this->fromAddress => $this->themingDefaults->getName()]);
```
But I don't know whether this method will be used when an email via appointment app is send.

Maybe someone with nextcloud and php experience is  able to investigate it further.

**Comment by SergeyMosin** [comment]
There would be two options for the name:
1. Use system-wide name provided by `$this->themingDefaults->getName()`
2. Use the name from `Appointments > User/Organization Info > Name` setting

New code would go here:
https://github.com/SergeyMosin/Appointments/blob/90cb5e66c90b037a45018e98d9a1cb45aeffc65f/lib/Backend/DavListener.php#L273-L277

**Comment by liaham** [comment]
I would prefer option 2. 

How about using it this way: 

`User Name » Company Name <mail@address.tld>` if a Company Name is given and `User Name <mail@address.tld>` if not?

This would give the receiver of the appointment mail both who will be the conversational partner and from which company is he or she.

**Comment by SergeyMosin** [comment]
Added in v1.15.2
