### ISSUE TITLE
Customize public page and email

### ISSUE THREAD

**Issue by fadedhero** [SergeyMosin/Appointments#416]
Can I edit the templates\public\form.php to customize the public page form? Or why do we have a templates folder? 
Same question goes to lib/Email/CustomEmailTemplate.php. How does it work? Do you have a documentation for this?

Thanks

**Comment by SergeyMosin** [comment]
`templates` folder is a part of  standard NC App architecture https://docs.nextcloud.com/server/latest/developer_manual/app_development/intro.html#app-architecture

The `lib/Email/CustomEmailTemplate.php` is/was only used for testing. This https://github.com/SergeyMosin/Appointments/blob/master/lib/Email/EMailTemplateNC20.php template is used in production.

The template is instantiated here: https://github.com/SergeyMosin/Appointments/blob/5d7bedbea02951d6532b068117131fe27d1ed5e4/lib/Backend/DavListener.php#L1149-L1173

As you can see, you can provide your own template class via `mail_template_class` config as described here: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#modifying-the-look-of-emails-beyond-the-theming-app-capabilities

I hope this helps.

**Comment by fadedhero** [comment]
Helps alot! Thanks a bunch
