### ISSUE TITLE
Error to delete Talk room when click 'Cancel' appointment  

### ISSUE THREAD

**Issue by kevinkuan1969** [SergeyMosin/Appointments#418]
Nextcloud 26.0.2 
Appointment 1.15.0

The setting to remove room from Talk if the appointment is cancelled:

![image](https://github.com/SergeyMosin/Appointments/assets/80019930/1aa177a2-97ea-4e8d-9239-813b19fc07cc)

The error message when click cancel in the email as well as the log file:

![image](https://github.com/SergeyMosin/Appointments/assets/80019930/f333fd73-6974-450d-9f42-e555d16a58f1)
![image](https://github.com/SergeyMosin/Appointments/assets/80019930/b9f91c10-05f8-4f2c-869f-83fd8f4c852d)

**Comment by kevinkuan1969** [comment]
[index] Error: Exception: Call to undefined method OCA\Talk\Room::deleteRoom() in file '/var/www/nextcloud/apps/appointments/lib/Backend/TalkIntegration.php' line 265 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1056
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

Caused by:

Error: Call to undefined method OCA\Talk\Room::deleteRoom() at <<closure>>

 0. /var/www/nextcloud/apps/appointments/lib/Backend/DavListener.php line 647
    OCA\Appointments\Backend\TalkIntegration->deleteRoom()
 1. /var/www/nextcloud/apps/appointments/lib/Backend/DavListener.php line 59
    OCA\Appointments\Backend\DavListener->handler()
 2. /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php line 86
    OCA\Appointments\Backend\DavListener->handle()
 3. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 4. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 5. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 87
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
 6. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 99
    OC\EventDispatcher\EventDispatcher->dispatch()
 7. /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php line 1479
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
 8. /var/www/nextcloud/apps/appointments/lib/Backend/BCSabreImpl.php line 1403
    OCA\DAV\CalDAV\CalDavBackend->deleteCalendarObject()
 9. /var/www/nextcloud/apps/appointments/lib/Controller/PageController.php line 475
    OCA\Appointments\Backend\BCSabreImpl->deleteCalendarObject()
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Appointments\Controller\PageController->cncf()
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
13. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
14. /var/www/nextcloud/lib/base.php line 1056
    OC\Route\Router->match()
15. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /index.php/apps/appointments/pub/UkwSf5r6AYaQ/cncf?d=0MzkfNlyLtYEkSVEna8T5lwoRXtMX6KW3G%2BdLl74wZF%2FwTeYxp3lDZmKB5kGUGWt6NqW13jJ4Fw%3D%3D&h=fbca1967
from 161.142.78.45 at 2023-05-12T06:51:07+00:00

**Comment by SergeyMosin** [comment]
Bug is confirmed. Fix will be released ASAP.

@kevinkuan1969 Thank you for the report.

**Comment by SergeyMosin** [comment]
Fixed in v1.15.1

**Comment by kevinkuan1969** [comment]
Great and thanks
