### ISSUE TITLE
Make the “help/Tutorial” link an on/off Toggle.

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#42]
Not knowing how to get rid of the instructions made it really awkward to continue setting it up. I ended up clicking on the calendar selection ellipsis and reselecting my calendar.
It could be made to toggle to the Public Page.

**Comment by SergeyMosin** [comment]
Sounds reasonable for next release.

**Comment by SergeyMosin** [comment]
Done in v1.4.0
