### ISSUE TITLE
[Feature Request] Up to 5 Questions for the user who books an appointment for further information

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#420]
For a better prepairing for an appointment it would helpful for me, if i can ask the interessted person some questions about the appointment. Best i'd get the information i get via e-mail after confirming the appointment and if it possible it would great it would add in the calendar entry.

**Comment by SergeyMosin** [comment]
Please take a look here: https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-721103321 and https://github.com/SergeyMosin/Appointments/issues/223#issuecomment-975359734

**Comment by SergeyMosin** [comment]
Tracked in #25
