### ISSUE TITLE
Feature request: default appointment length; appointment length choosen by visitor

### ISSUE THREAD

**Issue by wkmatzek** [SergeyMosin/Appointments#423]
Hi,
using the external calendar mode, it could be cumbersome to have to define free appointment slots one by one.
In that case it'd be nice to define a default appointment length within the app and then define a certain time range for appointments in the source calendar. Sometimes it would also be cool if the visitor could book different appointment lengths based on a service category (ideally choosen by mean of a menu).

**Comment by SergeyMosin** [comment]
> cumbersome to have to define free appointment slots one by one

Recurring events are supported in `External Mode`. See the Calendar App docs for more info...

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/9c892140-c67d-4497-8a78-214a2a1f6a4d)

> it would also be cool if the visitor could book different appointment lengths based on a service category

This could potentiality be accomplished  via a `Directory Page`, more info:
- https://github.com/SergeyMosin/Appointments/issues/21#issuecomment-696738211
- https://user-images.githubusercontent.com/10747559/168083131-5e6c1371-4b3d-4727-9e31-f18771dc78bb.png
