### ISSUE TITLE
How import events that have not been created with the Appointement form?

### ISSUE THREAD

**Issue by Flashpok** [SergeyMosin/Appointments#424]
Hello,
is it possible to import events that have not been created with the Appointement form? This would allow me to automatically send an email reminder to the customer I've added directly to my Nextcloud calendar without going through the Appointement form. 
Thank you for your help.

**Comment by SergeyMosin** [comment]
Please see `External` Mode. There is also additional info in the `Help/Tutorial`.

**Comment by Flashpok** [comment]
Hello,
thank you very much for the link.
But I don't understand how I can transform an existing event in a Nextcloud calendar into an "Appointment". How do I pass the person's email address so that they get the reminder? (this is the function I'm interested in)

**Comment by SergeyMosin** [comment]
Reminders are managed `Appointments > Settings > Reminders`

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/10285fa1-1176-4340-baa4-ceac62d882df)
