### ISSUE TITLE
Booked appointments to include some detail - request

### ISSUE THREAD

**Issue by OutbackMatt** [SergeyMosin/Appointments#425]
Awesome product.
I've been playing a round a bit and today contributed to unlock the extra features.

Loving it. I've been looking for this type of solution for a while.

I'd like that when the appointments are made and a talk room is created with password etc, that this detail is listed in the appointment description, including the links. The same detail that is sent to whomever makes the appointment.

I access my Nextcloud via CalDAV, and use the calendar in my email program. New appointments show fine, but there is no detail in the description.

**Comment by SergeyMosin** [comment]
Hi @OutbackMatt ,

> and use the calendar in my email program

If it is not a secret what `email program` do you use ?

If you create a test event from NC Calendar App (not from Appointments) with some text in the `Description` field, does that text show up in your email program ?

**Comment by OutbackMatt** [comment]
I use a mix of Outlook and Thunderbird for email, however my CalDAV is also accessible from my iPhone and perhaps other places like my website, or my roundcube installation.

If I create an event in Nextcloud Calendar, it works as expected

<img width="320" alt="image" src="https://github.com/SergeyMosin/Appointments/assets/7231493/a9b92ac9-0e53-4a83-967a-b31508f47e3d">

**Comment by OutbackMatt** [comment]
Awesome - thanks
