### ISSUE TITLE
v1.15.1 - ICS sending to organizer ?

### ISSUE THREAD

**Issue by J-C-P** [SergeyMosin/Appointments#426]
Hi,

The attendee receive the ICS (and it is great !! :-) ) but the inviter does not. Is it normal ?
Could it be a new option to also send the ICS to the organizer ?

Thanks a lot for your great work !

Have a good day :-)

**Comment by SergeyMosin** [comment]
Inviter/Organizer does not receive ICS files because the event are already created (and updated) in the organizer's calendar automatically. Sending ICS files to the organizer might actually cause more confusion and create duplicated events.
