### ISSUE TITLE
To change the translation of "Name" in french form

### ISSUE THREAD

**Issue by Flashpok** [SergeyMosin/Appointments#427]
Hi, is it possible to change "Nom complet" par "Prénom et Nom" in the appointment form ?
Thank you

**Comment by SergeyMosin** [comment]
Translations are provided by the [Nextcloud community on Transifex](https://www.transifex.com/nextcloud/nextcloud/dashboard/) and I include the latest translations with every release.
It is possible to edit translations files https://github.com/SergeyMosin/Appointments/tree/master/l10n locally but they will be overwritten during updates.
