### ISSUE TITLE
Is it running with nextcloud V27?

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#428]
Hello, i have a managed Nextcloud and my service provider told me, that the V27 seems to run more stable than V26 - so he plans to update my Nextcloud to V27. Does Appointments work with the V27?

**Comment by OutbackMatt** [comment]
yes it does

**Comment by stefan-franz** [comment]
Ok. Iit would be helpful if it were updated here
https://apps.nextcloud.com/apps/appointments

Can the Sergey conform it, that the update and installation process works really without tweaks?

**Comment by stefan-franz** [comment]
@OutbackMatt 
Would you please tell me, if you have running it on V27
If yes, are there any tweaks neccessary or can i install it over the app install function in the nextcloud admin are?
I have no access to the files, because i have a managed cloud from a provider. 

Thanks in advance
...can't reach Sergey....

**Comment by SergeyMosin** [comment]
I have not tested the app with NC27 yet. I am planning to do so over the weekend. I'll post more here after testing.

**Comment by OutbackMatt** [comment]
Yes, I currently run Nextcloud version 27.0.0
I have made no tweaks, only configuration settings from the GUI provided

**Comment by SergeyMosin** [comment]
NC v27 is supported as of v1.15.2
