### ISSUE TITLE
Change “Add Appointments” to “Add Appointment Slots”

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#43]
This is not actually about adding appointments, it is about adding a place for appointments to be.
I was actually very confused by this title. This simple change will make things much clearer.

**Comment by SergeyMosin** [comment]
How about "Create Appointments" ?

**Comment by BuilderGuy1** [comment]
My thought is that these are not actually "appointments".
They are "slots" where appointments would be made.
I suggested "Appointment Slots" as it is a common phrase and people understand what it means. 
Purhaps you could use "Create Appointment Slots"

**Comment by SergeyMosin** [comment]
Changed in v 1.4.0
