### ISSUE TITLE
Move “Number of Appointment slots” to the Schedule Generator area

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#44]
Move the “Number of Appointment slots” option to the Schedule Generator area. It makes logical sense to be there.

**Comment by SergeyMosin** [comment]
Not sure if I follow, in the latest version appointment slots are added on  **per day basis** in the Schedule Generator section. Some people do half-day Fridays or no appointments on Wednesdays, etc...
