### ISSUE TITLE
[Feature] Schedule Generator: Add multiple break times

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#45]
In the Schedule Generator, add the option to add multiple break times. This should be set relative to an existing appointment slot. For example: “Add Break after [ 2nd ] slot”.
The content in the braces [] should be a drop down.

**Comment by SergeyMosin** [comment]
Which version are you using ?? In the Schedule Generator interface you can drag appointment slots up and down to make as many breaks as you want.

**Comment by BuilderGuy1** [comment]
V1.1.10
Yes, I agree it could be done by sliding the slots around.
However, having a setting would allow every day to be set at once in a single place rather than having to adjust slots to the same brake times multiple times for the very same break times.
I think the Slot Sliding feature would be best used for one-off adjustments that are not universal for the entire week/calendar period.

**Comment by SergeyMosin** [comment]
I see, maybe the name is confusing, but there is the "**Copy to Next**" option (see the screenshot) which copies/duplicates slots into to the next day at the same position, assuming the next day does not have any slots already.

![add_appt_next](https://user-images.githubusercontent.com/10747559/78911790-d0f85a80-7a54-11ea-945c-138c2d308c57.jpg)

**Comment by BuilderGuy1** [comment]
I understand your process now.
It appears what I am suggesting is a more compressed workflow.
The workflow you have has 3 steps:
1) Set "Schedule Generator" settings
2) Adjust times/Add break times by dragging slots up/down
3) Duplicate the day's slots by clicking "Copy to Next" day option in ellipsis menu

My suggestion would combine steps 1 & 2.
It could be done either way but the user should be informed what the process is.
I do recommend adding my 3 step summary of the process to step 3 of the Tutorial.

**Comment by SergeyMosin** [comment]
The help/tutorial section has been updated in v1.4.8
[wontfix] for auto-breaks
