### ISSUE TITLE
* Required fields Indicator *

### ISSUE THREAD

**Issue by taziobaker** [SergeyMosin/Appointments#453]
This is great work.
Would it be possible to have an indicator of required fields?
even from the main fields (like: Date & Time, Full Name, Email, Phone) and the required custom field(s) added ones as well.

maybe an * after the label
and a little explainer as a footnote : * required

**Comment by SergeyMosin** [comment]
See https://github.com/SergeyMosin/Appointments/issues/65#issuecomment-619379953

Closing as duplicate
