### ISSUE TITLE
i : Information helper Panel Load

### ISSUE THREAD

**Issue by taziobaker** [SergeyMosin/Appointments#454]
Is it also possible to load the information helper into the right panel without having to loose the current setting?

This isn't clear. Sorry, here is an example:
When you click on "Manage Appointment Slots", there is a panel ("Calendars and Schedule") that shows up between the left menu and the "Public Page Preview"
Let's say you are filling out the settings, but get confused about one of the settings.
Luckily there is an i besides it and you click it to get clarity.
Actually, you are sent to the whole information page and loose the settings you had already started filling.

Would it be possible to have the i content show up next to the "Calendars and Schedule" so one may continue to fill the setting without loosing parameters already filled?

**Comment by SergeyMosin** [comment]
Not applicable to v2
