### ISSUE TITLE
Appointment Public Page header says "Nextcloud | Appointments"

### ISSUE THREAD

**Issue by taziobaker** [SergeyMosin/Appointments#456]
Is it possible to change this issue?

I customized the logos of our NextCloud instance, but the appointment public page booking shows "Nextcloud | Appointments".

Looking forward for anyone's feedback to remove this wording.

**Comment by SergeyMosin** [comment]
`Appointments > Settings > Customize Public Page > Advanced Settings > Page Header Title`

**Comment by taziobaker** [comment]
Just found it out by thinkering... very sorry to waste your time.

**Comment by taziobaker** [comment]
Just found it out by thinkering... very sorry to waste your time.
