### ISSUE TITLE
Help formating 1) "tag": "select", & 2)"type": "number"

### ISSUE THREAD

**Issue by taziobaker** [SergeyMosin/Appointments#459]
Anyone knows how to:
1) put a placeholder on the JSON custom field "tag": "select"?
2) format the number inputted into some type of currency (ei: "$1,409.98")?

Thank you in advance,

**Comment by JocelynDelalande** [comment]
I think neither are possible for now.

**Comment by SergeyMosin** [comment]
This feature is not planned.
