### ISSUE TITLE
“Public Page” options require 2 clicks to activate

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#46]
Both options under the “Public Page” ellipsis must be clicked twice before they actually activate.

**Comment by SergeyMosin** [comment]
What browser are you using? Can you check the console for any errors or warnings if you have time.
Thank you.

**Comment by BuilderGuy1** [comment]
Safari 13.1.
I'll check the console as soon as I can and get back to you.

**Comment by BuilderGuy1** [comment]
Here is a screen shot of the console captured while going back and forth between "Share Online" and "Stop Sharing".
Both only required ONE click this time.
Before it was very difinitive and repeatable that they both required TWO clicks to work.
Also, I am running NextCloud 17.0.5SNAP1

![Appointments_1 1 10_NC17 0 5snap1](https://user-images.githubusercontent.com/22668948/78916224-0182c900-7a42-11ea-8f37-a604671fc8fa.png)
