### ISSUE TITLE
Disable decline Button

### ISSUE THREAD

**Issue by SantaClausz** [SergeyMosin/Appointments#469]
First off great App! I use it for clients to book appointments. Sometimes clients cancel their appointment just a few hours before it starts. Is there a way to disable the decline option in the confirmation Email and in the reminder email, so that once the appointment is booked, it can only be cancelled by direkt Email to our company?

Thank you for you efforts!

**Comment by Jolopu** [comment]
Fully editable email templates would give us the option wether to include the cancellation link.

**Comment by SergeyMosin** [comment]
Duplicate #470
