### ISSUE TITLE
[Feature] Branding Background for Public Page

### ISSUE THREAD

**Issue by BuilderGuy1** [SergeyMosin/Appointments#47]
Add the option to upload and display a background picture on the Public Page for Branding and Beautification purposes.

**Comment by SergeyMosin** [comment]
Looks doable, maybe a "Custom Style" filed in the "Customize Public Page" section.

**Comment by SergeyMosin** [comment]
General style override is available in version 1.4.0 ``Customize Public Page > Advanced Settings > Style Override``
