### ISSUE TITLE
Iframe in wordpress website don't work

### ISSUE THREAD

**Issue by fcreach** [SergeyMosin/Appointments#473]
Hello, 

I am sorry for this request, but I was not able to resolve my problem by following the documentation and recommendations read.

I'm trying to integrate appointments into an iframe with a WordPress site.

The appointment url: https://docs.myservernextcloud.net/index.php/apps/appointments/embed/gwiLZ%2BaPwbDlRsk%3D/form

The website url: https://www.soudomaine.domaine.fr
The page of the website url: https://www.soudomaine.domaine.fr/index.php/page-d-exemple/
My nexcloud user: toto

I did this:
On nextcloud `php occ config:app:set appointments "emb_afad_toto" --value "www.soudomaine.domaine.fr"`
And `php occ config:app:set appointments "emb_cncf_toto" --value "https://www.soudomaine.domaine.fr/index.php/page-d-exemple/?some_param_name="`

On wordpress. In the header `
_<script type="text/javascript" async="async">
var urlRDV = window.location.href.includes('index.php/page-d-exemple/');
if (urlRDV) {
  window.addEventListener('DOMContentLoaded', function() {
    var src = "https://docs.myservernextcloud.net/index.php/apps/appointments/embed/gwiLZ%2BaPwbDlRsk%3D/form";
    var appointmentParam = "apphash"

    function getUrlVars() {
      var vars = {};
      var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
        vars[key] = value;
      });
      return vars;
    };

    var params = getUrlVars();
    var apphash = params[appointmentParam];
    var paramsConcat = Object.entries(params).reduce(function (prev, curr) {
      if (curr[0] === appointmentParam) {
        return prev;
      }
      prev = prev.concat("&",curr[0].toString(),"=",curr[1].toString());
      return prev;
    }, "");

    if (apphash) {
      src = src.slice(0, -4).concat('cncf?d=').concat(apphash,paramsConcat);
     }

    var myIframe = document.getElementById('myAppointmentFrame');
    myIframe.src=src;
  })();
}

</script>_
`

On the page `<iframe id="myAppointmentFrame" title="Appointment form" frameborder="0" style="height: 100rem; width: 100%;" src=
"https://docs.myservernextcloud.net/index.php/apps/appointments/embed/gwiLZ%2BaPwbDlRsk%3D/form" name="myAppointmentFrame"></iframe>`

In the iframe, the message "docs.myservernextcloud.net does not allow connection." appear.

Can you help me please ?
Thank you

**Comment by SergeyMosin** [comment]
@fcreach Can you send me the real URLs to sergey [at] srgdev.com

**Comment by fcreach** [comment]
Thank you @SergeyMosin . I have send the message.

**Comment by fcreach** [comment]
@SergeyMosin. I have resolved my issue. It was because the first time i have inject the occ line the url was wrong. And the next time when i injected the good line it not was take by nextcloud without error message.
So i have delete the parameters of the app with config:app:delete and inject the good line and it's works now !

Sorry for th derangement and thank you for your intervention.
I hope that my error can help at another one.

**Comment by stefangweichinger** [comment]
> I hope that my error can help at another one.

Found this issue as I also see errors trying to embed my URL ...
Will try to follow your approach but so far I don't fully understand.
