### ISSUE TITLE
Use the parameters of th appointement calendar

### ISSUE THREAD

**Issue by fcreach** [SergeyMosin/Appointments#475]
Hi,

The configuration in the Appointements part in the Calendar app contain a lot of parameters who doesn't exist in the appointement module. Is it possible to get the parameters of the calendar apportements in the appointements app ?

![image](https://github.com/SergeyMosin/Appointments/assets/157523245/db0af308-1f44-4492-8e3e-c40cc52efa6d)

Thank you

**Comment by SergeyMosin** [comment]
![image](https://github.com/user-attachments/assets/65f673ae-b235-4b58-8957-f3d91194c264)
