### ISSUE TITLE
emails not sent

### ISSUE THREAD

**Issue by stefangweichinger** [SergeyMosin/Appointments#479]
I installed your application yesterday, set it up and started testing.
Appointments are created but I don't get emails to confirm the appointments.

What can I check for?

This is a nextcloud-28.0.2-docker-container.

**Comment by SergeyMosin** [comment]
Can you check NC logs. Are you able to receive emails from NC on the same address using other apps like Mail or Calendar (Attendee Invitations)

**Comment by stefangweichinger** [comment]
@SergeyMosin the problem was on my side: the password manager seems to have overwritten the NC mail settings somehow. Corrected that, now your app notifies correctly. Sorry for the noise, thanks.
