### ISSUE TITLE
Make public page title configurable

### ISSUE THREAD

**Issue by jinnko** [SergeyMosin/Appointments#48]
The public page title is configurable when it is set using the [Public page templates](https://docs.nextcloud.com/server/18/developer_manual/app/requests/controllers.html?highlight=title#public-page-templates) interface.  When this is unset we see the text "Nextcloud".

Would be great if this could be configurable.

**Comment by SergeyMosin** [comment]
Will go well with #47 
Should be available soon

Thanks

**Comment by SergeyMosin** [comment]
Available in version 1.4.0 ``Customize Public Page > Advanced Settings``
