### ISSUE TITLE
Cannot add time slots

### ISSUE THREAD

**Issue by peternagelsa** [SergeyMosin/Appointments#481]
I have updated the Appointment app to version 2.0.0; currently running Nextcloud 28.0.3. I can add pages and add these pages to the Directory page, but I cannot add time slots. Am I missing something somewhere?

Thanks
Peter

**Comment by SergeyMosin** [comment]
Time slot management has been moved into the settings menu:
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/fe609e46-2c83-4c5e-975e-d08679c64007)

`Weekly Template` mode:
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/05a2cede-52df-4158-baaa-873165cc4367)

`Simple` mode:
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/86cf58ea-f4d7-4477-bcda-2687b39c8428)
