### ISSUE TITLE
Tutorial page translation in Transifex

### ISSUE THREAD

**Issue by Jerome-Herbinet** [SergeyMosin/Appointments#486]
Hi,

We would like to contribute to the project as translators.

We found all apps wordings in Transifex, except the content of this page : https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php

We understand at this point that this page is not multilingual. Would you make it so ? (Transifex)

Thanks by advance.

**Comment by SergeyMosin** [comment]
Thank you for the kind offer. In V2 the help page has actually been broken up into individual snippets (example below) and the snippets should be available on Transifex.

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/6560cffb-ce42-4491-9427-054cfd046d50)

---

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/81e9a121-ba73-401b-97f4-9a47e6fa64c1)

**Comment by SergeyMosin** [comment]
Not applicable to v2, closing.
