### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by LuisCalzado** [SergeyMosin/Appointments#489]
Excuse my ignorance, how often is the translation reviewed in Transifex? The last modification in the confirmation email template and in the canceled template for Spanish is from 4 years ago, there are spelling and structure errors.
I can't use the application until these translation errors and others are resolved, is there any way I can modify the template manually?

Thanks.

**Comment by SergeyMosin** [comment]
I am not sure how review process works, by I assume anyone can make changes. Once the changes are detected, `nextcloud-bot` ( https://github.com/SergeyMosin/Appointments/commits?author=nextcloud-bot ) updates the translation files in this repo and I usually include the latest translations with every release.

**Comment by LuisCalzado** [comment]
Thanks, i think its already fixed for next update.
