### ISSUE TITLE
x participants at a same time?

### ISSUE THREAD

**Issue by Micha-Serv** [SergeyMosin/Appointments#491]
I have to organize a shuttle bus tour where participants have to register at a certain time so that I have the number of participants.

Is there a way to make the date available for x participants at a certain time?

Thank you in advance for your support.

**Comment by Micha-Serv** [comment]
Any chance to help? This becomes urgent now for me.

Maybe there is a way instead of removing the available slot to let them stay? Or can i write protect the slots by my self ?

Any help would be highly appreciated.

Thanks in advance.

**Comment by SergeyMosin** [comment]
duplicate #54
