### ISSUE TITLE
Changing "Talk room name" does not work

### ISSUE THREAD

**Issue by sequilox** [SergeyMosin/Appointments#496]
First of all, thank you so much for your great work!

I have already donated something to support your work some time ago.

It seems that changing the name of the talk room does not work anymore in the new version:

![screenshot-2024-04-09](https://github.com/SergeyMosin/Appointments/assets/159694088/7068c4ec-b3e4-47b6-ac74-6fecc8bc3eb5)
![screenshot-2024-04-09_1](https://github.com/SergeyMosin/Appointments/assets/159694088/856ab59b-e55b-4991-8999-ebb310d0f21e)

The destination calendar is set correctly here:
![screenshot-2024-04-09_2](https://github.com/SergeyMosin/Appointments/assets/159694088/659fe2af-742d-41f3-a6d5-583254503c4a)

Thanks and best regards!

**Comment by SergeyMosin** [comment]
Bug confirmed.

**Comment by SergeyMosin** [comment]
Fixed in v2.0.7
