### ISSUE TITLE
Error sending with SMTP server

### ISSUE THREAD

**Issue by charlessteiner** [SergeyMosin/Appointments#50]
I've tried with two installation on two servers with two browsers. Tried with both STARTTLS and TLS/SSL. All checks passed on Setup & Security warnings. SMTP is successful with the nextcloud "test email settings"

Nextcloud 18.0.3

both servers
centos 7
PHP 7.3.16

---

After clicking "Book now" I get the error: 

An Error Has Occurred

Please contact us directly at asdf@foo.com

Thank you

---

In logs it shows error
[no app in context] Error: Can not send email to test@foo.com

POST /index.php/apps/appointments/pub/ASR4XPKH2CXc_ao%3D/form
from 111.111.111.111 at 2020-04-17T20:05:34+00:00

---

**When I switch to sendmail it works.**

**Comment by SergeyMosin** [comment]
This can be related to https://github.com/SergeyMosin/Appointments/pull/37#issue-392999156
>SMTP servers can usually not send emails on behalf of everybody, so we use Reply-To to put the organizer's email address.

The next release (probably next week) will have an option to use ``\OCP\Util::getDefaultEmailAddress()`` as per provided patch.
