### ISSUE TITLE
Grey e-mail text instead of black - can it changed?

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#503]
Can somehow the color adjusted - more read friendly to black?

![Grey text in Thunderbird - black possible?](https://github.com/SergeyMosin/Appointments/assets/96744684/9d27694b-02ae-4f2c-b960-8c13dcd2fca1)

**Comment by SergeyMosin** [comment]
The new NC templates default to this. I think I can wrap the text into a styled `div` which should bring back the darker black( and left alignment).

rel: #504

**Comment by SergeyMosin** [comment]
fixed in v2.1.1
