### ISSUE TITLE
Additional Email text all as one sentence

### ISSUE THREAD

**Issue by dpw1460e** [SergeyMosin/Appointments#504]
Hi Sergey,

I just added a longer addition text to the email confirmation message. 
The whole information, which has some carriage returns in the input form, is sent by email as just one sentence.
It would be nice to have some options to format the additional email text to make it more reader friendly.
Thanks a lot for your great work.

I'm using Appointments 2.0.7 right now.

**Comment by SergeyMosin** [comment]
I'll look into missing line brakes, but HTML is is supported including the `<br>` tag, so something like this should work:
```
<p>
Video call link <a href="www.example.com/video">www.example.com/video</a><br>
<span style="color:red;">Important note in red.</span><br><br>
Phone Number: 555-123-3456<br>
</p>
```

**Comment by dpw1460e** [comment]
Thanks, Sergey!
It works. 
I didn't find anything about it in the issues, and the tutorial states that HTML is escaped.

Awesome! Thanks a lot! Have a great weekend.
