### ISSUE TITLE
i18n: Incorrect word at Transifex

### ISSUE THREAD

**Issue by rakekniven** [SergeyMosin/Appointments#506]
https://github.com/SergeyMosin/Appointments/blob/73dffd291579b144de4829cacaa703be45670eba/src/components/Navigation2.vue#L167

This should be "Delete page" instead of "DeletePage"

Same for all other occurences of "DeletePage" and "CreatePage".

**Comment by SergeyMosin** [comment]
fixed 2.1.1

**Comment by rakekniven** [comment]
Hello @SergeyMosin I mentioned you at Transifex two times. Translators have been asking questions about strings of your app.

Would you mind having a look?
