### ISSUE TITLE
routing form

### ISSUE THREAD

**Issue by julien-garrigue** [SergeyMosin/Appointments#508]
In the scenario where we have multiple booking/appointment forms, it would be nice to have a routing form to help a user to use the right booking form.

It's a conditional form.

You can find an example of this "routing form" feature on Calendly.

Thank you

**Comment by SergeyMosin** [comment]
The `Directory Page` could work for this purposes.

![image](https://github.com/user-attachments/assets/531e742a-acf2-4745-a1da-cb1faf44ebf9)
