### ISSUE TITLE
Cannot add title, subtitle, and text to directory item editor.

### ISSUE THREAD

**Issue by Rebislori** [SergeyMosin/Appointments#509]
As the title suggest:

- I created 3 calendars
- Added 3 new pages
- added those pages to directory page
- i get [this](https://servertome.uk/s/5k3YJ9RnmLj3bpZ)
- And then [here](https://servertome.uk/s/oRJr4s8n6cDDsK4) i can't fill the fields.

Am i missing something?

Thank you in advance.

**Comment by SergeyMosin** [comment]
Bug confirmed: can not edit directory page fields after a item is saved. Should be fixed in the next release.

@Rebislori It is still possible to fill-in the fields when you create directory items (before the first save). Thank you for the bug report.

**Comment by Rebislori** [comment]
Great, thank you for your answer and your great job with this plugin.

**Comment by SergeyMosin** [comment]
Fixed in v2.1.4
