### ISSUE TITLE
Bug: can't select a calendar

### ISSUE THREAD

**Issue by antonkarliner** [SergeyMosin/Appointments#51]
Just updated to 1.40, love new functionality, but now I can't select the calendar to fill with appointment slots. When I try to "Share online" Public page, I get "Select a Calendar First" warning. I then try to select a calendar by pressing three dots next to "Select Calendar", I get a list of calendars, I press a calendar name – and nothing happens. Still "Select a Calendar First" mistake.

I tried to delete and re-create calendars, tried to reinstall the app, tried to reinstall calendar app, tried to use this as another user, tried different browsers – no effect.

I run Nextcloud 18.0.3 on Ubuntu VPS.

Also I noticed some mistakes in requests in Firefox Page inspector, happening when i press on the calendar name when trying to select it. maybe this is helpful (screenshot attached).

<img width="720" alt="Снимок экрана 2020-04-21 в 01 27 25" src="https://user-images.githubusercontent.com/19594480/79806573-6529c200-8371-11ea-9b04-48c42b7014f5.png">

**Comment by SergeyMosin** [comment]
Can you please check the request to ``state`` URL as per pic below right after a calendar is selected from the calendar list 

![cal_request](https://user-images.githubusercontent.com/10747559/79808845-03e7fb80-833d-11ea-9a19-19386a147cbc.jpg)

Thanks

**Comment by antonkarliner** [comment]
Here:
<img width="1280" alt="Снимок экрана 2020-04-21 в 02 33 19" src="https://user-images.githubusercontent.com/19594480/79809173-8d68ef00-8378-11ea-9f86-8c1a63db4c6e.png">

**Comment by antonkarliner** [comment]
Okay, just tried it on a fresh NC installation and everything works well... Seems there's a problem with my installation. Only if I knew what it is.

**Comment by SergeyMosin** [comment]
Is there anything suspicious in NC logs:
``tail -n500 /path/to/nextcloud/data/nextcloud.log|grep state``

**Comment by antonkarliner** [comment]
Well, there are messages like this:

`{"reqId":"rjw72BlRPE5SElJlFuHW","level":3,"time":"2020-04-18T03:00:03+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SHOW SERVER_VERSION':\n\nSQLSTATE[57P01]: Admin shutdown: 7 FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":0,"Trace":[{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->","args":["An exception occurred while executing 'SHOW SERVER_VERSION':\n\nSQLSTATE[57P01]: Admin shutdown: 7 FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.",{"errorInfo":["57P01",7,"FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver"},{"errorInfo":["57P01",7,"FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'SHOW SERVER_VERSION':\n\nSQLSTATE[57P01]: Admin shutdown: 7 FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request."]},{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php","line":162,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver"},{"errorInfo":["57P01",7,"FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"SHOW SERVER_VERSION",[]]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db/statementwrapper.php","line":73,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db.php","line":142,"function":"execute","class":"OC_DB_StatementWrapper","type":"->","args":[[]]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":978,"function":"executeAudited","class":"OC_DB","type":"::","args":[{"__class__":"OC_DB_StatementWrapper"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":958,"function":"checkDatabaseVersion","class":"OC_Util","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":658,"function":"checkServer","class":"OC_Util","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/cron.php","line":42,"args":["/home/admin/web/drive.*.*/public_html/lib/base.php"],"function":"require_once"}],"File":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[57P01]: Admin shutdown: 7 FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":"57P01","Trace":[{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php","line":153,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db/statementwrapper.php","line":73,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db.php","line":142,"function":"execute","class":"OC_DB_StatementWrapper","type":"->","args":[[]]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":978,"function":"executeAudited","class":"OC_DB","type":"::","args":[{"__class__":"OC_DB_StatementWrapper"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":958,"function":"checkDatabaseVersion","class":"OC_Util","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":658,"function":"checkServer","class":"OC_Util","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/cron.php","line":42,"args":["/home/admin/web/drive.*.*/public_html/lib/base.php"],"function":"require_once"}],"File":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[57P01]: Admin shutdown: 7 FATAL:  terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":"57P01","Trace":[{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php","line":153,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db/statementwrapper.php","line":73,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/db.php","line":142,"function":"execute","class":"OC_DB_StatementWrapper","type":"->","args":[[]]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":978,"function":"executeAudited","class":"OC_DB","type":"::","args":[{"__class__":"OC_DB_StatementWrapper"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/private/legacy/util.php","line":958,"function":"checkDatabaseVersion","class":"OC_Util","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":658,"function":"checkServer","class":"OC_Util","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"/home/admin/web/drive.*.*/public_html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/home/admin/web/drive.*.*/public_html/cron.php","line":42,"args":["/home/admin/web/drive.*.*/public_html/lib/base.php"],"function":"require_once"}],"File":"/home/admin/web/drive.*.*/public_html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"--","version":"18.0.3.0"}`

**Comment by SergeyMosin** [comment]
Though provided portion of the log is not related to the appointments app, it does not look good for the database connection. As far as "selecting a calendar" goes - this step writes to the database via ``OCP\IConfig->setUserValue(...)`` function, nothing special really...

Best of luck

**Comment by daebak74** [comment]
Same problem here after update 1.4.1 I can't select calendar NC 18.0.2

**Comment by SergeyMosin** [comment]
@daebak74 
Can you check NC logs right after calendar selection fails

```tail -n200 /path/to/nextcloud/data/nextcloud.log|grep state```
or
```tail -n200 /path/to/nextcloud/data/nextcloud.log|grep appo```

I can not reproduce, what database are you using

thank you

**Comment by SergeyMosin** [comment]
Can you set/update other values Name, Location or "Customize Public Page" settings.

**Comment by kinolaev** [comment]
Hello @SergeyMosin, the problem is `===` in https://github.com/SergeyMosin/Appointments/blob/v1.4.1/lib/Backend/BCSabreImpl.php#L142. I think some instances still doesn't use bigints for ids, thats why `$c['id']` is int and not equal to `$calId` that is string. Changing `===` to `==` resolves the problem, but it is temporary solution.

**Comment by SergeyMosin** [comment]
@kinolaev Thank you very much !!

**Comment by kinolaev** [comment]
I was wrong, `calendars` table uses bigints for ids but now I think that postgres returns bigint as int, while mysql returns bigint as string.

@daebak74, what database you use?

**Comment by antonkarliner** [comment]
Just did a fresh Nextcloud installation with postgres as DB – and encountered the same problem! So, it's definitely something about postgres.

**Comment by SergeyMosin** [comment]
@antonkarliner I just published v1.4.2 to the NC App store with the fix as per https://github.com/SergeyMosin/Appointments/issues/51#issuecomment-617749140 it should be available for download in 15-20 min

**Comment by antonkarliner** [comment]
@SergeyMosin great! Thanks a lot.
