### ISSUE TITLE
Automatic (Front end) Timezone conversion... is a must

### ISSUE THREAD

**Issue by smileBeda** [SergeyMosin/Appointments#511]
I only realize now that Appointments app will show my server's timezone on the appointment form to the users who use the form to book appointments.

Specifically it seems it uses the timezone set in my Nextcloud instance... or perhaps my calendars timezone.

This is of course rendering the app very much useless for even slightly international use case.

One cannot expect a Belgian to make calculations or even use some third party app to deduct what I might mean with `11:00 Indochina Timezone`
The daylight savings differences (missed by most third parties) alone will send the client right away to the next provider of service of which he/she was about to book a meeting for.

Calendly has this feature for free. It picks up (I guess) your IP and deduces the correct times from that, thus showing the person who books the times available in _their_ timezone.

This should be very useful to anyone using Appointments. I cannot imagine using the app without this feature, unfortunately.

Also see https://github.com/SergeyMosin/Appointments/issues/460

**Comment by theRAGEhero** [comment]
I agree, this would be an important feature.

**Comment by SergeyMosin** [comment]
Timezone picker is available in v2.2.0
