### ISSUE TITLE
[BUG] Location is not applied

### ISSUE THREAD

**Issue by hackvokat** [SergeyMosin/Appointments#512]
Hello,
When booking new appointments, the set location is not transferred to the calendar and the appointment invitation. It only says "Online (audio/video)" for all of them - regardless of the location specified in the configuration.
This has been the case since the last or penultimate update.

**Comment by SergeyMosin** [comment]
Bug confirmed. Fix is coming ASAP.

**Comment by SergeyMosin** [comment]
fixed in v2.1.2
