### ISSUE TITLE
open holiday calender does not work 

### ISSUE THREAD

**Issue by Solar-Simon** [SergeyMosin/Appointments#513]
Hi there,
I want to have an Abo for Holidays in my region. Here in Germany every federal state has some special Holidays.
If found this site: https://projects.kkapsner.de/Kalender/Feiertage/
But my Abo there does not work with appointments. Dates on those days are still available.
Where is the fault? 

On Nextcloud there is only a Holidays for the hole of Germany. This one works fine with appointment, but does not excatly apply to my region.

**Comment by SergeyMosin** [comment]
fixed in v2.1.7
