### ISSUE TITLE
Use default instance email as default

### ISSUE THREAD

**Issue by tcitworld** [SergeyMosin/Appointments#52]
Following #37, I think using `\OCP\Util::getDefaultEmailAddress` and `Reply-To` should really really really be the default (as most instance won't have the particular configuration allowing to send emails on behalf of organizers).

Please consider this.
See #53 as well.

**Comment by SergeyMosin** [comment]
Isn't there some kind of SPAM filtering issues with some mail server, DKIM, etc... configurations when using "Reply-To" with different domain name or something like that. However, the ``getDefaultEmailAddress`` can be the default :) , just got to update the docs.

Thanks

**Comment by tcitworld** [comment]
> Isn't there some kind of SPAM filtering issues with some mail server, DKIM, etc... configurations when using "Reply-To" with different domain name or something like that.

The `From` header is checked, hence this proposition, but the `Reply-To` can be anything.

At some point we may want to have an option for disabling the `Reply-To` if the organizer doesn't want the attendees to know their email.

Thank you, feel free to close this now or when this is in a release.
