### ISSUE TITLE
No free terms

### ISSUE THREAD

**Issue by PrzemekSkw** [SergeyMosin/Appointments#521]
Hello,
I try to figure out how to setup my first appointment but show me "No Free Terms"
I go to settings in new Public Page:
![image](https://github.com/SergeyMosin/Appointments/assets/25219988/75580bf5-fd3c-4f7c-ae1a-9e7f2622698e)

even if I setup terms in calendar i get no free terms:
![image](https://github.com/SergeyMosin/Appointments/assets/25219988/d5185e16-f371-4882-942e-f4f918642764)

Regards

**Comment by SergeyMosin** [comment]
Is the page enabled ?

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/7b05d080-4005-4472-8031-aede960c552c)

**Comment by PrzemekSkw** [comment]
Hi, thanks for fast answer.
I make new Public Page, set simple calendar view and set week:
![image](https://github.com/SergeyMosin/Appointments/assets/25219988/eba29ebf-224a-449b-ba45-b44c5a73685b)

I add that page to Folder Page as item.
Then I enable page as You show but still no free terms.

**Comment by PrzemekSkw** [comment]
![image](https://github.com/SergeyMosin/Appointments/assets/25219988/c7648e23-a406-427f-af71-fbbc7948a3b2)

**Comment by SergeyMosin** [comment]
In `Simple` mode:

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/1b9fbaf3-8552-444f-989e-5deadea1679c)

----

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/ddb3bf3e-8a94-4d44-aa9d-819e297e55a3)

**Comment by PrzemekSkw** [comment]
Thank You, now it works :)

Do you plan to simplify the application in the future or add some popup tutorial because I showed it to several people from my company and no one was able to add a meeting properly?

Regards.

**Comment by SergeyMosin** [comment]
duplicate/related #529
