### ISSUE TITLE
If "show timezone" is disabled, it's still mentioned in the email text

### ISSUE THREAD

**Issue by markuman** [SergeyMosin/Appointments#522]
> ...appointment scheduled for Mittwoch, 19. Juni 2024, 12:10 Mitteleuropäische Sommerzeit is awaiting your confirmation.

Is it possible to remove the timezone information in email text?  
It's already not displayed in the settings

**Comment by SergeyMosin** [comment]
This only applies to the web page, not the email.
It might be possible for email when `Editable Email Templates` in #470 is implemented
Closing as duplicate of #470
