### ISSUE TITLE
Click to unsubscribe refers to localhost

### ISSUE THREAD

**Issue by markuman** [SergeyMosin/Appointments#525]
https://github.com/SergeyMosin/Appointments/blob/7857af009eaa167723d97a69a1a91ec49291a742/lib/Backend/DavListener.php#L1538C32-L1539C29

While `$cnl_lnk_url` is build by `overwrite.cli.url`

> // overwrite.cli.url must be set if $embed is not used

https://github.com/SergeyMosin/Appointments/blob/7857af009eaa167723d97a69a1a91ec49291a742/lib/Backend/DavListener.php#L339-L345

Reminder-Mails are never embedded, so it might happen that unsubscribe URLs are set to localhost.

A proper field to define the base url per appointment would be helpful.

**Comment by SergeyMosin** [comment]
In v2.1.5 additional checks have been added to only add the links if the `overwrite.cli.url` property contains a valid URL.

 > A proper field to define the base url per appointment would be helpful.

This is really up to admins to define the "base url" using `overwrite.cli.url` as per NC [docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwrite-cli-url), and if it has not been defined, users can opt-out of spending the links by unchecking the `Add actions links` checkbox.  

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/ed269de2-584b-4787-985f-7913e70ac4e4)
