### ISSUE TITLE
Conflict check is not working for holidays calendar

### ISSUE THREAD

**Issue by nijel** [SergeyMosin/Appointments#527]
I've added holidays calendar to conflicts check:

![image](https://github.com/SergeyMosin/Appointments/assets/212189/afed6209-c051-46e4-8284-10b17026a9ac)

There is a public holiday in the calendar for next Friday:

![image](https://github.com/SergeyMosin/Appointments/assets/212189/d9567dd7-1198-4aba-a032-c9362460cd36)

But the meeting slot is still offered for that day:

![image](https://github.com/SergeyMosin/Appointments/assets/212189/f41bd07e-f102-411b-acdb-fd22020ded30)

**Comment by SergeyMosin** [comment]
fixed in v.2.1.7

**Comment by nijel** [comment]
I now see the issue again in 2.4.3. I am not sure if it was ever working correctly for me or not, as I didn't check after updating.

1. Add Czech holidays calendar (as documented in https://docs.nextcloud.com/server/latest/user_manual/en/groupware/calendar.html#subscribe-to-a-holiday-calendar).
2. Add it for conflicts checking in appointments.
3. Add slots for Easter (next Friday / Monday).
4. See that Appointments happily offers these times even there is conflict with public holidays.
