### ISSUE TITLE
Don't use SystemValue for an app configuration

### ISSUE THREAD

**Issue by tcitworld** [SergeyMosin/Appointments#53]
To determine whether to use default instance email or organizer email as `From:` header, this app is using `getSystemValueBool('appointments.use.default.email')`. Apps shouldn't register their own system values in `config.php`.

Instead please use `getAppValue('appointments, 'useDefaultEmail', 'yes') === 'no'`, which can be set with `occ config:app:set appointments useDefaultEmail --value no`.

See #52 as well.

**Comment by SergeyMosin** [comment]
OK, this makes sense

**Comment by tcitworld** [comment]
Thank you, feel free to close this now or when this is in a release.

**Comment by tcitworld** [comment]
Thank you, feel free to close this now or when this is in a release.
