### ISSUE TITLE
 Text in the confirmation email appears truncated in older email programs

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#532]
The text in the confirmation email appears truncated in older email programs, such as Windows Live Mail 2012:

![Cropped text Confirmation E-Mail](https://github.com/user-attachments/assets/69f95fd0-62d0-427a-abc4-f8bdfff82ad4)

**Comment by SergeyMosin** [comment]
Very Strange. Appointment emails are sent using standard NC template(s) & functions.

Is this only effecting Appointments confirmation email or other Appointments and/or NC email ?

**Comment by Sarmingsteiner** [comment]
The Appointments confirmation emails for the host appear somewhat truncated (i.e. only the first line: "Appointment confirmed". Emails from other NC apps are shown properly.

**Comment by SergeyMosin** [comment]
fixed in v.2.1.7
