### ISSUE TITLE
Can't book appointments after installation

### ISSUE THREAD

**Issue by alexander-zierhut** [SergeyMosin/Appointments#533]
Uncaught ReferenceError: OC is not defined
<anonymous> https://nextcloud.xxxx/apps/files_sharing/l10n/de_DE.js?v=8b20871d-37:1

Uncaught TypeError: OC.L10N is undefined
<anonymous> https://nextcloud.xxxx/custom_apps/appointments/l10n/de_DE.js?v=8b20871d-37:1

Uncaught ReferenceError: $ is not defined
<anonymous> https://nextcloud.xxxx/core/js/public/publicpage.js?v=8b20871d-37:25

I haven't used the app yet and only did some initial configuration.

![image](https://github.com/user-attachments/assets/292c6aa4-d7a9-45a9-af1a-fe8c93bdc4b1)
The form does not become disabled.

What other info do you need me to provide?

**Comment by alexander-zierhut** [comment]
I also switched the language to English, but the problem persisted.

**Comment by SergeyMosin** [comment]
Can you make sure that the page is enabled.

![image](https://github.com/user-attachments/assets/b1828f9d-4853-4b39-a27a-fc0e68ef0b75)

Is the page is already enabled, can you check the console for the `data-state` code.

![image](https://github.com/user-attachments/assets/3360a6ea-7e37-45a7-80fe-6808fb764e4f)

**Comment by alexander-zierhut** [comment]
Hi @SergeyMosin, thank you for the quick reply.

![image](https://github.com/user-attachments/assets/b7e222ec-3c98-4a93-ae9b-96ee4db6ed52)
The page is enabled.

![image](https://github.com/user-attachments/assets/9f170bb3-0024-496f-8b19-b8e6e8ee550c)
The `data-state` is `5`

**Comment by SergeyMosin** [comment]
`data-state: 5` indicates that there are no appointments withing the period indicated by the `Show appointments for next...` setting.

`Weekly Template` mode example:

![image](https://github.com/user-attachments/assets/520bb4ca-9cc3-4e37-bf72-ca5cec2be367)

----

![image](https://github.com/user-attachments/assets/80c17a22-b050-4340-889e-e03f9dce0a29)

**Comment by alexander-zierhut** [comment]
Thank you so much! Maybe a notice that there is no template might make sense? I didn't see that at all.
