### ISSUE TITLE
Extra fields are no longer stored in calendar event (regression)

### ISSUE THREAD

**Issue by JocelynDelalande** [SergeyMosin/Appointments#534]
I use the extra fields feature for a while (~1 year).

I set up the following content as extra fields code :

```json
[
  [
    {
      "tag": "select",
      "label": "Tarification",
      "required": true,
      "options": [
        "Payant",
        "Gratuit",
        "Tarif négocié"
      ],
      "name": "n80406135"
    },
    {
      "tag": "input",
      "required": true,
      "label": "Description",
      "placeholder": "Que va-t-il se passer dans la salle",
      "type": "text",
      "name": "nc01910b3"
    }
  ]
]
```

It used to work, but fore some time (couple of weeks ?), the form is displayed fine but it seems that the content of the two fields is lost : it does no longer appears in the calendar events (`DESCRIPTION`) nor in the confirmation email.

Any idea of what happened ? A regression ?

I'm using appointments v2.1.6

**Comment by SergeyMosin** [comment]
I think this might be a regression from v1 to v2 migration. Please remove the outer array (square brackets.)

This should work:
```json
  [
    {
      "tag": "select",
      "label": "Tarification",
      "required": true,
      "options": [
        "Payant",
        "Gratuit",
        "Tarif négocié"
      ],
      "name": "n80406135"
    },
    {
      "tag": "input",
      "required": true,
      "label": "Description",
      "placeholder": "Que va-t-il se passer dans la salle",
      "type": "text",
      "name": "nc01910b3"
    }
  ]
```

**Comment by JocelynDelalande** [comment]
Thanks @SergeyMosin :) The workaround works. Maybe the code could autofix the data when the quirk is detected ?
