### ISSUE TITLE
Conflict Check Only Considers First Day for Multi-Day Events Since Version 2.1.7

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#535]
I have noticed an issue with the conflict check functionality for multi-day events. Since updating to version 2.1.7, it seems that only the first day of a multi-day event is considered in the conflict check. This is causing scheduling conflicts to go undetected for the remaining days of the event.

Version:
2.1.7

Please investigate and address this issue. Thank you for your assistance.

**Comment by SergeyMosin** [comment]
Possible regression from 93f473f80fd2d8ad586df00be0a82a8db2602068 , can you post ( or send directly to me: sergey [at] srgdev.com ) a `.ics` file for one of the multi-day events that is not properly blocking.

Thank you.

**Comment by SergeyMosin** [comment]
Should be fixed in v2.1.8
