### ISSUE TITLE
Remove icon in appointment title & add reminder inside calendar

### ISSUE THREAD

**Issue by rhmkt** [SergeyMosin/Appointments#539]
I would like to remove the check icon from the calendar title, but even changing to a custom title the icon is still there.

I would also like to set a reminder inside the appointment for a time like 30 minutes, so that I get desktop notifications in things like outlook rather than just an email which is easily missed.

Are these features that can be added?

**Comment by SergeyMosin** [comment]
In v2.1.12 the  ✔️ can be removed in `Settings > Advanced >  Event Title Template `

The "_reminder inside the appointment_" is not planned at least for the near future.
