### ISSUE TITLE
2 rooms on same calendar for appointment

### ISSUE THREAD

**Issue by 2EricBrunet** [SergeyMosin/Appointments#541]
Hello,
First of all thank your work with this pertinent app!

I have created 2 public pages for 2 rooms for appointments in simple mode (weekly mode is not appropriate for my case) in **same** calendar.
After slots created in parameter menu of each page, I notice each public page form display slots of other page! 😨

Is it a bug or a limitation of the app 😅 ?

The solution is to create an agenda by room ?

technical infos: 
* Netxcloud server: 27.1.11.3

Thanks in advance.

**Comment by SergeyMosin** [comment]
> Is it a bug or a limitation of the app 😅 ?

This is how the app works. If you don't want to share appointment slots between multiple pages you need a separate calendar per page.
