### ISSUE TITLE
Appointments not compatible with NextCloud 30.0

### ISSUE THREAD

**Issue by grosjo** [SergeyMosin/Appointments#543]
Hi there,
What would be needed to make this compatible with NC 30 ?
Thank you

**Comment by thisiszeev** [comment]
I am rather familiar with PHP and getting the hang of VueJS rather quickly. But I am a rookie with developing for Nextcloud.

If someone can point me in the right direction for where I can get documentation for what is depreciated and what is current on the Nextcloud 29/30 API, I am confident I can bring this app upto support Nextcloud 30.

**Comment by SergeyMosin** [comment]
I am planning to do NC30 testing next week, and if everything goes well I'll publish a new release next weekend.

@thisiszeev if you want to get a head-start, NC30 Core/API changes are here: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html

And for starters `max-version` needs to be changed to `30` here: 
https://github.com/SergeyMosin/Appointments/blob/3e0f1ce91f772c802948897f35a1f80c6bb6d6d8/appinfo/info.xml#L30-L33

**Comment by thisiszeev** [comment]
Shot bro!

Yeah, I got the info.xml figured out, it's what to look for when going through the actual JS and PHP files. But I will pop over to the link you shared and give it a good read.

If you need any people to do user testing of the app I am happy to offer my services for the modest fee of $0.00 plus taxes.😁

But seriously, I make regular use of this app so I am very keen to help in anyway

**Comment by thisiszeev** [comment]
Wow, what a read. This is exactly what I was looking for an could not find.

There are several apps I want to help to bring up to NC30. I know that 99% of these app maintainers do it in their spare time and earn little to no money for the apps that bring me value. So unlike a lot of people I see complaining that this is not this and that is not that and it's so unacceptable... I on the other hand would rather roll up my sleeves and help where I can, and show patience and appreciating for where I am unable to help.

**Comment by thisiszeev** [comment]
I have setup two blank nextcloud instances, one for 29 and one for 30. I have setup 3 test user accounts on each of them. I have backedup the html root for each and also made an SQL Dump for each... so while I am working, I can go quickly go back to clean install, in the event I break something of course.

**Comment by SergeyMosin** [comment]
v2.1.12 is NC30 compatible

**Comment by grosjo** [comment]
Thanks
