### ISSUE TITLE
[Feature Request] Source Calendar Appointment Slot Title to Event Title Template

### ISSUE THREAD

**Issue by FiveVoltLogic** [SergeyMosin/Appointments#548]
I am using this to book in repairs for our repair café. A few users will be able to administrate and so I'm looking to make this as simple as I can for them.

Part of this is the ability to have all bookings on one destination calendar rather than a separate calendar for each type of repair which can be done through External Calendars, but looks like I would need a source and a destination for each repair type, which seems a little clunky.

Currently I use the 'Simple' time slot mode, I add one appt slot for each time (1 for 10am, 1 for 10:30am etc..) and then duplicate and rename them in the source calendar ("_Electrical", "_General", "_Textile" etc..).

I can then book them as normal, and there isn't a conflict check so all the remaining slots are still visible and any cancelled slots reappear on the source calendar.

This all works fine, but once the calendar entry moves from the source to the destination, the title is lost. Is there any way to add this to the event title template? %E for event title?

If there's another way to do this, or I've missed something, please let me know!

**Comment by SergeyMosin** [comment]
New template tags are available in v2.1.12

- Icon = `%I` 
- Event Preset Title = `%E`

**Comment by FiveVoltLogic** [comment]
Amazing, thanks for your quick response :D
