### ISSUE TITLE
[Feature] option to disable telephone input

### ISSUE THREAD

**Issue by Rello** [SergeyMosin/Appointments#55]
Hello,
the telephone number is a mandatory input.
In my usecase everything depends on the email. Perhaps you can add an option to add/remote this input field?

thank you

**Comment by SergeyMosin** [comment]
This one is not that hard to implement, may next release.

**Comment by SergeyMosin** [comment]
Available in v1.4.9
``Customize Public Page > Advanced Settings > Hide phone number field``

**Comment by Rello** [comment]
Thank you. applied immediately.

thanks also for the advice to add several appointments at once in your app and them move them in the calendar in parallel.
