### ISSUE TITLE
Feature Request: Block Specific Email Addresses in the Appointments App

### ISSUE THREAD

**Issue by eswolferl** [SergeyMosin/Appointments#558]
Description
It would be highly beneficial if the Nextcloud Appointments app included functionality to block or restrict specific email addresses from booking appointments. Currently, the app allows any user with the booking link to schedule an appointment, which can result in spam or unwanted bookings. Adding an option to filter or restrict certain email addresses would give administrators greater control over who can access the scheduling system.

Proposed Solution
We suggest adding a feature within the Appointments app settings where administrators can define a list of blocked or restricted email addresses. This list would prevent any booking attempts from matching addresses or domains. For flexibility, this feature could include:

    A "blocked email addresses" field where specific emails or domains can be added.
    An option to enable or disable the restriction feature.
    A potential "custom message" option to inform blocked users if they attempt to book.

Use Case
This feature would greatly help in scenarios where unwanted booking attempts are received repeatedly from the same address or domain. For example, professionals, consultants, or businesses using Nextcloud Appointments could avoid spam or misuse by unauthorized parties.

Conclusion
This feature would enhance the utility of Nextcloud Appointments, making it a more robust and secure scheduling tool for all users. Thank you for considering this addition!

**Comment by SergeyMosin** [comment]
@eswolferl What would a good default message for blocked users be ?

Potential UI to manged the black list...

![image](https://github.com/user-attachments/assets/03708cd8-5ff2-40df-9955-acf9043621cd)

**Comment by eswolferl** [comment]
Hi,

Ui Looks good.
Message "Your access has been temporarily restricted. For further
information or if you believe this was a mistake, please send us an inquiry
via email at ***@***.*** Thank you for your understanding!"


Sergey Mosin ***@***.***> schrieb am Di., 12. Nov. 2024,
01:29:

**Comment by SergeyMosin** [comment]
Available in v2.2.0

**Comment by eswolferl** [comment]
Thanks, I'll check it out.

Sergey Mosin ***@***.***> schrieb am So., 17. Nov. 2024,
17:04:
