### ISSUE TITLE
Part of the menu with settings that are not displayed

### ISSUE THREAD

**Issue by cg001** [SergeyMosin/Appointments#561]
I installed appointments and don't see the whole menu at the left side. Especially the settings cog wheel is not there. An appointments calender is created but did not change anything.

I already die some debugging (uninstall/reinstall, deactivate all other apps etc.) but can't get this to work.

I see one message in browser console saying:
[INFO] AppContent: falling back to global nextcloud pane config.     index.es.js:2337 Proxying an event bus of version 3.3.1 with 1.3.0

Is this a known issue?

Thanks for having a look,
Christian
![Bildschirmfoto 2024-11-18 um 15 27 21](https://github.com/user-attachments/assets/39c1f4b1-a0b8-42a1-b472-5e9679e51b07)

**Comment by SergeyMosin** [comment]
Can you check the "3 dot" menu. The original screenshots are from v1 (rel #553 )

![image](https://github.com/user-attachments/assets/da61c6bc-82e8-4a0c-bf19-9bd0999d4510)

**Comment by cg001** [comment]
ahh, here they are, thank you!

Sorry for one additional question: do I create the schedule with the available timeslots from the appointments-view or in den calendar-app?

Thank you very much,
Christian

**Comment by SergeyMosin** [comment]
Depends on the "Time slot mode"

![image](https://github.com/user-attachments/assets/e5e6d1f9-4ba3-4178-980d-99b0f5e4c045)
