### ISSUE TITLE
Testing for conflicts doesn't work

### ISSUE THREAD

**Issue by Taxicletter** [SergeyMosin/Appointments#565]
Hi,
I used the appointments-app successfully for a long time. After a while, I need it again and am configuring it. I have NextCloud on my web-space and important my calender there. Maybe that's somehow part of the problem.
Then I set the calendar to book too. If I do that, I cannot set a different calendar to check for conflicts. I guess that's intended, because of course that would be the same calendar. But just mentioning it.
If I look for appointments, most of the booked spots still appear available. If book an appointment, the appointment is saved in my calender and is indeed not visible any-more as available. But I just created an event in my calendar, to make that an unavailable timeslot, and it keeps being selectable (I reload the page, so Appointments has the latest version of my calendar).
I know this used to work, so I guess I'm doing something wrong. But what?

The debug-info (blanked out personal info with ++++++++++++++):

```
Nextcloud Version: 30.0.2
Appointments Version: 2.3.2
Time zone: Europe/Brussels (calendar: N/A, core: Europe/Brussels)
Embeding Frame Ancestor: N/A
Embeding Button URL: N/A
Extension Notify: N/A
Key: Yes

{
  "enabled": true,
  "label": "++++++++++++++",
  "organization": "++++++++++++++",
  "email": "++++++++++++++",
  "address": "++++++++++++++",
  "phone": "0483303009",
  "confirmedRdrUrl": "",
  "confirmedRdrId": false,
  "confirmedRdrData": false,
  "mainCalId": "-1",
  "destCalId": "-1",
  "nrSrcCalId": "-1",
  "nrDstCalId": "-1",
  "nrPushRec": true,
  "nrRequireCat": false,
  "nrAutoFix": false,
  "tmmDstCalId": "2",
  "tmmMoreCals": [],
  "tmmSubscriptions": [],
  "tmmSubscriptionsSync": "0",
  "prepTime": "1440",
  "bufferBefore": 0,
  "bufferAfter": 0,
  "whenCanceled": "reset",
  "allDayBlock": false,
  "titleTemplate": "",
  "privatePage": false,
  "tsMode": "2",
  "icsFile": true,
  "skipEVS": true,
  "attMod": true,
  "attDel": true,
  "meReq": false,
  "meConfirm": true,
  "meCancel": false,
  "vldNote": "",
  "cnfNote": "",
  "icsNote": "",
  "formTitle": "",
  "nbrWeeks": "12",
  "showEmpty": false,
  "startFNED": false,
  "showWeekends": false,
  "time2Cols": false,
  "endTime": false,
  "hidePhone": false,
  "gdpr": "",
  "gdprNoChb": false,
  "pageTitle": "",
  "prefillInputs": 0,
  "prefilledType": 0,
  "formFinishText": "",
  "metaNoIndex": true,
  "pageStyle": "",
  "useNcTheme": true,
  "template_data": [
    [
      {
        "start": 46800,
        "dur": [
          60
        ],
        "title": "++++++++++++++"
      },
      {
        "start": 50400,
        "dur": [
          60
        ],
        "title": ++++++++++++++"
      }
    ],
    [],
    [],
    [
      {
        "start": 59400,
        "dur": [
          60
        ],
        "title": "++++++++++++++"
      },
      {
        "start": 63600,
        "dur": [
          60
        ],
        "title": "++++++++++++++"
      },
      {
        "start": 67800,
        "dur": [
          60
        ],
        "title": "++++++++++++++"
      }
    ],
    [],
    [],
    []
  ],
  "template_info": {
    "tzName": "Europe/Brussels",
    "tzData": "BEGIN:VTIMEZONE\r\nTZID:Europe/Brussels\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nTZNAME:CEST\r\nDTSTART:19700329T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nTZNAME:CET\r\nDTSTART:19701025T030000\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nEND:STANDARD\r\nEND:VTIMEZONE"
  },
  "fi_html": "",
  "fi_json": [],
  "secHcapSiteKey": "",
  "secHcapSecret": "",
  "secHcapEnabled": false,
  "secEmailBlacklist": [],
  "reminders_data_0_seconds": "86400",
  "reminders_data_0_actions": true,
  "reminders_data_1_seconds": "0",
  "reminders_data_1_actions": true,
  "reminders_data_2_seconds": "0",
  "reminders_data_2_actions": true,
  "reminders_moreText": "",
  "reminders_friday": false,
  "talk_enabled": false,
  "talk_delete": false,
  "talk_emailText": "",
  "talk_lobby": false,
  "talk_password": false,
  "talk_nameFormat": 0,
  "talk_formFieldEnable": false,
  "talk_formLabel": "",
  "talk_formPlaceholder": "",
  "talk_formTxtReal": "",
  "talk_formTxtVirtual": "",
  "talk_formTxtTypeChange": "",
  "bbbEnabled": false,
  "bbbDelete": true,
  "bbbAutoDelete": true,
  "bbbPassword": false,
  "bbbFormEnabled": false,
  "debugging_mode": 0,
  "__ckey": ""
}
{
  "talk_formDefLabel": "Meeting Type",
  "talk_formDefPlaceholder": "Select meeting type",
  "talk_formDefReal": "In-person meeting",
  "talk_formDefVirtual": "Online (audio/video)",
  "talk_integration_disabled": true,
  "bbb_integration_disabled": true,
  "bjm": "cron",
  "cliUrl": "1",
  "defaultLang": "en",
  "token": "++++++++++++++"
}
[
  {
    "name": "Agenda",
    "color": "#0082c9",
    "id": "2",
    "isReadOnly": false,
    "isSubscription": false
  }
]
```

**Comment by SergeyMosin** [comment]
Can you make sure that the "Blocker" events are set as "Busy" and the "Classification" either set to either "When shared show full event" or "When shared show only busy", and if your blocker is a "Full Day" event, check `Settings > Calendars and Schedule > Time Slot Settings > Include all day events in conflict check`

![image](https://github.com/user-attachments/assets/74ca3262-4f25-4518-9e15-ae389728cf4c)

**Comment by Taxicletter** [comment]
Thank you Sergey, it aren't whole day blockers, and they are confirmed and busy (in Dutch).
![Schermafdruk van 2024-11-25 19-34-13](https://github.com/user-attachments/assets/209427ec-12e1-4e7f-b110-1a2b29ffe859)
![Schermafdruk van 2024-11-25 19-35-33](https://github.com/user-attachments/assets/7304ea51-ca44-4cc5-9398-78f561b6bc82)

**Comment by SergeyMosin** [comment]
Can you export the event and send me the `.ics` file to sergey [at] srgdev.com

**Comment by Taxicletter** [comment]
Hi Sergey, I was thinking: I exported my calendar with BetterBird (because OpenDesktop was down). Could it help if I remove my Calendar from NextCloud and import an exported version (from OpenDesktop this time, since I can reach my account again today)?
Also, is this important: in OpenDesktop, I can see Appointments I created in the Calendar view, which is not the case in my own NextCloud instance.
![afbeelding](https://github.com/user-attachments/assets/5f94f06a-5be6-4522-9c84-d815d72296ed)
![afbeelding](https://github.com/user-attachments/assets/9671172d-89cf-423a-9761-1a1a380ddd80)
(I mailed you the appointment yesterday, thank you for checking this out!!)

**Comment by Taxicletter** [comment]
OK: I tried to import the calendar again, this time the OpenDesktop export. That didn't change anything.
Also: The appointments in the left sidebar are something different from your appointment-app. But I tried making appointments there, and also this app doesn't "see" the appointments already in the calendar.

**Comment by Taxicletter** [comment]
Hi Sergey,
I don't see the "Get by Event UID". The only settings I can reach, is those from an appointment, there are no "general settings" as far as I can see?
![image](https://github.com/user-attachments/assets/ec0b78dc-34a4-4a00-801d-6539487ced22)

**Comment by SergeyMosin** [comment]
The new setting is  in v2.3.3 (released about an hour ago)

**Comment by Taxicletter** [comment]
Waaw, you are the fastest developer in the world :-)

Yes, classification is 0:

```
END:VEVENT
END:VCALENDAR
',
      'uri' => 'CCC70DC2-9A78-491C-9584-561D47B24197.ics',
      'calendarid' => 2,
      'lastmodified' => 1732650558,
      'etag' => '335e57bd9e31ea33456f8d9e82503501',
      'size' => 684,
      'componenttype' => 'VEVENT',
      'firstoccurence' => 1733238000,
      'lastoccurence' => 1733241600,
      'uid' => 'cbda3774-84b7-41a2-8811-d9d4b2ea2470',
      'classification' => 0,
      'calendartype' => 0,
      'deleted_at' => NULL,
    ),
  ),
```

**Comment by Taxicletter** [comment]
Hi,
I  added a new appointment page as a test and choose "simple" this time. When I publish the page, I get the error: "Main Calendar not found, check settings". My main calendar is "Agenda" and is selected.

![afbeelding](https://github.com/user-attachments/assets/5e376f3b-b999-4839-8251-7af300abd85e)

Can that be the cause of this problem? That for some reason NextCloud doesn't recognise my calendar?

**Comment by SergeyMosin** [comment]
Bug confirmed, possibly caused by out of order `query->andWhere` expression in `fastQuery`

**Comment by Taxicletter** [comment]
And it's fixed! That's fantastic! Thank you very much.

**Comment by growechris** [comment]
Hi,
we've got the same problem although we updated to v2.3.4
We also checked the points above.
We hope you can help us.

**Comment by SergeyMosin** [comment]
@growechris Are there any appointments related errors in Nextcloud logs ? Can you send me ( sergey [at] srgdev.com ) the settings dump for the page, it can be found in the `Settings > Advanced > Debugging > Settings Dump` ?

**Comment by growechris** [comment]
@SergeyMosin Thanks for your answer. I sent you the data by email.

**Comment by SergeyMosin** [comment]
@growechris It looks like you are using the `Simple` mode. In this mode conflicts are not checked (this actually why overlapping/multi-person appointments can be book via this method). Please consider the any of the other `Mode`s.

Note: possibly a documentation related issue, ref: #167

**Comment by neufeind** [comment]
@SergeyMosin It seems to have worked for me with Simple Mode in Version 2.2.0 and broke at 2.3.0 (released 23th Nov 2024). Also see my comment in #566. Maybe an issue since it "worked in the past"? Also, what value does not checking in Simple Mode have but upon trying to book you get a generic error-message.
