### ISSUE TITLE
Appointment slots should Show As "free" instead of "busy"

### ISSUE THREAD

**Issue by shgysk8zer0** [SergeyMosin/Appointments#57]
When an appointment slot is created, it should show as free instead of busy. It should then be changed to busy when the slot is booked.

Having available slots marked as busy makes it so that anyone in Nextcloud viewing my availability sees the exact times that I mark as available for appointments as busy.

## Default settings [10-12, 13-17 all busy hours]
![image](https://user-images.githubusercontent.com/1627459/79901345-91226300-83c4-11ea-98a7-fd2322be0e69.png)

## Updated to set 11 AM as free instead of busy
![image](https://user-images.githubusercontent.com/1627459/79901625-f2e2cd00-83c4-11ea-9bdc-91603d22380a.png)

**Comment by SergeyMosin** [comment]
Should the the time slot become Busy when the appointment is booked or when the attendee actually confirms via the email link ?

**Comment by shgysk8zer0** [comment]
@SergeyMosin my best guess is as soon as booked to avoid conflicting scheduling.

**Comment by SergeyMosin** [comment]
Free/Busy is supported as of v1.4.6
