### ISSUE TITLE
missing a menu

### ISSUE THREAD

**Issue by SpeziesQ** [SergeyMosin/Appointments#570]
We are missing a menu to work with appointments (Termine), we can not activate the product with our contributor key.
Site is hostet at hetzner managed nextcloud.

![image](https://github.com/user-attachments/assets/9326ea2a-a7ef-4e69-bf51-ed31873bca3f)

Is there a workaround link to pullout the menu?

Best regards
Frank

**Comment by SergeyMosin** [comment]
Does the three dot button not open the menu ?

[app_menu.webm](https://github.com/user-attachments/assets/474e3a96-fa59-441c-8a11-d27dbba52546)

**Comment by SpeziesQ** [comment]
![image](https://github.com/user-attachments/assets/b9b9874c-f452-498b-a4c5-e92e7a04bdc7)

Oh my god.... I had not realised that tis german translation at the last position is for the contributor key. Thanks a lot.

**Comment by SpeziesQ** [comment]
Thanks for the fast help.
