### ISSUE TITLE
Time shown incorrectly in Safari

### ISSUE THREAD

**Issue by Rello** [SergeyMosin/Appointments#59]
Hello,
I have an urgent issue and could not find the cause. I assume one of the last changes in the **pagecontroller** because it was working before 1.4

I added floating appointments to a calendar at 8am
check this form:
https://klasseimnetz.de/index.php/apps/appointments/pub/5xRrG9vEmgwX/form

Calendar:
![Screenshot 2020-04-21 at 22 19 18](https://user-images.githubusercontent.com/13385119/79910029-3ddcfe80-841e-11ea-9085-0423f855e515.png)

opening in Chome shows the booking correct:
![Screenshot 2020-04-21 at 22 18 54](https://user-images.githubusercontent.com/13385119/79910032-3ddcfe80-841e-11ea-951d-f7d3aed7f245.png)

opening in Safari (macOs or iOS) looks incorrect
![Screenshot 2020-04-21 at 22 19 40](https://user-images.githubusercontent.com/13385119/79910028-3c133b00-841e-11ea-825d-378662e1c35e.png)

the booking confirmation email shows the correct time.
any idea?

**Comment by Rello** [comment]
I think this part is not doing what expected
https://github.com/SergeyMosin/Appointments/blob/master/lib/Controller/PageController.php#L833

**Comment by SergeyMosin** [comment]
Confirmed. Safari is not following the specs for Date.parse().
``Date.parse("2019-01-01T00:00:00")`` for example, should be parsed to browser's local timezone  while Safari parses it to UTC.
The fix is coming shortly.

Thank you

**Comment by Rello** [comment]
Ah. Shi*
Had the same issue in the Analytics app. Did not think in that direction 😤

Thank you

**Comment by Rello** [comment]
works again.
thank you for the quick action
