### ISSUE TITLE
The public link does not work on  nextcloud 8.0.1 with nginx and php-fpm

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#6]
The public link does not work on  nextcloud 8.0.1 with nginx and php-fpm

The public link  ends up in a 404 and redirects to the login page. 

I have not checked the logs yet. But will later on.

**Comment by mikweb2017** [comment]
try setting the app for the admin group only so it worked for me.

**Comment by SergeyMosin** [comment]
Are you using v1.0.4 ???

**Comment by small1** [comment]
yepp

**Comment by small1** [comment]
and it worked when o set the app to only work for one group

**Comment by SergeyMosin** [comment]
version 1.0.5 should fix last of public link issues.
