### ISSUE TITLE
can't add time slots to existing calendar

### ISSUE THREAD

**Issue by simplynotes** [SergeyMosin/Appointments#60]
If I create a new calendar in Nextcloud the apointment ap works as expected. When selecting an existing calendar - which is also synced with exchange - I get an error "COnfiguration error" when trying to add available time slots. The nextcloud.log doesn't contain any relevant information

any ideas?

thanks
Raimund

**Comment by SergeyMosin** [comment]
Could be some kind of permission problem, I am not sure.
Have you tried first creating a calendar, adding appointments and then syncing with exchange ?

**Comment by Dubidubiduu** [comment]
Added a new calendar, got "Einstellungsfehler. Bitte die Konsole prüfen". No information in there.

First /index.php/settings/admin/logging isn't named console in my german translation, also as a non admin user I wouldn't know what you mean with that line.

Second, what to do now to get it to work?

**Comment by SergeyMosin** [comment]
Can you check **Browser** console please.
Thank you.

**Comment by Dubidubiduu** [comment]
Ah, of course! Still not the best information for not admin users (and also not for a dummy admin :o ).

Turns out, that I just had to add something in the textarea at "User/Organisation Info" following "Benötigt keine Übersetzung. Für Android wird nur die formelle Übersetzung verwendet (de_DE)."

**Comment by SergeyMosin** [comment]
> Benötigt keine Übersetzung. Für Android wird nur die formelle Übersetzung verwendet (de_DE)

This is strange, let me check on translations at https://www.transifex.com/nextcloud/nextcloud/dashboard/

**Comment by simplynotes** [comment]
For me the solution was to switch to "Local (floating)" in the "Add Appointment Slots" Dialog in the drop down "Time zone"
The browser's web console showed the error "1:Can not get calendar timezone"

Best regards
Raimund

**Comment by SergeyMosin** [comment]
@simplynotes Timezone support if fixed as of v1.4.6, please see https://github.com/SergeyMosin/Appointments/issues/58#issuecomment-619092772 for differences between FLOATING and TIMEZONE times.

**Comment by SergeyMosin** [comment]
@Dubidubiduu Yes, it makes sense to move the error message from the console to the popup.

**Comment by SergeyMosin** [comment]
@Dubidubiduu The translation should be fixed in the v1.4.6 as well
