### ISSUE TITLE
Confirmation emails don't work

### ISSUE THREAD

**Issue by antonkarliner** [SergeyMosin/Appointments#61]
After 1.4.2 update, calendar selection works, but now confirmation e-mails are not delivered. E.g. somebody books an appointment and in order to finish booking he or she has to press "Confirm" in confirmation e-mail. But he/she doesn't recieve any emails.

So, I changed `==` to `=` in [line 51](https://github.com/SergeyMosin/Appointments/blob/98bd4e392905e8208b5410af8415d9bb23949cc3/lib/Backend/DavListener.php#L51) in lib/Backend/DavListener.php. And now everything works! And emails are delivered.

The issue seems very similar to #51 and also related to database type (I use postgres).

**Comment by SergeyMosin** [comment]
Fixed in v1.4.3
Thank you very much. I should really get a postgres setup for testing...

**Comment by antonkarliner** [comment]
Thanks for your quick reaction!
