### ISSUE TITLE
[Feature] Selectable Timerange isn't enough - There is more than 08.00-18.45 and Mon-Fri

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#62]
I actually would prefer to use it as a planner for my ngo appointments. So we work outside of office hours. For me 19.00 and 20.00 are very common time slots, whose I cannot choose yet. Also I can not choose the weekend yet (or at least I don't know how).

**Comment by SergeyMosin** [comment]
Extended to 22:00 in v1.4.8, for the weekends you can just move appointments manually in the calendar app.

**Comment by El-Gavy** [comment]
Hi,

I'm using Appointments for helping libraries and most of them open during saturdays.
I will tell the librarians to create appointments with the assistant and then move them with calendar app but it would be easier for them if saturday could be included in available days.

Thanks for this app, love it !
