### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#63]
Updated to 1.4.6., cleared browser cache, still get this:

![appointments](https://user-images.githubusercontent.com/34820982/80234183-fc379800-8657-11ea-88c6-a400670a3f72.png)

**Comment by SergeyMosin** [comment]
It is coming directly from transifex. There is nothing I can do, the bot pushes translations around midnight and I include the latest in the releases. If you want you can patch the ``/path/to/nextcloud/apps/appointments/l10n/de.js`` and ``/path/to/nextcloud/apps/appointments/l10n/de.json`` files on your machine. Also the  de_DE locale seem to have the right translations.

![de_translations](https://user-images.githubusercontent.com/10747559/80236707-81f01f00-8629-11ea-9eb5-d5b863a00318.png)

**Comment by SergeyMosin** [comment]
Should be fixed in v1.4.9
