### ISSUE TITLE
Bug: Deleted Calendar is still shown 

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#64]
1. Created test-calendar, added appointments. Works.
1. Deleted calendar, as it was just a test.

Expected behaviour:
1. The calendar isn't shown anylonger or it is shown, but I get a message, that it's deprecated/it's deleted.

Actual behaviour:
1. The calendar is still shown.

**Comment by SergeyMosin** [comment]
I can not reproduce. What browser are you using? Screenshot would help.

**Comment by Dubidubiduu** [comment]
Using Firefox 75.0 (64-Bit). Checked it two times now, one time without creating an appointment by external user, one time with. In both cases also couldn't reproduce what I experienced before. So I guess it's closed.

**Comment by dolohow** [comment]
I noticed that too.  Appointments shows calendars that I removed a long time ago, as reported here by OP.

Apparently, Nextcloud does not delete calendars, instead table `calendars` has field `deleted_at`. I think you should filter out those that are "marked" as such.

The code here only checks for read only, I think which is passed to `transformCalInfo`
https://github.com/SergeyMosin/Appointments/blob/82836bdefb36676d7f256571f2f5dd64d4635eed/lib/Backend/BCSabreImpl.php#L954-L964

**Comment by SergeyMosin** [comment]
Confirmed. Should be fixed in v1.12.5

@dolohow thanks for the report

**Comment by SergeyMosin** [comment]
Fixed in v1.12.5
