### ISSUE TITLE
[Feature] Give mandatory fields more attention - make it somehow selectable

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#65]
1. Mandatory input fields should be detectable in first sight, a red * at the fields also with an explanation * = mandatory would do the job.
1. Also you shouldn't send form when a mandatory field hasn't value.
1. Make per instance or per user or Appointment switch, which fields are mandatory.

**Comment by SergeyMosin** [comment]
>Mandatory input fields should be detectable in first sight, a red * at the fields also with an explanation * = mandatory would do the job.

You can customize the look anyway you want in ``Customize Public Page > Advanced Settings > Style Override``
Red * for the name field example:
``` 
<style>
label[for="srgdev-ncfp_fname"]:before{
  content:'*';
  display: inline;
  position:static;
  margin-right: .2em;
  color: red;
}
</style>
```
> Also you shouldn't send form when a mandatory field hasn't value.

Can't reproduce. What browser are you using ?

> Make per instance or per user or Appointment switch, which fields are mandatory.

Related to issue #55

**Comment by Dubidubiduu** [comment]
Ah, sorry, still had #60 and the "user/organisation info" form in mind. So I wasn't able to create time slots, since I haven't entered a location in "user/organisation info" form before.

Thank you for css snippet, very appreciated.
