### ISSUE TITLE
Naming - Polls vs. Appointments

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#66]
When I need to find a date and time for an appointment I use the polls app. When I offer my time to others I use the Appointments-App.

The german translation for the app right now is "Termine" (appointment) which is kinda confusing, since a appointment could also be something with a few persons.

Maybe singleAppointment is a solution to this?

**Comment by SergeyMosin** [comment]
This is up to translators at https://www.transifex.com/nextcloud/nextcloud/dashboard/
