### ISSUE TITLE
[Feature] Make affirmation Mail optional

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#67]
Give a setting, with whom the external user don't have to affirmate his booking.

**Comment by SergeyMosin** [comment]
Available in v1.4.14 - ``Email Settings > Skip email validation step``, some important info in the ``Help/Tutorial`` [Skip email validation step](https://htmlpreview.github.io/?https://github.com/SergeyMosin/Appointments/blob/master/templates/help.php#srgdev-sec_emailskipevs) section.

**Comment by Dubidubiduu** [comment]
Thanks!

It kinda works, **BUT** I also get a cancelled mail.

First time, the cancelled message was sent just a minute after the confirmation mail (or in the same time), second time it was ~4 hours later. Cronjob runs every five minutes...

**Comment by SergeyMosin** [comment]
What is "a cancelled mail" ? Can I see a screenshot ?

When the ``Skip email validation step`` option is enabled there is still one outgoing email being sent to the attendee, acknowledging that the appointment has been booked for the requested date and time, but it does not require any further action, it is for information purposes only. 

If by "a cancelled mail" you mean that this massage is bouncing back to you, than it means that the email address provided in the form is incorrect and the mail server is unable to deliver the message.

**Comment by Dubidubiduu** [comment]
Well, I guess nevermind, I just have been stupid, guess I just deleted the events and forgot about it. Sorry to waste your time :-/
