### ISSUE TITLE
[Feature] Add option to add a reminder for appointments

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#68]
Add an option to add a reminder for appointments, so I know before the event starts, even if I don't check my calendar that often.

Consider following options:
no - default
10 minutes
20 minutes
30 minutes
1 hour
2 hours
1 day

**Comment by SergeyMosin** [comment]
Good idea

**Comment by gitkald** [comment]
Yes, this would be nice

**Comment by Bellusterra** [comment]
Just signed on to request this myself and saw that it was already requested. Definitely would be a great addition.

**Comment by Bellusterra** [comment]
First of all great work @SergeyMosin I noticed the ability to now add in external calendar with a separate booking and scheduled calendar option. I had another thought to go along with my last. In the confirmation/notification email sent out to the person scheduling the appointment the ability to add to their calendar would be a good addition I believe, and that could have the triggered reminder built in to the event, or another option in the email to after “add to your calendar” “set reminder”, or simply as mentioned, integrated “add event to calendar with reminder”

**Comment by SergeyMosin** [comment]
> ability to add to their calendar would be a good addition

There is the ``Email Settings > Attach .ics file to confirm/cancel emails`` for which most email clients will show some kind of UI to quickly add/remove the event.

As for reminders, I did do a quick test but there were some timing issues, maybe it has something to do with the [background jobs configuration](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html) on my test rig. However, appointment reminders is definitely something I want to add when I get more free time to look into this.

**Comment by Bellusterra** [comment]
Well I look forward to seeing it get even better, I really like your application and appreciate the time you have been putting into it Thank you.

**Comment by radoeka** [comment]
Think of not just one reminder, but allow multiple reminders (2 days, 1 day and 30 minutes in advance e.g.).  The user can decide which reminders he/she wants to keep/use.

**Comment by SergeyMosin** [comment]
Reminders are available in v1.11.2 `Settings > Reminders`

Two important things:
- Scheduling method ( default `AJAX` is the least reliable ) more info: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#parameters
- `overwrite.cli.url` , if this is not properly configured then actions ( cancel and talk integration links ) will not be added to the emails or will point to a wrong URL, more info: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations
