### ISSUE TITLE
[Feature] Add text field for user/orga - output in subscription and mailing

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#69]
1. Additional to #24, there should also be a text field for the user/organisation offering time.
1. The text should be printed in subscription form.
1. Also the text should be printed to automailing (also the location field).

Guess I'm done with feature requests for a long. Thank you for your app and coding!!

**Comment by SergeyMosin** [comment]
(3) Is available in v1.5.0 ``Email Settings > Additional VALIDATION/CONFIRMATION email text``
(1) and (2) should be addressed in #24
