### ISSUE TITLE
From a schedule of one week. The public link only shows  the first day

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#7]
Add one week of appointments. Go to the public link. It will only show the first days slots and when those are full it wont show any more.

**Comment by SergeyMosin** [comment]
Does this happen to the public link only ? Or the preview form acts the same way ?

**Comment by fancycode** [comment]
For me it shows the first two days. Both on the public link and the preview form. Tested with 1.0.7 and created appointments for next week (starting March 2nd), 45 minutes, with lunch break, 7 instances.

**Comment by SergeyMosin** [comment]
Ok, I see the confusion...
It shows appointments in one week range from today.
Let's say today is Tuesday and you have appointments setup only for the next week Mon-Fri. The system will consider the following days:
This weeks Tue (1), Wed(2), Thu(3), Fri(4), Sat(5). Next week: Sun(6), Mon(7). Therefore the only available  appointments from the system's perspective are on day 7 (Mon). In other words, it counts empty days.

Maybe it should grab 16 days from today and show the first 7 NOT EMPTY days.
Does this make sense ?

**Comment by fancycode** [comment]
Maybe the list could include the empty days (grayed out)? That way the user can see that the next 7 days from the current date are shown.

**Comment by nolens** [comment]
@small1 
fixed in version 1.10
please close this issue.
