### ISSUE TITLE
Love to see this! Had a bit of info I wanted to share

### ISSUE THREAD

**Issue by jcklpe** [SergeyMosin/Appointments#71]
Very cool seeing this! Very cool. 

I'm a fan of Calendly and I'm curious if you've looked at it at all for UX stuff? I think they structure the booking process really well. 

Also there's an open source alternative called "Easy Appointments" : https://github.com/alextselegidis/easyappointments

Anyway don't want to bother. just thought maybe those approaches would be helpful to compare with.

**Comment by SergeyMosin** [comment]
tag #87 
Thanks
