### ISSUE TITLE
[BUG] Make it work with shared calendars

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#73]
Thank you very much for helping to trace down #72, this request is connected with that, but I do want to have a clean start.

My usecase:
In my setup I have a keyaccount, who owns everything (calendars, decks, talk-groups etc.). That keyaccount, which is in fact not used by a human, also owns an onboarding-calendar. That calendar is shared with me and a few others. I then create appointments in this calendar, so, when someone confirm that appointment, I or my collegues take care of that event.

Problem:
After tracing down #72, it turns out, that mails aren't sent, when it's a shared calendar.

Required solution:
Appointments App also works with this use case.

Alternate:
Shared calendars shouldn't be shown in appointment app at all.

**Comment by SergeyMosin** [comment]
Shared calendar support is fixed in version 1.4.12, write(edit) permission is now also required to use the calendar.

Thank you very much for reporting and debugging
