### ISSUE TITLE
[Feature] The public links doesn't work in a iframe

### ISSUE THREAD

**Issue by mtalmont** [SergeyMosin/Appointments#74]
This application is very useful, thank you !
I try to integrate public link in a Worpress Website. 
i use iframe and allow all.
I configured Header X-Options in Apache2 and .htaccess .

Some shared links in nextcloud like calendar link work in my iframe but not for reserved appointments...
![Capture du 2020-05-07 16-54-42](https://user-images.githubusercontent.com/19665437/81309989-d660b900-9083-11ea-98b6-2a6a94eaa0e5.png)

**Comment by SergeyMosin** [comment]
This is more of security feature than a bug. Here is more info: https://w3c.github.io/webappsec-csp/#directive-frame-ancestors
However, I guess there could be admin level override for this

**Comment by nickian** [comment]
This would be much more useful if it could be embedded as an iframe or with a javascript tag. Is there an easy way to tell nginx or Apache to allow it?

**Comment by SergeyMosin** [comment]
I think ``@NoSameSiteCookieRequired`` annotation (https://github.com/nextcloud/user_saml/pull/159 and https://github.com/nextcloud/calendar/issues/169) is needed in the code and an option to add domains/urls **into** which the "public appointments page" is going to be embedded as per https://github.com/SergeyMosin/Appointments/issues/74#issuecomment-625449788.

Next release should be good for embedding.

**Comment by SergeyMosin** [comment]
v1.5.0
iframe embeddable URL is available under ``Public Page [...] > Show URL/link > Show iframe/embeddable``
Plus additional instruction in the Help/Tutorial section

**Comment by mtalmont** [comment]
Thank you ! I will try that wen i have some time.
