### ISSUE TITLE
[feature] Show only avaliable days in web form

### ISSUE THREAD

**Issue by menelic** [SergeyMosin/Appointments#78]
thanks for a great app, its especially great for coordinating across time zones. A request to enhance usability: Please dd an option to show only the days on which appointment slots are available so users do not have to scroll through and click on "empty" days where there is no appointment. 

In addition, it would be great if the proposed times for appointments are shown immediately without users needing to click to reveal them.

For any larger organisation where sub groups are invited for different meetings and individuals might be part of 2 or more groups this would be a huge time saver. For organisations with members across many time zones, the ability to see the local times of several proposed meetings at a glance would be a huge utility bonus.

**Comment by SergeyMosin** [comment]
> option to show only the days on which appointment slots are available so users do not have to scroll through and click on "empty" days where there is no appointment.

Uncheck ``Customize Public Page > Show Empty Days``

![empty_days](https://user-images.githubusercontent.com/10747559/81818855-9030ad00-94fc-11ea-9ae4-03121570dce7.jpg)

> 1. it would be great if the proposed times for appointments are shown immediately without users needing to click to reveal them
> 2. ability to see the local times of several proposed meetings at a glance

#24 is the placeholder for UI customization features
