### ISSUE TITLE
Version 1.0.5 internal server error

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#8]
This is what i have in the nextcloud log

 {"reqId":"eOnb5Yrozy2ygdBVHCdm","level":3,"time":"2020-02 -25T23:19:40+00:00","remoteAddr":"2.64.37.85","user":"jobe","app":"index","method":"GET","url":"/apps/appointments/","message":{"Exception":"ParseError","Message":"syntax error, unexpected ')'","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":322,"function":"Composer\\Autoload\\includeFile","args":["/var/www/nextcloud/apps/appointments/lib//Controller/PageController.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"function":"spl_autoload_call","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":98,"function":"__construct","class":"ReflectionClass","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":415,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":112,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Appointments\\Controller\\PageController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Appointments\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"appointments.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"appointments.page.index"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"appointments.page.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/appointments/"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/appointments/lib/Controller/PageController.php","Line":279,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.1.3"}

**Comment by SergeyMosin** [comment]
Fixed in 1.0.6
So weird PHP7 did not throw this error.

Thanks
