### ISSUE TITLE
[feature] Add option to "noindex" public appointment pages

### ISSUE THREAD

**Issue by nolens** [SergeyMosin/Appointments#80]
Objective: 
- make sure search engines don't crawl the public appointment pages

suggestion: 
- add option to add rel="noindex, nofollow" tag in html code of public page

**Comment by SergeyMosin** [comment]
Available in version 1.4.16 
``Customize Public Page > Advanced Settings > Add "noindex" meta tag``

``<meta name="robots" content="noindex">`` is appended to the ``<head>`` section as per https://support.google.com/webmasters/answer/93710

**Comment by nolens** [comment]
So quick - well done, thanks so much, @SergeyMosin !

**Comment by Dubidubiduu** [comment]
> 
> 
> Available in version 1.4.16
> `Customize Public Page > Advanced Settings > Add "noindex" meta tag`
> 
> `<meta name="robots" content="noindex">` is appended to the `<head>` section as per https://support.google.com/webmasters/answer/93710

I don't see any reason this isn't the default setting.

**Comment by SergeyMosin** [comment]
@Dubidubiduu backward compatibility
