### ISSUE TITLE
Ability to hide empty events

### ISSUE THREAD

**Issue by kominoshja** [SergeyMosin/Appointments#82]
First of all, I want to thank @SergeyMosin and all contributors that made this app possible. The ability to use Nextcloud as an appointment management system is a life-saver. I wanted to suggest a feature, but i'm not sure if this is the right place? Never the less, let me describe what I would suggest.

The UX gets quite clunky when you already have many events in one day and then you add available appointments. I think it would be helpful if users could decide whether or not they want to see 'Available' meeting spots

**Comment by SergeyMosin** [comment]
>The UX gets quite clunky...

I was thinking the same thing. The plan is to add option to set a different calendar for **confirmed** appointments. That way the calendar with available time slots can be hidden, somewhat similar to https://github.com/SergeyMosin/Appointments/issues/17#issuecomment-596716667 , plus it will pave the way to auto-generated/recurrent weekly templates/schedules.
Current target v1.5.*

**Comment by kominoshja** [comment]
I think that's a fix!

**Comment by kominoshja** [comment]
Amazing job! Thanks :)
