### ISSUE TITLE
[Request]: Extended note in confirmation mail

### ISSUE THREAD

**Issue by gitkald** [SergeyMosin/Appointments#83]
A note in the confirmation mail that you should keep this mail, in case you want to cancel the appointment.

Many people simply delete such a mail and then the slot cannot be opened again in case of a cancellation.

**Comment by SergeyMosin** [comment]
Option for additional text in the validation and confirmation should be available in the next release.

**Comment by SergeyMosin** [comment]
Similar to #69 (3)

**Comment by SergeyMosin** [comment]
Available in v1.5.0 ``Email Settings > Additional VALIDATION/CONFIRMATION email text``

**Comment by SergeyMosin** [comment]
Cancellation link is added to confirmation email automatically in v1.6.0
