### ISSUE TITLE
Remove Calendar Entries for Past Dates?

### ISSUE THREAD

**Issue by nickian** [SergeyMosin/Appointments#84]
Is it possible to have a script automatically clean up the unconfirmed "available" entries in the calendar once the date has passed? It seems really messy to have all of these unused entries saved forever.

**Comment by SergeyMosin** [comment]
Available in v1.5.0 ``Manage Appointment Slots > Remove Old Appointments``

**Comment by nolens** [comment]
So cool! Thanks @SergeyMosin . Working fine on my side!
