### ISSUE TITLE
Appointments 1.4.16 and NextCloud 18.04, Public Link not provided.

### ISSUE THREAD

**Issue by jjanarnava** [SergeyMosin/Appointments#85]
Hello Sergey, up to the entry of the appointmens in my calendar everything looks good, however I am not able to get a PUBLIC link. I can hoover over "Copy Public Link! but klicking it, I do not have a publich link at all in my Copy and Paste Memory. Just something I have copied before.

How to get or construct the public link? Thank you.

**Comment by SergeyMosin** [comment]
What browser are you using ?
Can you check the browser's console for errors ?

Thanks

**Comment by jjanarnava** [comment]
It is Firefox 68.8.0 the debug info is 
copy error: undefined                       script.js:2:824345
TypeError: this is undefined             script.js:2:824368

In Chrome it is OK: https://cloud6.cape-coop.net/index.php/apps/appointments/pub/nl2eabh4ag%3D%3D/form

Thank you for your fast reply.

**Comment by Bellusterra** [comment]
Hi Sergey, I seem to be having the same issue. Everything seems to work but cannot copy the public link. Just installed the app on Nextcloud 18.04 using ios web broswers duck duck go, safari and chrome. None seem to be able to copy. Thank you for such a great app and addition to Nextcloud.

**Comment by SergeyMosin** [comment]
Fixed in v1.5.0 ``Public Page [...] > Show URL/link``

**Comment by Bellusterra** [comment]
Works perfectly! Thank you @Sergey. Any way to Additionally add the copy to clip board for the “Show iframe/embeddable” after hitting the dropdown arrow to copy on mobile? I really like the app really great work, again thank you so much.

**Comment by Bellusterra** [comment]
My apologies I realized just changed /pub/ to /embed/ in the link works just as well. Thank you @Sergey
