### ISSUE TITLE
Automatically create time Slots / Weekly Templates

### ISSUE THREAD

**Issue by krheinwald** [SergeyMosin/Appointments#87]
It would be great to have the flexible approach which Calendly offers, i.e. to automatically create time slots based on working hours (e.g. 9-17) and free time in the calendar.

**Comment by SergeyMosin** [comment]
This is similar to #39 (recurring appointments).
I am going to close this one and the discussion should continue over at #39

**Comment by krheinwald** [comment]
Actually, this is not the same. I guess you don'r know Calendly?
My use case is that I define working hours eg. Mo.-Fr. 9-17 and an associated calendar. I then define generic time slots of 1h or 30min or 90mins. A user/customer can then claim any free slot of that length which is available in the associated calendar. Existing entries already present calendar (e.g. another meeting not assoicated with the appointments, but synced in from Outlook) are automatically blocked. I.e. the available slots are always created on the fly when a user wants to book an appointment depending on my workin hours and availabel time.

My I kindly suggest you have a look at  https://calendly.com ?

**Comment by SergeyMosin** [comment]
The plan so far is a weekly template. You would set once and it would be available for a preset number of weeks into the future. And of course, existing/conflicting time slots would be blocked.

**Comment by SergeyMosin** [comment]
"Weekly Template" timeslot mode comment...

**Comment by SergeyMosin** [comment]
**Reminder**: exclude holidays as per #88

**Comment by alexbijma** [comment]
Hi, what a great app is this! But actually i'm looking very much forward to more features;-)

I'm at least looking for something like Calendly. Especially so my customers can book a time slot. Those time slots i want to set manually(recurring each week with exceptions). But not all day, only some hours per day. For example:
Mon 10-12 and 14-15
Th 9-10 and 13-14
We 10-11 and 14-15
etc.. customers can only pick one slot for half an hour.

This would make it possible to let customers make an appointment with me by themself.

Keep up the good work @SergeyMosin

**Comment by nolens** [comment]
@alexbijma 

> I'm at least looking for something like Calendly. Especially so my customers can book a time slot. Those time slots i want to set manually(recurring each week with exceptions). But not all day, only some hours per day. For example:
> Mon 10-12 and 14-15
> Th 9-10 and 13-14
> We 10-11 and 14-15
> etc.. customers can only pick one slot for half an hour.> 

This is exactly what the plugin does. Except automatic repetition of dates - this feature is planned for the future, as is described here in #87  .

**Comment by alexbijma** [comment]
@nolens sounds good, i'm gonna check it out

**Comment by SergeyMosin** [comment]
Available in v1.8.*
