### ISSUE TITLE
[feature] change free appointment slot mechanism

### ISSUE THREAD

**Issue by mokkin** [SergeyMosin/Appointments#88]
Actually you have to add free time slots, day by day, week by week for the whole year as I understand.
I think this way to complicated and quite time consuming. In addition it is filling the calendar with useless entries.
In our current booking software the admin or user can define working hours for the whole company or any specific user. Those working hours are then bookable for clients with the exception for holidays or existing appointments.

I hope you got what I mean. Do you think you can change that?

**Comment by SergeyMosin** [comment]
"Weekly Template" time slot mode can be discussed here: #87 
Also recurrence is supported in _External Mode_ see https://github.com/SergeyMosin/Appointments/issues/100#issuecomment-653780651
