### ISSUE TITLE
[Feature] Talk integration

### ISSUE THREAD

**Issue by Bellusterra** [SergeyMosin/Appointments#92]
A check box with the option to auto generate a public chat room and link attached within the email and the same link in the calendar notes. The lobby can be set to on by default. 
  Having this functionality would extend appointment calls to what might normally be a long distance call on the phone. With Talk being able to open in most browsers now, without the need to download anything, it would work really well in this use case.

**Comment by jpbraun** [comment]
This would be a really great feature!

**Comment by SergeyMosin** [comment]
Looks like this feature is getting fast-tracked thanks to @jpbraun and his public school ([www.igs-lengede.de](https://www.igs-lengede.de/))
The plan so far is:

- Automatically create a Talk room and attach the link to the email when an appointment is **confirmed**. Room name format {Attendee name} {date/time} Ex. ``Sergey Mosin 15/09/20 20:22``
- Automatically update room name {date/time} if the appointment is rescheduled
- Delete the room if the appointment is deleted

Extended features as per https://github.com/SergeyMosin/Appointments/issues/79#issuecomment-687659269
- Customizable email text (Default will be: ``Chat/Call link: https://my_domain.com/call/kzu6e4uv``)
- Optionally auto set "Lobby start time'' to the appointments start time
- Optional password protection

Anything missing ???

**Comment by jpbraun** [comment]
Sound's great!

**Comment by RoundAboutWEB** [comment]
Unfortunately I did not understand the solution, but I find the idea extremely good and helpful. 
How can you now create a new talk show with Appointments?
new talk --> new room
New talker should not see the previous entries in a room, therefore a new room.

**Comment by jpbraun** [comment]
Sergey needs a few days to implement the feature. Coding needs time. Don't hurry.

**Comment by SergeyMosin** [comment]
Version 1.7.4 ``Settings > Talk Integration``

![talk-integration1](https://user-images.githubusercontent.com/10747559/93731721-420f7280-fb9c-11ea-9a8e-bb3eab78e748.jpg)

_Lobby timer_ a.k.a. _lobby start time_ a.k.a. _lobby auto-disable_ is NOT set automatically yet, because a couple of tests failed most like due to daylight savings. If you are planing to use it, **make sure to let your guests in manually**.  

![talk-integration-lobby](https://user-images.githubusercontent.com/10747559/93731042-569e3b80-fb99-11ea-8977-82ca49446594.jpg)

P.S. _FYI: New **Nextcloud 19** centered email template is somewhat broken, should be fixed in the next update._

**Comment by small1** [comment]
It would be good with an option to select calendar/Calendars for which online appointments or to select which times that should be added as online events. (Or both)

**Comment by small1** [comment]
And templateable name for the room as an advanced feature.

**Comment by jpbraun** [comment]
Great Feature! Thank you very much Sergey. We just need one additional functionality. For the Parent's Day the parents have to have the choice between the Talk-Room and the real Classroom. A selection field would be very helpful (Face-To-Face-Meeting / Online-Meeting (Audio/Video) || Treffen vor Ort / Online-Meeting (Audio/Video)
![2020-09-21_140150](https://user-images.githubusercontent.com/31374152/93764758-f8626e80-fc13-11ea-8bd1-33c6998242c3.jpg)
In addition, a short text field would be helpful (but not absolutely necessary).

**Comment by Bellusterra** [comment]
@jpbraun I agree, definitely necessary, I’m not sure how easy it can be implemented, but giving the host the option when creating the calendar “open slots” to create per individual time slot the option to be available as either only online, only at the location (in person) or both with the client then having the option on the front end as your picture shows to choose. Their could even be the option on the client end when picking their scheduled time to filter for face to face meetings only or online options which could grey out the time slots and days that don’t offer that.

**Comment by SergeyMosin** [comment]
@small1 Thanks for the contribution

-----

>It would be good with an option to select calendar/Calendars for which online appointments or to select which times that should be added as online events.

>giving the host the option when creating the calendar “open slots” to create per individual time slot the option to be available as either only online

This should relatively easy when #87 is implemented. As a quick fix, a string like ``__no_talk__`` for example, in an event's description can indicate an override and disable Talk integration for that particular appointment. Plus there is definitely going to be an override option for different pages in a multi-page setup.

----- 

> templateable name for the room as an advanced feature.

What tokens are needed for the template? I can think of ``GuestName``, ``DateTime``, ``TimeZone``, ``OrganizerName``.

-----

> choice between the Talk-Room and the real Classroom. A selection field would be very helpful (Face-To-Face-Meeting / Online-Meeting (Audio/Video)

This should be easy, but would have to be a select drop-down.
Override-able defaults would be:
Label: ``Meeting Type``
Placeholder option text: ``Select meeting type``
NO_TALK option text: ``In-person meeting``
ADD_TALK option text: ``Online (audio/video)``

When NO_TALK options is selected the "NO_TALK option **text**" will be added to the description.

-----

> In addition, a short text field would be helpful (but not absolutely necessary).

This is related to #24 

-----

> There could even be the option on the client end when picking their scheduled time to filter for face to face meetings only or online options which could grey out the time slots and days that don’t offer that.

Good idea but will have to waaaaaaaaaaaait for a while.................. :)

**Comment by jpbraun** [comment]
> his should be easy, but would have to be a select drop-down.
Override-able defaults would be:
Label: Meeting Type
Placeholder option text: Select meeting type
NO_TALK option text: In-person meeting
ADD_TALK option text: Online (audio/video)

That sounds fantastic!

**Comment by small1** [comment]
+1 om this

/Johan

**Comment by Bellusterra** [comment]
I apologize @small1, I didn’t mean to leave you out of my last comment, being that it was just a rewording of your suggestion:). I think I read over it really quick and then thought I have another great idea haha. Which was of course your idea. Thank you.

**Comment by SergeyMosin** [comment]
Version 1.7.6 ``Settings > Talk Integration`` Add "Meeting Type" form field option is now available.

![talk-integration-meeting-type](https://user-images.githubusercontent.com/10747559/93881148-8853f700-fcac-11ea-9e77-0a0cdd04ab6f.jpg)


NOTICE: Nextcloud **19** users MUST update **1.7.5 -> 1.7.6** (email template bug in v1.7.5)

**Comment by Bellusterra** [comment]
Wow! That was fast!

**Comment by jpbraun** [comment]
> Wow! That was fast!

I agree!

**Comment by nolens** [comment]
@Bellusterra 
Please close this issue. The feature has been implemented.

**Comment by RoundAboutWEB** [comment]
This function will work fine, but why I can't edit "Customize email text:"?

**Comment by Bellusterra** [comment]
@nolens Thank you.
