### ISSUE TITLE
[Feature] Preferred Contact Method Boxes

### ISSUE THREAD

**Issue by Bellusterra** [SergeyMosin/Appointments#93]
Maybe 3 boxes next to or above the “Book Now” button

Preferred Contact Method
   - [ ] Phone  - [ ] E-Mail   - [ ] Video Call
If the - [ ] Video Call box is checked then it can then auto generate a public chat room with lobby and links. I know @Sergey you are trying to keep things as clutter free as possible so I hope this wouldn’t take away from how good everything looks currently.

**Comment by SergeyMosin** [comment]
Most of it is covered in #92 , the rest will have to wait until there is some kind of progress in #24
