### ISSUE TITLE
Thoughts about combination of Feature requests

### ISSUE THREAD

**Issue by andreasgremm** [SergeyMosin/Appointments#95]
@SergeyMosin : Great APP, very usefull! Thank you for this great work!

We are a fire brigade in Germany and Appointments would be a great tool to organize different health checks required, reserve time for trainings, reserve rooms, cars, ... everything like this.

As I see the different feature requests regarding:
- Recurring Appointments
- Number of Attendees
- Assignment of Appointments to Calender not by user (having multiple locations or reasons for appointment) 
  + The user and organization information should be definable per calendar which would enable one user to create different type of appointments.

I would love all of them.

But I agree that it might be difficult to change the wonderful app to enable all this and be backward compliant.

I would like to ask you to think about the following approach:

A new version (eventually a fork) of the appointment app could have an additional functionality providing step 1 and step 3 in the following sequence.

1.  Definition of an Appointment:
This step is doing the definition of an appointment probably as an appointment template.
This template could be used to initiate a calendar entry. This could also held an indicator of the maximum number of attendees. The template could be editable (if necessary) and then be used again for a new series of appointments. Multiple templates could be defined and used in different calendars for different purposes (e.g. Health checks, Room reservations, Training attendance ...)

2. In the normal calendar app the management (recurring, copy, movement etc.) could be done. In conjunction with the calendar app team. It needs to be defined which parameters of a calendar entry are needed for appointments to ensure consistency while working in the calendar app.
This could also include certain parameter changes as "maximum nr. of attendees". Or the change of the location for a specific entry etc.

3. The reservation part with all the necessary steps is done as today extended by new functionality of maximum numbers of attendees and perhaps other features.

Kind regards,
Andreas

**Comment by SergeyMosin** [comment]
External Mode with recurrence support is available in v1.6.0  see https://github.com/SergeyMosin/Appointments/issues/100#issuecomment-653780651

_Number of Attendees_ can be discussed here: #54 

_Assignment of Appointments to Calender not by user_ is here #81
