### ISSUE TITLE
show appointment title in the form

### ISSUE THREAD

**Issue by ccoenen** [SergeyMosin/Appointments#97]
Right now, the form looks like this, and my calendar looks like this:

![appointments in calendar and web interface](https://user-images.githubusercontent.com/124909/84246633-2d383300-ab07-11ea-8548-706af067b6aa.png)

I would like the form to display the appointment's current title, so I could do something more or less like in this mockup:

![grafik](https://user-images.githubusercontent.com/124909/84251134-3926f380-ab0d-11ea-9b29-e68c5c5f4396.png)

Another possibility for the (basically) same thing would be to display its categories, which would work fine for me as well.

**Comment by SergeyMosin** [comment]
Available in version 1.6.3...

If an event's **title/summary starts with an "_" character** then the title will be displayed next or below the time in the form. For example: "_Coaching"  will be displayed as "Coaching"

<img src="https://user-images.githubusercontent.com/10747559/87454633-3e76d280-c5d2-11ea-8779-1c4cc26c78e9.jpg" width="640">
