### ISSUE TITLE
Appointment lead time (in lack of a better word) or "bookable until X at the latest"

### ISSUE THREAD

**Issue by ccoenen** [SergeyMosin/Appointments#99]
I sometimes find myself in a situation where I almost miss an appointment because they can be booked at very short notice. I would love it, if appointments somehow had different amounts of lead time.

At the moment, an open slot starting at 08:00 can be booked until 07:59, so I might have looked into my calendar a few minutes early and have missed it. It would be great have a setting to define some kind of minimum time before the appointment. I think this must be a setting (not everyone will want this to be the same value!).

It may even be a thing that differs *per appointment*: If it's the first appointment in the morning, I would like to have a little more lead time, so I can see the night before, that I need to come in early tomorrow. Maybe I also have additional spots, that are only available for early bookers. Things like that.

**Comment by SergeyMosin** [comment]
Available in version 1.6.3...
```
Manage Appointment Slots > Advanced Settings > Minimum lead time
```

Is there a better term than ``Minimum lead time`` ??
